### PR TITLE
Various fixes for PR 1783

### LINKED ISSUE #3839: gcc 4.6 override keyword
We still support gcc 4.6 but it doesn't support the override keyword (see http://stackoverflow.com/a/15776434), so I am getting compiler errors:
```
/ssd/deal-git/include/deal.II/lac/trilinos_sparse_matrix.h:2317:25: error: expected ‘;’ at end of member declaration
/ssd/deal-git/include/deal.II/lac/trilinos_sparse_matrix.h:2335:43: error: expected ‘;’ at end of member declaration
...
```

### LINKED ISSUE #3841: Trilinos without MPI compilation fails
see https://cdash.kyomu.43-1.org/viewBuildError.php?buildid=3900

@jppelteret can you take a look please?

### PR DESCRIPTION
**Pull request by jppelteret**
Remove C++11 features not supported by GCC 4.6.
Fixes #3839

Amend Trilinos-related classes for when using non-MPI Trilinos build
Fixes #3841

### CODE REVIEW

**Comment by drwells** [comment]
I am not particularly familiar with this class, but I see no reason why we cannot use the implicit `operator=` here: we can get rid of the whole thing, right?

For the record GCC 4.4 supports `=default` so we can use that one.

**Comment by jppelteret** [comment]
@drwells Thats true. I'll just remove `operator=`.

**Comment by jppelteret** [comment]
By the way, I'm reticent to remove `#ifdef DEAL_II_WITH_CXX11` for this class. Its only meant for use with `LinearOperator`s and they require `C++11`. So there's really no point in building one without the other.

**Comment by jppelteret** [comment]
*reluctant. Its been a long day...

**Comment by drwells** [comment]
I was trying to make a second point and was not very clear about it. 

In general (regardless of the function we consider) we may may use `=default` with C++11 but not `override`.

**Comment by jppelteret** [comment]
No, I did understand what you said, thanks. Regardless of whether `GCC 4.4` supports `=default`, I decided to move that and use your idea of an implicit definition for `operator=`. I can't see a reason why this wouldn't work.

My comment regarding the `#ifdef` directive followed [another comment](https://github.com/dealii/dealii/issues/3839#issuecomment-274562638). I should have referenced this comment at that time.

**Comment by jppelteret** [comment]
@tjhei You're welcome!

I'm working on a fix for #3841 right now. However, I don't have a serial version of `Trilinos` right now. How can I test this? Also, would you like me to add it to this PR?

File: source/lac/trilinos_sparse_matrix.cc [hunk 1]
```diff
@@ -2449,16 +2449,33 @@ namespace TrilinosWrappers
 {
   namespace internal
   {
+    namespace
+    {
+#ifndef DEAL_II_WITH_MPI
```
Comment (jppelteret) [inline source/lac/trilinos_sparse_matrix.cc]: @kronbichler Does this (and its usage below) seem plausible to you?

**Comment by tjhei** [comment]
> However, I don't have a serial version of Trilinos right now.

I think this is less important (I also don't but we are testing this on cdash). If you want, we can address this separately.

File: source/lac/trilinos_sparse_matrix.cc (hunk 1 above)
Comment (kronbichler) [inline source/lac/trilinos_sparse_matrix.cc]: This looks nice! Exactly the way I would have done it.

Comment (jppelteret) [inline source/lac/trilinos_sparse_matrix.cc]: Thanks for the confirmation! Apologies that I didn't make the comment several lines further down. 

One thing that I'm curious about though: does `#ifndef DEAL_II_WITH_MPI` strictly mean that `Trilinos` is built without `MPI`? Can we not link to, for example, a serial build of `Trilinos` but a parallel build of `PETSc`?

**Comment by kronbichler** [comment]
The serial Trilinos compiles fine on my machine, i.e., https://cdash.kyomu.43-1.org/buildSummary.php?buildid=3900

**Comment by jppelteret** [comment]
Great, glad that's sorted now :-)

File: source/lac/trilinos_sparse_matrix.cc (hunk 1 above)
Comment (kronbichler) [inline source/lac/trilinos_sparse_matrix.cc]: I don't think you can link a serial Trilinos built with a parallel built of PETSc. We only allow a serial built of Trilinos if deal.II is non-MPI. (Serial Trilinos is somewhat of a side feature that we do not test extensively. I have one copy on my computer but I hardly ever use it. We probably should have never introduced it because it requires explicitly distinguishing between the `Communicator` objects as you observed.) I'm not sure about the PETSc configuration options we offer, but I don't think we can have PETSc without MPI.

Comment (jppelteret) [inline source/lac/trilinos_sparse_matrix.cc]: Thanks for the clarification!
