### PR TITLE
Patterns: Fix parsing lists of lists

### LINKED ISSUE #15227: Parameter Pattern for list of lists is not parsed correctly
## Description of problem
`dealii::Patterns::pattern_factory` incorrectly parses pattern strings for lists of lists from a description. This causes strings to incorrectly match a pattern they should not match and vice versa.

For example:
`[List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]> of length 0...4294967295 (inclusive)]`
is parsed as
`[List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 0...4294967295 (inclusive)]> of length 3...3 (inclusive) separated by < >]`
Note, the amount of elements in each list and the separator changes.

### Proof of concept:
```c++
#include <deal.II/base/patterns.h>

#include <iostream>

int
main()
{
  // Example parameter pattern for a list of lists
  const std::string description =
    "[List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]> of length 0...4294967295 (inclusive)]";
  // The above pattern describes a list of lists of 3 doubles, e.g.:
  // "1 2 3,1.2 3.2 1.2" is valid
  // "1.2,1.3,1.4,1.6 1.2,1.3,1.0,1.5,6.5,5.1 7.6,13.5,1.5" is not valid

  // Parse the description in deal.ii
  std::unique_ptr<dealii::Patterns::PatternBase> pattern = dealii::Patterns::pattern_factory(description);

  // Write the original and parsed description
  std::cout << "Original description: " << std::endl
            << description << std::endl
            << std::endl
            << "Parsed description: " << std::endl
            << pattern->description(dealii::Patterns::PatternBase::Machine)
            << std::endl;
  // Output:
  // Original description:
  // [List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]> of length 0...4294967295 (inclusive)]
  //
  // Parsed description:
  // [List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 0...4294967295 (inclusive)]> of length 3...3 (inclusive) separated by < >]

  // First check, should be a match
  std::cout << "First check: \"\" is "
            << (pattern->match("") ? "a match" : "not a match")
	    << std::endl;
  // Output:
  // First check: "" is not a match

  // Second check, should be a match
  std::cout << "Second check: \"1 2 3,1.2 3.2 1.2\" is "
            << (pattern->match("1 2 3,1.2 3.2 1.2") ? "a match" : "not a match")
            << std::endl;
  // Output:
  // Second check: "1 2 3,1.2 3.2 1.2" is not a match

  // Third check, should not be a match
  std::cout << "Third check: \"1.2,1.3,1.4,1.6 1.2,1.3,1.0,1.5,6.5,5.1 7.6,13.5,1.5\" is "
            << (pattern->match("1.2,1.3,1.4,1.6 1.2,1.3,1.0,1.5,6.5,5.1 7.6,13.5,1.5") ? "a match" : "not a match")
            << std::endl;
  // Output:
  // Third check: "1.2,1.3,1.4,1.6 1.2,1.3,1.0,1.5,6.5,5.1 7.6,13.5,1.5" is a match

  // All checks fails
}
```

## Source of error
I believe this is due to the List::create method in dealii/source/base/patterns.cc:
https://github.com/dealii/dealii/blob/edf8d927d255ed3cd5055616f5e26b0d90fade2c/source/base/patterns.cc#L787
In line 787, `std::getline(is, str, '>');` is intended to get the pattern of the elements of the list. In the above example, this would be `[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]` for the outer-most list. Here, however, it actually pulls out `[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]`, due to the `>` following the inner-most Double-pattern. Due to error-correction, this is not an invalid pattern, but can still be parsed. This, however, produces unexpected results.

__Instead of finding the first occurence of `>` with `std::getline()`, I believe the last occurence of `>` should be used.__

### Proof of concept:
```c++
#include <deal.II/base/patterns.h>

#include <iostream>

int
main()
{
  // Example parameter pattern for a list of lists
  const std::string description =
    "[List of <[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]> of length 0...4294967295 (inclusive)]";
  // The above pattern describes a list of lists of 3 doubles, e.g.:
  // "1 2 3,1.2 3.2 1.2" is valid
  // "1.2,1.3,1.4,1.6 1.2,1.3,1.0,1.5,6.5,5.1 7.6,13.5,1.5" is not valid

  // First part of pattern
  const char* description_init = "[List";

  // Start deal.ii code: dealii/source/base/patterns.cc #783
  std::istringstream is(description);
  is.ignore(strlen(description_init) + strlen(" of <"));

  std::string str;
  std::getline(is, str, '>');
  // End deal.ii code: dealii/source/base/patterns.cc #787

  // Write results of parsing.
  // Expected results:
  // Subpattern is "[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]> of length 3...3 (inclusive) separated by < >]"
  std::cout << "Subpattern is \"" << str << "\"" << std::endl;
  // Output:
  // Subpattern is "[List of <[Double -MAX_DOUBLE...MAX_DOUBLE (inclusive)]"

  // Subpattern is not correct
}
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #15227 by finding the correct set of matching angular brackets in the description.

### CODE REVIEW

File: source/base/patterns.cc [hunk 1]
```diff
@@ -780,15 +780,30 @@ namespace Patterns
...
+          {
+            tmp_it = std::find_if(tmp_it + 1, description.end(), [](char c) {
+              return (c == '>' || c == '<');
+            });
+            Assert(tmp_it != description.end(),
+                   ExcMessage("Couldn't find a closing '>' in description!"));
+            if (*tmp_it == '<')
+              ++n_open_angular;
+            else
+              --n_open_angular;
```
Comment (bangerth) [inline source/base/patterns.cc:798]: A perpetual problem in parsing any kind of file is finding a matching closing parenthesis/token. I have no idea why the heck that has not ever been addressed by a standard function.

File: source/base/patterns.cc [hunk 2]
```diff
@@ -780,15 +780,30 @@ namespace Patterns
...
-        std::string str;
-        std::getline(is, str, '>');
+        int  n_open_angular = 1;
+        auto tmp_it         = it - 1;
+        while (n_open_angular > 0)
+          {
+            tmp_it = std::find_if(tmp_it + 1, description.end(), [](char c) {
+              return (c == '>' || c == '<');
+            });
+            Assert(tmp_it != description.end(),
```
Comment (bangerth) [inline source/base/patterns.cc:793]: Can you make this an `AssertThrow`? You'r often parsing run-time input.

File: source/base/patterns.cc [hunk 3]
```diff
@@ -780,15 +780,30 @@ namespace Patterns
...
+          }
 
-        std::unique_ptr<PatternBase> base_pattern(pattern_factory(str));
+        std::string                  base_pattern_string(it, tmp_it);
+        std::unique_ptr<PatternBase> base_pattern(
+          pattern_factory(base_pattern_string));
 
-        is.ignore(strlen(" of length "));
+        std::istringstream is(
+          std::string(tmp_it + strlen(" of length "), description.end()));
```
Comment (bangerth) [inline source/base/patterns.cc:806]: std::strlen. Same at the top of the patch.

**Review by bangerth — CHANGES_REQUESTED** [review]

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Thanks. I had not realized that there were many places in the file that used `::strlen`...
