### PR TITLE
Catch exceptions in main() in later steps.

### LINKED ISSUE #4070: Add top level exception handling to tutorials
This was caught by Coverity: see #4012 for details. Briefly, we don't always catch exceptions in the `main` functions of tutorials.

I am working on this now: hopefully no one else is doing the same thing in another patch.

### PR DESCRIPTION
**Pull request by drwells**
This was caught by Coverity.

We decided not to implement this in early steps to keep things simple: I marked those, in Coverity's GUI, as 'intentional' and 'ignore'.

Closes #4070.

### CODE REVIEW

File: examples/step-32/step-32.cc [hunk 1]
```diff
@@ -3727,11 +3727,11 @@ int main (int argc, char *argv[])
...
   using namespace dealii;
 
-  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv,
-                                                      numbers::invalid_unsigned_int);
-
   try
     {
+      Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv,
+                                                          numbers::invalid_unsigned_int);
+
```
Comment (bangerth) [inline examples/step-32/step-32.cc]: Moving the code here is probably a bad idea. If an exception is thrown,  the MPI object on that process will be destroyed. This will call MPI Finalize which will dead lock because the other processes are not at the same place...

Comment (drwells) [inline examples/step-32/step-32.cc]: That is a good point (and a very subtle one!). I'll fix things.

**Comment by bangerth** [comment]
Thanks.

If coverity complains, maybe it's worthwhile marking the constructor of `MPI_InitFinalize` as `DEAL_II_NOTHROW`?

**Comment by drwells** [comment]
If we do that and that constructor throws an exception anyway then we immediately abort, right?

Since the destructor won't run if there is an exception in the constructor we can't really handle exceptions thrown here anyway (we never finalize PETSc/SLEPc/MPI) so it makes sense to try and quit everything if this happens.

**Comment by bangerth** [comment]
> If we do that and that constructor throws an exception anyway then we immediately abort, right?

I don't recall. It may be undefined behavior. We may want to make sure that doesn't happen within the constructor by ensuring that we really do just abort. Nothing good can come of it if we can't initialize MPI. There is no point in continuing.
