### PR TITLE
Include the top XML sections in an error message.

### LINKED ISSUE #3151: ParameterHandler and top level XML sections
From #3122: it would be nice if, when `ParameterHandler` encounters an XML file with multiple top level sections, if it could print the names of such sections as part of a helpful exception message.

### PR DESCRIPTION
**Pull request by drwells**
This commit improves ExcInvalidXMLParameterFile by printing out the names of the top level XML sections in an exception message.

Closes #3151.

### CODE REVIEW

File: source/base/parameter_handler.cc [hunk 1]
```diff
@@ -1936,11 +1936,28 @@ void ParameterHandler::parse_input_from_xml (std::istream &in)
...
+                        << "The top level elements are:\n";
+
+      unsigned int entry_n = 0;
+      for (boost::property_tree::ptree::iterator it = single_node_tree.begin();
+           it != single_node_tree.end(); ++it)
+        {
+          top_level_message << "    "
+                            << it->first
+                            << (entry_n != n_top_level_elements - 1 ? "\n" : "");
+          ++entry_n;
```
Comment (bangerth) [inline source/base/parameter_handler.cc]: maybe put this into the loop header?

File: source/base/parameter_handler.cc [hunk 2]
```diff
@@ -1936,11 +1936,28 @@ void ParameterHandler::parse_input_from_xml (std::istream &in)
...
-                                           + Utilities::to_string(n_top_level_elements)
-                                           + " top-level elements, but there "
-                                           "should only be one."));
+  if (n_top_level_elements != 1)
+    {
+      std::ostringstream top_level_message;
+      top_level_message << "There are "
+                        << n_top_level_elements
+                        << " top level elements, but there should only be one.\n"
+                        << "The top level elements are:\n";
```
Comment (bangerth) [inline source/base/parameter_handler.cc]: I think the error message would be easier to understand if you said somewhere something of the form "While reading a ParameterHandler input file in XML format, ..."

File: source/base/parameter_handler.cc (hunk 1 above)
Comment (drwells) [inline source/base/parameter_handler.cc]: Done.

**Comment by bangerth** [comment]
OK to merge if tester is happy.

**Comment by drwells** [comment]
Hmm, let me see if I can build this under clang myself. I think the tester may just be confused.

**Comment by bangerth** [comment]
Looks to me like @tjhei 's drive is full.

**Comment by drwells** [comment]
Yes, you are right.
