### PR TITLE
Make the error message for non-integer IDs in UNV files clearer.

### LINKED ISSUE #14379: grid_in  unv file error
`terminate called after throwing an instance of 'dealii::StandardExceptions::ExcIO'
  what():  
--------------------------------------------------------
An error occurred in line <864> of file </home/ztdep/Downloads/dealii-9.4.0/source/grid/grid_in.cc> in function
    void dealii::GridIn<dim, spacedim>::read_unv(std::istream&) [with int dim = 2; int spacedim = 2; std::istream = std::basic_istream<char>]
The violated condition was: 
    in.fail() == false
`
[3x3.unv.txt](https://github.com/dealii/dealii/files/9893007/3x3.unv.txt)

### PR DESCRIPTION
**Pull request by drwells**
Fixes #14379.

@ztdepztdep Thanks for the report - this is not so much a bug in the library as an insufficient error message. There's no reasonable way for us to handle this case (how could we convert `OUTER RING` to an integral boundary id?) but we should inform the user what went wrong.

### CODE REVIEW

File: source/grid/grid_in.cc [hunk 1]
```diff
@@ -835,7 +835,31 @@ GridIn<dim, spacedim>::read_unv(std::istream &in)
...
           AssertThrow(in.fail() == false, ExcIO());
-          in >> id;
+          // Ocassionally we encounter IDs which are not integers - we don't
+          // support that case since there is no sane way for us to determine
+          // integer IDs from, e.g., strings.
+          std::string line;
+          // get the newline
+          std::getline(in, line);
+          // get the next line
+          std::getline(in, line);
```
Comment (Rombur) [inline source/grid/grid_in.cc:845]: Did you mean to call `getline` twice? If so please add a comment why you discard the first line

**Review by Rombur — APPROVED** [review]

File: source/grid/grid_in.cc [hunk 2]
```diff
@@ -835,7 +835,33 @@ GridIn<dim, spacedim>::read_unv(std::istream &in)
             n_entities;
 
           AssertThrow(in.fail() == false, ExcIO());
-          in >> id;
+          // Ocassionally we encounter IDs which are not integers - we don't
+          // support that case since there is no sane way for us to determine
+          // integer IDs from, e.g., strings.
```
Comment (masterleinad) [inline source/grid/grid_in.cc:840]:
```suggestion
          // Occasionally we encounter IDs that are not integers - we don't
          // support that case since there is no sane way for us to determine
          // integer IDs from, e.g., strings.
```
