### PR TITLE
Fix (Dynamic)?SparsityPattern::begin() for empty sparsity patterns.

### LINKED ISSUE #7379: SparsityPattern::begin() is broken for an empty sparsity pattern
```
at sparsity_pattern.h:1374
   1371	inline SparsityPattern::iterator
   1372	SparsityPattern::begin() const
   1373	{
-> 1374	  return iterator(this, rowstart[0]);
   1375	}
```
obviously `rowstart` is not initialized, but I would still expect `begin()` and `end()` work for empty objects.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #7379.

### CODE REVIEW

**Comment by tjhei** [comment]
> This looks good to me, but I would just combine all the test cases into one and get rid off of all the `try-catch` clutter.

agreed!

File: tests/sparsity/dynamic_sparsity_pattern_iterator_07.cc [hunk 1]
```diff
@@ -0,0 +1,77 @@
+// ---------------------------------------------------------------------
+//
+// Copyright (C) 2004 - 2017 by the deal.II authors
```
Comment (davydden) [inline tests/sparsity/dynamic_sparsity_pattern_iterator_07.cc]: Do we adjust dates?

Comment (bangerth) [reply tests/sparsity/dynamic_sparsity_pattern_iterator_07.cc]: We have a script that will add 2018 next time we run it. The dates are not incorrect: I cloned an existing test, so the new tests' copyright extends back to these older tests.
