### PR TITLE
Fix #3165

### LINKED ISSUE #3165: GridGenerator::hyper_ball + SphericalManifold + MappingQ appears to be broken
I had a small unit test which worked fine a few weeks ago, but with the most recent `develop` version it is broken with
```
An error occurred in line <2596> of file </Users/davydden/libs-sources/deal.ii/davydden/source/fe/mapping_q_generic.cc> in function
    virtual CellSimilarity::Similarity dealii::MappingQGeneric<3, 3>::fill_fe_values(const typename Triangulation<dim, spacedim>::cell_iterator &, const CellSimilarity::Similarity, const Quadrature<dim> &, const typename Mapping<dim, spacedim>::InternalDataBase &, dealii::internal::FEValues::MappingRelatedData<dim, spacedim> &) const [dim = 3, spacedim = 3]
The violated condition was:
    det > 1e-12*Utilities::fixed_power<dim>(cell->diameter()/ std::sqrt(double(dim)))
The name and call sequence of the exception was:
    (typename Mapping<dim,spacedim>::ExcDistortedMappedCell(cell->center(), det, point))
Additional Information:
The image of the mapping applied to cell with center [-5.89141 -7.3502 -8.36609] is distorted. The cell geometry or the mapping are invalid, giving a non-positive volume fraction of -0.0760174 in quadrature point 8.
```

There is nothing fancy in the test, only `GridGenerator::hyper_ball` and `SphericalManifold`. I know nothing about the manifold part of the library, so i would appreciate if someone could have a look.

@luca-heltai ping.
[step-1.cc.zip](https://github.com/dealii/dealii/files/501109/step-1.cc.zip)

### PR DESCRIPTION
**Pull request by luca-heltai**
Apparently I was too zealous in trying to make everything radius independent...

The bug is apparent only when R>>1 and center != Point<dim>(), otherwise everything looked fine "with the norm of the eye"...

All manifold tests pass. I'm running all grid tests now.

### CODE REVIEW

**Comment by luca-heltai** [comment]
~~~
The following tests FAILED:
	355 - grid/torus_01.debug (Failed)
	356 - grid/torus_01.release (Failed)
Errors while running CTest
~~~
This seems unrelated.

File: tests/manifold/spherical_manifold_04.cc [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+#include <iostream>
+#include <fstream>
+#include <sstream>
+
+using namespace dealii;
+
+void test (const double R)
+{
+  const unsigned int dim = 3;
+  const unsigned int global_mesh_refinement_steps = 1;
```
Comment (davydden) [inline tests/manifold/spherical_manifold_04.cc]: if you do `4` here and ....

File: tests/manifold/spherical_manifold_04.output [hunk 2]
```diff
@@ -0,0 +1,3 @@
+
+DEAL::Volume:       14109.1
```
Comment (davydden) [inline tests/manifold/spherical_manifold_04.output]: .. you will have `14137.2` here, which looks better as a test.

Comment (luca-heltai) [inline tests/manifold/spherical_manifold_04.output]: It is also a test that takes unnecessarily long to run... ;) I know it's better with 4, but if the bug was already caught with 1, why bother in making it run longer?

With `1`:
~~~
Test project /usr/local/src/d2-parallel-package/dealii/build
    Start 502: manifold/spherical_manifold_04.debug
1/2 Test #502: manifold/spherical_manifold_04.debug .....   Passed    4.95 sec
    Start 503: manifold/spherical_manifold_04.release
2/2 Test #503: manifold/spherical_manifold_04.release ...   Passed    4.93 sec
~~~
with `4`:
~~~
Test project /usr/local/src/d2-parallel-package/dealii/build
    Start 502: manifold/spherical_manifold_04.debug
1/2 Test #502: manifold/spherical_manifold_04.debug .....***Failed   15.19 sec
    Start 503: manifold/spherical_manifold_04.release
2/2 Test #503: manifold/spherical_manifold_04.release ...***Failed    11.09 sec
~~~

Comment (luca-heltai) [inline tests/manifold/spherical_manifold_04.output]: As you prefer. If you want to see a better convergence, I can put a `4`...

:)

Comment (davydden) [inline tests/manifold/spherical_manifold_04.output]: later on when everyone will forget what this test actually check, it will look strange that it tests volume calculation but numerical results are significatly different than analytical. You can quickly test whether you will get exactly the same number with the current precision with `3` refinement steps. Otherwise i would prefer to have a blessed output where the two numbers are the same.

Comment (luca-heltai) [inline tests/manifold/spherical_manifold_04.output]: Ok. I put a 4 there.

**Comment by kronbichler** [comment]
I agree that it's nice to have agreement between the numerical value and the analytical one.
