### PR TITLE
Avoid using a deprecated SLEPc function.

### LINKED ISSUE #4089: Slepc 3.6.3 compatibility
With slepc-3.6.3 + petsc-3.6.4 freshly installed with candi I get the following:

~~~
/usr/tmp/heltai/dealii/build/lib/libdeal_II.g.so.8.5.0-pre: error: undefined reference to 'EPSComputeResidualNorm'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
~~~

anyone else?

The documentation of slepc seems to refer to a different interface. Apparently they maintained the definition but not the implementation...

### PR DESCRIPTION
**Pull request by drwells**
EPSComputeResidualNorm and EPSComputeRelativeError were both deprecated in the 3.6 release in favor of EPSComputeError.

This should fix #4089; everything already works on my machine, but we should not get weird link errors (which may be a result of how SLEPc defines the deprecated functions as `static inline` for C compatibility) if we avoid deprecated functions.

### CODE REVIEW

**Comment by bangerth** [comment]
Not sure whether the tester even has SLEPc, but let's ask Clemson to pay the 20 cents or so in electricity and cooling to try the tests anyway.

OK to merge once the tester is happy.

File: source/lac/slepc_solver.cc [hunk 1]
```diff
@@ -195,22 +195,17 @@ namespace SLEPcWrappers
       for (unsigned int i = 0; i < *n_converged; i++)
         {
           double residual_norm_i = 0.0;
-          // EPSComputeResidualNorm is L2-norm and is not consistent with the stopping criteria
-          // used during the solution process.
-          // Yet, this is the norm which gives error bounds (Saad, 1992, ch3):
-          //   | \lambda - \widehat\lambda | <= ||r||_2
-          ierr = EPSComputeResidualNorm (eps, i, &residual_norm_i);
-
-          // EPSComputeRelativeError may not be consistent with the stopping criteria
```
Comment (davydden) [inline source/lac/slepc_solver.cc]: i would keep those comments in case someone later will have a question why we chose the function below.

Comment (drwells) [reply source/lac/slepc_solver.cc]: Fair point. I'll go back and add these in (they do need a slight rewrite since EPSComputeRelativeError is deprecated).

**Comment by drwells** [comment]
@davydden I added the comments back in.

While we are here. I don't understand the last comment regarding `EPSSetTrueResidual`. The SLEPc documentation claims that this function forces all methods to use the full residual calculation instead of shortcuts; however, this comment states otherwise. Is this a reference to a SLEPc bug?

File: source/lac/slepc_solver.cc [hunk 2]
```diff
@@ -195,22 +195,23 @@ namespace SLEPcWrappers
...
-          // used during the solution process. Given EPS_CONV_ABS set above,
-          // this can be either the l2 norm or the mass-matrix induced norm
-          // when EPS_GHEP is set.
-          // ierr = EPSComputeRelativeError (solver_data->eps, i, &residual_norm_i);
-
-          // EPSGetErrorEstimate is consistent with the residual norm
-          // used during the solution process. However, it is not guaranteed to
-          // be derived from the residual even when EPSSetTrueResidual is set.
-          // ierr = EPSGetErrorEstimate (solver_data->eps, i, &residual_norm_i);
+          // EPSComputeError (or, in older versions of SLEPc,
```
Comment (davydden) [inline source/lac/slepc_solver.cc]: Have a look at this thread https://lists.mcs.anl.gov/pipermail/petsc-users/2014-November/023509.html

`EPSComputeResidualNorm` always use L2 norm but it's not necessarily what SLEPC checks internally. 
`EPSComputeRelativeError` is L2 for non-symm and mass-matrix induced norm for GHEP. 
From that thread it seems `EPSSetTrueResidual` is not implemented in all solvers, so you kind of never know.

p.s. I must admit I have not used SLEPc for a while

Comment (drwells) [reply source/lac/slepc_solver.cc]: @davydden good point. I updated the comments to include a link to that thread so our choices in the code are clear :+1:

File: source/lac/slepc_solver.cc [hunk 3]
```diff
@@ -195,22 +195,28 @@ namespace SLEPcWrappers
...
+          // EPSComputeRelativeError) uses an L2-norm and is not consistent
+          // with the stopping criterion used during the solution process (see
+          // the SLEPC manual, section 2.5). Since EPS_CONV_ABS is set above,
```
Comment (davydden) [inline source/lac/slepc_solver.cc]: "Since" sentence previously applied to EPSComputeRelativeError, i don't think it holds for `EPSComputeError`

File: source/lac/slepc_solver.cc [hunk 4]
```diff
@@ -195,22 +195,28 @@ namespace SLEPcWrappers
...
+          // it is not guaranteed to be derived from the residual even when
+          // EPSSetTrueResidual is set: see the discussion in the thread
+          //
+          // https://lists.mcs.anl.gov/pipermail/petsc-users/2014-November/023509.html
+          //
+          // for more information.
+#if DEAL_II_SLEPC_VERSION_GTE(3, 6, 0)
+          ierr = EPSComputeError(eps, i, EPS_ERROR_ABSOLUTE, &residual_norm_i);
+#else
+          ierr = EPSComputeRelativeError(eps, i, &residual_norm_i);
```
Comment (davydden) [inline source/lac/slepc_solver.cc]: also you need an entry incompatibility section as previously we used `EPSComputeResidualNorm`

Comment (drwells) [reply source/lac/slepc_solver.cc]: Thats actually a mistake on my part; I meant to use EPSComputeResidualNorm here.

**Comment by drwells** [comment]
@davydden Not a problem; I'd rather get things correct now then leave it until the next time we look at SLEPc.

I have another question: we do
```cpp
EPSSetConvergenceTest(eps, EPS_CONV_ABS);
```

which (according to the documentation) will use the residual for the convergence test. However, the comments below (in the current version) state that `EPSComputeResidualNorm` is not consistent with the stopping criteria: is this incompatible just because of the approximation of the residual, or is there something else?

**Comment by davydden** [comment]
> EPSComputeResidualNorm is not consistent with the stopping criteria

i think it's because the solver together with spectral transformation can check something completely different. Say if you shift-and-invert, you potential check residual of the original problem or of the transformed problem.

**Comment by davydden** [comment]
p.s. I don't know all the details about SLEPc and what is actually being tested for what case. Not to mention that sometimes things are tested with mass-matrix induced norm (if it's SPD) and sometimes not.

**Comment by drwells** [comment]
Good point; the documentation is a bit ambiguous but the deflation methods are most likely doing exactly that.

**Comment by drwells** [comment]
I think I fixed everything.
