### PR TITLE
Shifted matrix bugs

### LINKED ISSUE #1990: ShiftedMatrixGeneralized::vmult, ::residual do not work
Please, look here at implementation of vmult and residual in ShiftedMatrixGeneralized:
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/shifted_matrix.h#L242

There are two problems:

1) these functions are declared as const, but they try to modify aux vector in the object.
This can be solved by declaring VECTOR aux just before lines 251, 268. (and removing the declaration in the line 150.)

2) SmartPointer M should be called as M->, not M. in lines 252, 269.

### PR DESCRIPTION
**Pull request by drwells**
This should close #1990.

Amazingly (and this is documented in the commit messages) this class has been impossible to compile since it appeared in 2001.

### CODE REVIEW

File: tests/lac/shifted_matrix_generalized_01.cc [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+  m1(0, 1) = 1.0;
+  m1(1, 0) = 1.0;
+  m1(1, 1) = 2.0;
+
+  m2(0, 0) = 1.0;
+  m2(0, 1) = 1.0;
+  m2(1, 0) = 1.0;
+  m2(1, 1) = 1.0;
+
+  ShiftedMatrixGeneralized<FullMatrix<double>, FullMatrix<double>, Vector<double>>
```
Comment (asartori86) [inline tests/lac/shifted_matrix_generalized_01.cc]: just a silly comment :) should be added a space between the two  `>>` at the end?

Comment (drwells) [inline tests/lac/shifted_matrix_generalized_01.cc]: That is not a silly comment. I keep inadvertantly adding `C++11`isms where I should not. Thanks for catching this!

File: include/deal.II/lac/shifted_matrix.h [hunk 2]
```diff
@@ -213,51 +213,51 @@ ShiftedMatrix<MatrixType>::residual (VectorType       &dst,
...
+ShiftedMatrixGeneralized<MatrixType, MatrixType2, VectorType>::vmult
 (VectorType       &dst,
  const VectorType &src) const
 {
   A->vmult(dst, src);
   if (sigma != 0.)
     {
-      aux.reinit(dst);
-      M.vmult(aux, src);
+      aux.reinit(dst.size());
```
Comment (kronbichler) [inline include/deal.II/lac/shifted_matrix.h]: A reason why you change the initialization this way? This will limit the class do serial vectors that can be initialized by size. The generic way is to call reinit on an exemplar (dst in this case).

**Comment by drwells** [comment]
@kronbichler I do not know why but for some reason, when I wrote this, I thought that that particular `reinit` function was not implemented for `Vector`. I fixed it.

**Comment by bangerth** [comment]
@drwells , would you be willing to push another patch with a change log entry? Merge is pre-approved.
