### PR TITLE
Reduce size of test (multigrid/transfer_matrix_free_06)

### LINKED ISSUE #11726: Fix test multigrid/transfer_matrix_free_06.mpirun=15.debug
The test `multigrid/transfer_matrix_free_06.mpirun=15.debug` keeps on timeouting for some time now:
```
The following tests FAILED:
	3320 - multigrid/transfer_matrix_free_06.mpirun=15.debug (Timeout)
```

### PR DESCRIPTION
**Pull request by peterrum**
Closes #11726.

### CODE REVIEW

File: tests/multigrid/transfer_matrix_free_06.cc [hunk 1]
```diff
@@ -43,7 +43,7 @@ check(const unsigned int fe_degree)
   deallog << "FE: " << fe.get_name() << std::endl;
 
   // run a few different sizes...
-  unsigned int sizes[] = {1, 3};
+  unsigned int sizes[] = {1, 2};
```
Comment (kronbichler) [inline tests/multigrid/transfer_matrix_free_06.cc:46]: Could you please also change line 59 to `if (degree == 1)`? We have some higher degrees already, I do not think we need more mesh elements.

**Review by kronbichler — APPROVED** [review]

**Comment by peterrum** [comment]
Let's hope this resolves the time-out issue!
