### PR TITLE
Fix Trilinos SparsityPattern iterators.

### LINKED ISSUE #3541: Static analysis: include/deal.II/lac/trilinos_sparsity_pattern.h

### LINKED ISSUE #3586: Fix TrilinosWrappers::SparsityPattern::const_iterator
The `TrilinosWrappers::SparsityPattern::const_iterator` class segfaults upon construction. This is not surprising because it calls this function:
```
    void
    Accessor::visit_present_row ()
    {
      // if we are asked to visit the
      // past-the-end line, then simply
      // release all our caches and go on
      // with life
      if (this->a_row == sparsity_pattern->n_rows())
        {
          colnum_cache.reset ();

          return;
        }
//TODO: Is this thread safe?

      // otherwise first flush Trilinos caches
      sparsity_pattern->compress ();

      // get a representation of the present
      // row
      int ncols;
      // TODO: casting a size_type to an int, could be a problem
      int colnums = sparsity_pattern->n_cols();

      int ierr;
      ierr = sparsity_pattern->graph->ExtractGlobalRowCopy((TrilinosWrappers::types::int_type)this->a_row,
                                                           colnums,
                                                           ncols,
                                                           (TrilinosWrappers::types::int_type *)&(*colnum_cache)[0]);
      AssertThrow (ierr == 0, ExcTrilinosError(ierr));

      // copy it into our caches if the
      // line isn't empty. if it is, then
      // we've done something wrong, since
      // we shouldn't have initialized an
      // iterator for an empty line (what
      // would it point to?)
      Assert (ncols != 0, ExcInternalError());
      colnum_cache.reset (new std::vector<size_type> (colnums,
                                                      colnums+ncols));
    }
```
I don't even know where to start with this. Clearly, for `ExtractGlobalRowCopy` to work, it needs to be provided with a sufficiently large vector, which isn't happening here. I'm also completely mystified what exactly the constructor call in the last statement is doing.

This ought to be fixed.

### PR DESCRIPTION
**Pull request by bangerth**
These iterators were previously completely dysfunctional: one could not even create
an iterator without getting a segfault. This is now fixed by fixing the 
Accessor::visit_present_row class. I've also added testst that check the
slightly complicated internal memory management of this class.

While there, also remove the copy constructor of the Accessor class: It is the
default copy constructor, and by removing it, we also don't have to worry
about there being no copy operator.

Fixes #3586. Also fixes #3541. Supersedes #3583.

### CODE REVIEW

File: source/lac/trilinos_sparsity_pattern.cc [hunk 1]
```diff
@@ -114,43 +114,35 @@ namespace TrilinosWrappers
...
-      // copy it into our caches if the
-      // line isn't empty. if it is, then
-      // we've done something wrong, since
-      // we shouldn't have initialized an
-      // iterator for an empty line (what
-      // would it point to?)
-      Assert (ncols != 0, ExcInternalError());
-      colnum_cache.reset (new std::vector<size_type> (colnums,
-                                                      colnums+ncols));
+      colnum_cache.reset (new std::vector<size_type> (sparsity_pattern->row_length(this->a_row)));
```
Comment (drwells) [inline source/lac/trilinos_sparsity_pattern.cc]: I did not think of doing this for the PETSc wrappers but perhaps we can avoid allocations here. Is there a reason that we cannot do something like

```cpp
colnum_cache->resize(sparsity_pattern->row_length(this->a_row));
```

instead?

Comment (bangerth) [inline source/lac/trilinos_sparsity_pattern.cc]: There is a comment in the class that says that we want to make copying of accessors cheap. Consequently, this cache is administered as a `shared_ptr`. If you just resize things, then other iterators/accessors that were copied from the current one before moving to a new row, will become outdated.

The `_02` test I added checks for exactly this.

I think one could debate whether copying iterators is a case that needs to be supported in a particularly efficient way. That says, the class currently supports it, and I'm not particularly worried about applications that walk over the elements of a sparsity pattern -- that's mostly for debugging, so I didn't bother with trying to improve efficiency over what it currently is. My interest was mostly in just making it work.

Comment (drwells) [inline source/lac/trilinos_sparsity_pattern.cc]: Fair enough. I thought about this some more and I am not sure how to do it in a thread safe way so we should keep things like this.
