### PR TITLE
Fix vertex orientations in torus mesh

### LINKED ISSUE #16272: Distributed triangulation: assertion when distributing DoFs
Hello,

I have a problem with a parallel distributed triangulation that occurs in a 3d scenario when using at least three levels of refinements and at least 4 MPI processes when distributing the degrees of freedom.
The problem is dependent on the mesh and it occurs when using the [torus mesh](https://www.dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#a7e99c2ee8ac3332b50baa028b7ded526) of the GridGenerator class.
I tested this on dealii 9.5.1 and todays master branch. Here is a minimal working example:
[distributing_crash.zip](https://github.com/dealii/dealii/files/13382299/distributing_crash.zip)

If I run it with at least -np4 I get the following assertion:

````
$ mpirun -np 4 ./distributing_crash
Running on 4 MPI rank(s)...
Number of locally owned active cells: 3840
Number of globally active cells:      15360
Distributing dofs... 

--------------------------------------------------------
An error occurred in line <3556> of file <~/Downloads/dealii_dev/source/dofs/dof_handler_policy.cc> in function
    dealii::internal::DoFHandlerImplementation::Policy::{anonymous}::communicate_dof_indices_on_marked_cells<3, 3>(const dealii::DoFHandler<3, 3>&, std::vector<bool>&)::<lambda(const auto:118&, const auto:119&)>::<lambda(auto:120&, auto:121)> [with auto:120 = unsigned int; auto:121 = unsigned int*]
The violated condition was: 
    (stored_index == invalid_dof_index) || (stored_index == *received_index)
Additional information: 
    This exception -- which is used in many places in the library --
    usually indicates that some condition which the author of the code
    thought must be satisfied at a certain point in an algorithm, is not
    fulfilled. An example would be that the first part of an algorithm
    sorts elements of an array in ascending order, and a second part of
    the algorithm later encounters an element that is not larger than the
    previous one.
    
    There is usually not very much you can do if you encounter such an
    exception since it indicates an error in deal.II, not in your own
    program. Try to come up with the smallest possible program that still
    demonstrates the error and contact the deal.II mailing lists with it
    to obtain help.

Stacktrace:
-----------
#0  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#1  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#2  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#3  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#4  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#5  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#6  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: std::function<void (dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)>::operator()(dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&) const
#7  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: void dealii::GridTools::internal::exchange_cell_data<std::vector<unsigned int, std::allocator<unsigned int> >, dealii::DoFHandler<3, 3>, dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > >(dealii::DoFHandler<3, 3> const&, std::function<std::optional<std::vector<unsigned int, std::allocator<unsigned int> > > (dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&)> const&, std::function<void (dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)> const&, std::function<bool (dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&)> const&, std::function<void (std::function<void (dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > const&, unsigned int)> const&)> const&, std::function<std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > (dealii::parallel::TriangulationBase<dealii::DoFHandler<3, 3>::dimension, dealii::DoFHandler<3, 3>::space_dimension> const&)> const&)
#8  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: void dealii::GridTools::exchange_cell_data_to_ghosts<std::vector<unsigned int, std::allocator<unsigned int> >, dealii::DoFHandler<3, 3> >(dealii::DoFHandler<3, 3> const&, std::function<std::optional<std::vector<unsigned int, std::allocator<unsigned int> > > (dealii::DoFHandler<3, 3>::active_cell_iterator const&)> const&, std::function<void (dealii::DoFHandler<3, 3>::active_cell_iterator const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)> const&, std::function<bool (dealii::DoFHandler<3, 3>::active_cell_iterator const&)> const&)
#9  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: 
#10  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: dealii::internal::DoFHandlerImplementation::Policy::ParallelDistributed<3, 3>::distribute_dofs() const
#11  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: dealii::DoFHandler<3, 3>::distribute_dofs(dealii::hp::FECollection<3, 3> const&)
#12  ~/Downloads/dealii_dev/build/lib/libdeal_II.g.so.9.6.0-pre: dealii::DoFHandler<3, 3>::distribute_dofs(dealii::FiniteElement<3, 3> const&)
#13  ./distributing_crash: Problem_DGP::Demonstration<3>::run()
#14  ./distributing_crash: main

Calling MPI_Abort now.
To break execution in a GDB session, execute 'break MPI_Abort' before running. You can also put the following into your ~/.gdbinit:
  set breakpoint pending on
  break MPI_Abort
  set breakpoint pending auto

````

I attached a debugger and looked at some variables when the assertion is thrown (it is thrown on proc0):

````
stored_index = 77463
*received_index = 143823
invalid_dof_index = 4294967295

cell->index() = 4461

cell->center(false, false) = {2.1532106405941569, -0.3266047428319967, 1.0183927880754229}
````

The minimal working example runs fine in release mode - nevertheless in my production code the program crashes later on when creating the sparsity pattern - and I think this is a consequence of a problem when distributing the DoFs:

````
TimerOutput objects finalize timed values printed to the
screen by communicating over MPI in their destructors.
Since an exception is currently uncaught, this
synchronization (and subsequent output) will be skipped
to avoid a possible deadlock.
---------------------------------------------------------

********************************************************************************

An EXCEPTION occured: Please READ the following output CAREFULLY!

--------------------------------------------------------
An error occurred in line <1294> of file <~/Downloads/dealii_dev/include/deal.II/lac/trilinos_sparsity_pattern.h> in function
    void dealii::TrilinosWrappers::SparsityPattern::add_entries(size_type, ForwardIterator, ForwardIterator, bool) [with ForwardIterator = const unsigned int*; size_type = unsigned int]
The violated condition was:
    ierr >= 0
Additional information:
    An error with error number -2 occurred while calling a Trilinos
    function

Stacktrace:
-----------
#0  ~/Downloads/dealii_dev/build/lib/libdeal_II.so.9.6.0-pre:
#1  ~/Downloads/dealii_dev/build/lib/libdeal_II.so.9.6.0-pre: dealii::AffineConstraints<double>::add_entries_local_to_global(std::vector<unsigned int, std::allocator<unsigned int> > const&, dealii::AffineConstraints<double> const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, dealii::SparsityPatternBase&, bool, dealii::Table<2, bool> const&) const
#2  ~/Downloads/dealii_dev/build/lib/libdeal_II.so.9.6.0-pre: dealii::AffineConstraints<double>::add_entries_local_to_global(std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, dealii::SparsityPatternBase&, bool, dealii::Table<2, bool> const&) const
#3  ~/Downloads/dealii_dev/build/lib/libdeal_II.so.9.6.0-pre: void dealii::DoFTools::make_flux_sparsity_pattern<3, 3, double>(dealii::DoFHandler<3, 3> const&, dealii::SparsityPatternBase&, dealii::AffineConstraints<double> const&, bool, unsigned int)
--------------------------------------------------------

APPLICATION TERMINATED unexpectedly due to an exception.
````

Other problems with other meshes (e.g. [channel with cylinder](https://www.dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#a9d0b8a34fe5ca58425aa1fcf0d6132f1)) run fine - even with finer meshes on more processes. It is just that I need a torus-like mesh now.

Maybe anybody has an idea what is going wrong here or can help me with this?
Greetings
Mathias

### PR DESCRIPTION
**Pull request by kronbichler**
This fixes #16272 - I think the basic test case by @peterrum is enough if we look at the mesh statistics (also for p4est versions that do not include the assertion, I see that p4est 2.8 would throw).

Note that I had to adjust one test case where the order of vertices in the torus would matter.

### CODE REVIEW

File: tests/distributed_grids/create_torus_mesh.cc [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+// version 2.1 of the License, or (at your option) any later version.
+// The full text of the license can be found in the file LICENSE.md at
+// the top level directory of deal.II.
+//
+// ---------------------------------------------------------------------
+
+
+
+// Test GridGenerator::torus, which used to run into an assertion with p4est
+// due to bad orientations before 2023
```
Comment (peterrum) [inline tests/distributed_grids/create_torus_mesh.cc:19]: Could you add the issue number?

**Review by peterrum — APPROVED** [review]

**Review by peterrum — APPROVED** [review]
Thanks!
