### PR TITLE
Recreate changes.h automatically

### LINKED ISSUE #3154: Better scheme than changes.h
We keep running into the issue that proposed patches have to be rebased to fix the merge conflict on `changes.h`. This issue isn't going to go away as we seem to get more patches over time.

I'd like to discuss better ways to do this. My preferred approach is to have a directory `doc/news/changes/` into which patch authors simply put a file that corresponds to individual changelog entries. A script would then combine this into the `changes.h` file we send to doxygen. If we adopt the convention that these files start with `YYYY-MM-DD-...`, but are otherwise arbitrary, then we can combine them in a way that preserves the temporal order of the changelog, and would avoid all but the most unlikely merge conflicts.

Other suggestions that have been made over time include special comments in commit messages. I don't particularly like this because it's hard to auto-generate a `changes.h` file from that. It's also really difficult to deal with if someone accidentally gets the format wrong -- you can't fix it up after the fact.

Thoughts?

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #3154.
This is a suggestion on how to deal with the annoying merge conflicts in `changes.h`.
It seems that we more or less agreed to have subdirectories. This is what this PR does.

The script converting the old `changes.h` into the new one uses that there is a line like
`(name_1, ...., name_n, YYYY/MM/DD)` at the last line of each of the entries, but there is basically no requirement for new items.

### CODE REVIEW

**Comment by bangerth** [comment]
Something like this is what I had in mind. It requires `bash`, though. Once we're happy with the functionality, we may want to convert the scripts to cmake so that it can be run platform independently.

I'm traveling, so I will let others comment on the specifics of the patch.

File: doc/news/create_changes_h.sh [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+
+if test ! -d incompatibilities -o ! -d general -o ! -d specific ; then
+  echo "*** This script must be run from ./doc/news!"
+  exit 1
+fi
+
+echo INCOMPATIBILITIES
+cat header_incompatibilities > changes.h
+echo "<ol>" >> changes.h	
+ARRAY=($(ls incompatibilities | sort -r))
```
Comment (davydden) [inline doc/news/create_changes_h.sh]: i am not a bash-guru, maybe document the logic and variables throughout the script so that it is more clear for others.

File: doc/news/create_changes_h.sh [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+if ! [ -z "$ARRAY" ]; then
+  echo -n " <li>" >> changes.h
+  sed 's/^/ /' incompatibilities/${ARRAY[0]} >> changes.h
```
Comment (davydden) [inline doc/news/create_changes_h.sh]: why `for` loop is not enough? Does it only work with more than 1 elements?

File: doc/news/changes.h [hunk 3]
```diff
@@ -1,1314 +0,0 @@
...
-// it, and/or modify it under the terms of the GNU Lesser General
-// Public License as published by the Free Software Foundation; either
-// version 2.1 of the License, or (at your option) any later version.
-// The full text of the license can be found in the file LICENSE at
-// the top level of the deal.II distribution.
-//
-// ---------------------------------------------------------------------
-
-/**
-@page changes_after_8_4_2 Changes after Version 8.4.2
```
Comment (davydden) [inline doc/news/changes.h]: you delete whole lot of things, but there is no creating of the same amount of files for each entry. 
I would suggest to keep the `changes.h` untouched in THIS pr and make sure that the script creates exactly the same file (disregarding whitespace and alike). Once this is the case, one can delete the `changes.h` and add it to `.gitignore`.

File: doc/news/create_changes_h.sh (hunk 2 above)
Comment (davydden) [inline doc/news/create_changes_h.sh]: it is also not clear why do you need those `.dummy` files. Please document this in the script.

File: doc/news/header_incompatibilities [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+// The full text of the license can be found in the file LICENSE at
+// the top level of the deal.II distribution.
+//
+// ---------------------------------------------------------------------
+
+/**
+@page changes_after_8_4_2 Changes after Version 8.4.2
+
+<p>
+This is the list of changes made after the release of deal.II version
```
Comment (davydden) [inline doc/news/header_incompatibilities]: i would split it into `header_incompatabilities` and `header` (top part which has the actual header)

File: doc/news/split_changes_h.sh [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+## it, and/or modify it under the terms of the GNU Lesser General
+## Public License as published by the Free Software Foundation; either
+## version 2.1 of the License, or (at your option) any later version.
+## The full text of the license can be found in the file LICENSE at
+## the top level of the deal.II distribution.
+##
+## ---------------------------------------------------------------------
+
+#
+# This script splits the previously used into contributions in the folders:
```
Comment (davydden) [inline doc/news/split_changes_h.sh]: once we move to 1 file per each change, why would wee ned a script to split it again? I would not commit this file at all.

File: doc/news/split_summary.sh [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+## it, and/or modify it under the terms of the GNU Lesser General
+## Public License as published by the Free Software Foundation; either
+## version 2.1 of the License, or (at your option) any later version.
+## The full text of the license can be found in the file LICENSE at
+## the top level of the deal.II distribution.
+##
+## ---------------------------------------------------------------------
+
+#
+# This script is used in ./split_changes_h.sh to split entries
```
Comment (davydden) [inline doc/news/split_summary.sh]: same here.

**Comment by davydden** [comment]
please add a `README` which documents categories

@Bangerth:

> I was thinking of putting a README file into doc/news/changes/ that explains the format of these files and of file names.

and 

> As for the categories, I always thought of "major" (which is actually "general changes") as something that affects more than one function or class, or that has to do with tutorials, or that has to do with infrastructure such as the build system. Other suggestions welcome.

or we can go with @tjhei 's suggestion

> While we are at it, we should talk about the three sections "major", "minor", and "incompatibilities". I never know the difference between the two former. 

I am in favour of the latter option.

Here's also what @kronbichler says

> Among those software packages where I like reading the release notes, the "major" changes are something more substantial than just adding another variant of a function, rather something to get "excited" about (and a list that is sufficiently compact).

File: doc/news/create_changes_h.sh (hunk 2 above)
Comment (masterleinad) [inline doc/news/create_changes_h.sh]: The only reason for these `.dummy` files is, that git doesn't allow me to create empty directories.

Comment (davydden) [inline doc/news/create_changes_h.sh]: they won't be empty, right? After you split the current file into small files, there will always be something in each category.

File: doc/news/split_changes_h.sh (hunk 5 above)
Comment (masterleinad) [inline doc/news/split_changes_h.sh]: Sure, in the end this file can go. It's just convenient to have `split_changes_h.sh` (and `split_summary.sh` here) until we really do the change.

Comment (davydden) [inline doc/news/split_changes_h.sh]: still, i would not commit it. I just don't see a reason why should it be a part of the Git history.  I would just split the current `changes.h` (without deleting it!) into lots of smaller once using these scripts and make sure that re-running generation does not show any missing entries.

File: doc/news/create_changes_h.sh (hunk 2 above)
Comment (davydden) [inline doc/news/create_changes_h.sh]: but why do you need it? Just add empty line within this script before the for loop or within it at the end. Even if the category is empty, a single empty line in resulting `changes.h` won't damage anything.

Comment (davydden) [inline doc/news/create_changes_h.sh]: put it another way, currently you add twice as much code to maintain, whereas I think you can cut it down easily.

File: doc/news/split_changes_h.sh (hunk 5 above)
Comment (masterleinad) [inline doc/news/split_changes_h.sh]: Once this is `ready to merge` I'll remove these two files and add all the output from them.
Recreating `changes.h` already works.

File: doc/news/changes/README.md [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+
+Each of these files contain a short description of a change, the authors' names
+and the date where the latter two a separated by "<br>" from the first one. 
+A typical file could look like this:
+
+    New: We can do fancy stuff now.
+    <br>
+    (John Doe, YYYY/MM/DD)
+
+and is named "YYYYMMDDJohnDoe". File names for multiple contributions from the
```
Comment (davydden) [inline doc/news/changes/README.md]: what if it's `JohnDoeRobertWhite...`? I think it's better to state explicitly what is actually required by the script, and what is a convenience. I suppose the only thing you really need is `YYYYMMDD` to order changes and make sure they are not conflicting. In other words,
`YYYYMMDD_this` and `YYYYMMDD_that` will also work? If not, i think the bash script should be modified. That is because all the proper authorship is already within the file
```
(John Doe, YYYY/MM/DD)
```
so how files are named shall not be important as long as you can get the date.

File: doc/news/changes/README.md [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+The "incompatibilities" section contains modifications to the library that 
+are incompatible with previous versions of the library, but which are
+necessary for the future maintainability of the library. 
+
+major
+-----
+
+Entries in the "major" section are reserved for substantial changes to the
+library. In particular, this should be sufficiently compact. A good example
+for this category would be adding a new tutorial program.
```
Comment (davydden) [inline doc/news/changes/README.md]: `or a new FE class`.

File: doc/news/changes/create_changes_h.sh [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+OUTPUT="../changes.h.new"
+
+function process_directory
+{
+  echo "<ol>" >> ${OUTPUT}
+  # process all entries in the right order
+  ARRAY=($(ls "$1" | sort -r))
+  if ! [ -z "${ARRAY[0]}" ]; then
+    # treat the first item special
+    # we don't want to insert a new line here
```
Comment (davydden) [inline doc/news/changes/create_changes_h.sh]: the question remains, why 

> we don't want to insert a new line here

?

I am still in favour of removing that special treatment of the first element.

File: doc/news/changes/create_changes_h.sh [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+  exit 1
+fi
+
+OUTPUT="../changes.h.new"
+
+function process_directory
+{
+  echo "<ol>" >> ${OUTPUT}
+  # process all entries in the right order
+  ARRAY=($(ls "$1" | sort -r))
```
Comment (davydden) [inline doc/news/changes/create_changes_h.sh]: so that's all you need from file names: to be sortable according to the date.

File: doc/news/changes/README.md [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+
+minor
+-----
+
+Finally, the "minor" section contains all the changes that do not fit in
+the former two.
```
Comment (davydden) [inline doc/news/changes/README.md]: please give some examples.

File: doc/news/changes/create_changes_h.sh (hunk 9 above)
Comment (davydden) [inline doc/news/changes/create_changes_h.sh]: To make myself clear, there will be nothing wrong with `.html` if it looks like
```
<ol>

 <li>
   ....
 </li>

 <li>
   ....
 </li>
</ol>
```
It will make zero difference in visualisation and the way the page is displayed.

If you don't want to have a new line infront, add it at the end of each entry:
```
<ol>
 <li>
   ....
 </li>

 <li>
   ....
 </li>

</ol>
```

File: doc/news/changes/README.md (hunk 7 above)
Comment (masterleinad) [inline doc/news/changes/README.md]: Yes, both `YYYYMMDD_this` and `YYYYMMDD_that` will also work. We use the file name only for sorting.

**Comment by bangerth** [comment]
I've created a pull request against this pull request (see https://github.com/masterleinad/dealii/pull/7) that makes sure that `changes.h` is created automatically as an input for the doxygen run that consumes this file and converts it into HTML.

@tamiko -- here's a question for you. `changes.h` depends on all of the changelog fragments people have put into `doc/news/changes/*` subdirectories. I see two options:

* I can list them as explicit dependencies. This has the downside that because the dependencies are created during cmake run time, just putting a new file into a subdirectory does not trigger re-creation of `changes.h` and consequently no re-run of doxygen. This really only works if (i) `changes.h` does not yet exist, or (ii) we run cmake anyway, e.g., because the git commit hash has changed.

* I can make the target `PHONY`, by using `ADD_CUSTOM_TARGET` instead of `ADD_CUSTOM_COMMAND` to create `changes.h`. This would simply *always* re-create `changes.h`, but consequently also always trigger re-running doxygen (*very expensive*, takes several minutes) even if `changes.h` did not actually change. (I.e., it was recreated but yielded the same file, just with a different time stamp.)

My preference would be a variation of the second option, but modified in a way so that the time stamp of `changes.h` only changes if the file content in fact changed. How would one do such a thing?

File: doc/news/changes/create_changes_h.sh [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+  for f in "${ARRAY[@]}"; do
+    echo "" >> ${OUTPUT}
+    echo -n " <li>" >> ${OUTPUT}
+    # indent lines by one blank space
+    sed 's/^[ ]*/ /' "$1"/"$f" >> ${OUTPUT}
```
Comment (tjhei) [inline doc/news/changes/create_changes_h.sh]: this needs to be tested on MAC, because their default ``sed`` behaves differently.

Comment (bangerth) [inline doc/news/changes/create_changes_h.sh]: I would like to re-generate this script in cmake after this patch is merged (and the issue about when the file is re-generated is resolved). So this issue may just disappear.

**Comment by bangerth** [comment]
@tamiko ?

**Comment by jppelteret** [comment]
Thanks @masterleinad for taking the time to work out a solution to this. I'll be great to have this pain point removed from the development process!

**Comment by masterleinad** [comment]
@bangerth According to http://stackoverflow.com/questions/15282444/using-cmake-how-can-i-concat-files-and-install-them/15283110#15283110 using CONFIGURE_FILE does exactly what you were asking for.

**Comment by masterleinad** [comment]
From my point of view this should be ready:
- We create a temporary file `changes.h.in` in the source directory from the contributions in `./doc/news/changes/*`. This file is copied to `changes.h` in the build directory if the file changed.
- The documentation for the changes uses both the `*.h` files in `./doc/news/` in the source directory and `changes.h` in the build directory.
- When installing we copy both the `*.h` files in `./doc/news/` in the source directory for changes between older versions and `changes.h` in the build directory. We don't copy the individual contributions in `./doc/news/changes/*` to the install directory.
- All this doesn't use any bash script but just CMake instructions

File: doc/news/changes/README.md [hunk 13]
```diff
@@ -0,0 +1,45 @@
...
+
+The "incompatibilities" section contains modifications to the library that 
+are incompatible with previous versions of the library, but which are
+necessary for the future maintainability of the library.
+
+major
+-----
+
+Entries in the "major" section are reserved for substantial changes to the
+library. In particular, this should be sufficiently compact. A good example
```
Comment (jppelteret) [inline doc/news/changes/README.md]: Can I ask, what do you mean by the phrase "In particular, this should be sufficiently compact"?

Comment (masterleinad) [inline doc/news/changes/README.md]: https://github.com/dealii/dealii/issues/3154#issuecomment-249258766:
> Among those software packages where I like reading the release notes, the "major" changes are something more substantial than just adding another variant of a function, rather something to get "excited" about (and a list that is sufficiently compact).

**The list** should be sufficiently compact.

Comment (jppelteret) [inline doc/news/changes/README.md]: Ah, OK I understand now. Thanks for the clarification :-)

File: doc/CMakeLists.txt [hunk 14]
```diff
@@ -32,6 +33,14 @@ IF(DEAL_II_COMPONENT_DOCUMENTATION)
...
     PATTERN "doxygen" EXCLUDE
     PATTERN "*.in" EXCLUDE
+    PATTERN "news/changes.h" EXCLUDE
+    PATTERN "news/changes/*" EXCLUDE
+    )
+
+  INSTALL(FILES
+    ${CMAKE_CURRENT_BINARY_DIR}/news/changes.h
+    DESTINATION ${DEAL_II_DOCHTML_RELDIR}/news
+    COMPONENT documentation
```
Comment (bangerth) [inline doc/CMakeLists.txt]: This is not a priori wrong, but I wonder whether there's any purpose in it. These files are not really meant to be read by humans, but to be processed by doxygen. What are your thoughts?

File: doc/news/changes/create_changes_h.cmake [hunk 15]
```diff
@@ -0,0 +1,52 @@
...
+FILE(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "")
+CAT    (${CMAKE_CURRENT_SOURCE_DIR}/header                   ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "FALSE")
+CAT    (${CMAKE_CURRENT_SOURCE_DIR}/header_incompatibilities ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "FALSE")
+PROCESS(${CMAKE_CURRENT_SOURCE_DIR}/incompatibilities        ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in)
+CAT    (${CMAKE_CURRENT_SOURCE_DIR}/header_major             ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "FALSE")
+PROCESS(${CMAKE_CURRENT_SOURCE_DIR}/major                    ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in)
+CAT    (${CMAKE_CURRENT_SOURCE_DIR}/header_minor             ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "FALSE")
+PROCESS(${CMAKE_CURRENT_SOURCE_DIR}/minor                    ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in)
+CAT    (${CMAKE_CURRENT_SOURCE_DIR}/footer                   ${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in "FALSE")
+CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/changes.h.in ${OUTPUT_FILE} COPYONLY)
```
Comment (bangerth) [inline doc/news/changes/create_changes_h.cmake]: Ah, yes, clever. Nice use of `CONFIGURE_FILE`!

Can you offset the last line and add a comment of the form "In the previous line, we created a file 'changes.h.in' based on all changelog fragments. Copy it over to 'changes.h' but only touch the time stamp if the file actually changed (this is what CONFIGURE_FILE does)."

File: doc/news/CMakeLists.txt [hunk 16]
```diff
@@ -0,0 +1,55 @@
...
+    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/changes
+    DEPENDS 
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/header
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/header_incompatibilities
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/header_major
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/header_minor
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/footer
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/major/*
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/minor/*
+      ${CMAKE_CURRENT_SOURCE_DIR}/changes/incompatibilities/*
```
Comment (bangerth) [inline doc/news/CMakeLists.txt]: Hm, I didn't think that `DEPENDS` can contain wildcards. Can you check whether `changes.h` is re-created if you change one of the changelog fragments?

File: doc/news/CMakeLists.txt [hunk 17]
```diff
@@ -0,0 +1,55 @@
...
+  MESSAGE(STATUS "")
+  MESSAGE(STATUS "Setting up changelog generation")
+
+  #
+  # Generate changes.h.
+  #
+  ADD_CUSTOM_COMMAND(
+    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/changes.h
+    COMMAND ${CMAKE_COMMAND} -DOUTPUT_FILE=${CMAKE_CURRENT_BINARY_DIR}/changes.h
+                             -P ${CMAKE_CURRENT_SOURCE_DIR}/changes/create_changes_h.cmake
```
Comment (bangerth) [inline doc/news/CMakeLists.txt]: Thinking about this again, I don't think this is quite right. You say that the output of this command is `changes.h`, but `changes.h` is really only updated if the fragments actually changed. I think it would be more correct if you said that the output is `changes.h.in`, and then moved the `CONFIGURE_FILE` call from the script you call here to after the current command.

(Makefiles are hard :-( )

File: doc/news/CMakeLists.txt (hunk 16 above)
Comment (masterleinad) [inline doc/news/CMakeLists.txt]: Yes, `changes.h.in` is re-created when I add or modify a file in `./doc/news/changes/major`.

Comment (bangerth) [inline doc/news/CMakeLists.txt]: Interesting! Thanks for checking.

File: doc/news/CMakeLists.txt (hunk 17 above)
Comment (masterleinad) [inline doc/news/CMakeLists.txt]: Hmm... If I use ` OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/changes/changes.h.in` instead of ` OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/changes.h` doxygen is not re-run automatically when there are changes in the subdirectories of `./doc/news/changes/*`.
Therefore, I would just leave the logic as is.

File: doc/CMakeLists.txt (hunk 14 above)
Comment (masterleinad) [inline doc/CMakeLists.txt]: The reasoning was to create the same files as we did before. Thinking about it, we probably don't need to copy any files in `./doc/news`. I agree that all the information is contained in the files generated by doxygen already.

**Comment by bangerth** [comment]
Let's just go with this. We can always improve it at a later point. So:
* Can you squash the last few commits where you convert the script to cmake and then modify things?
* Merge this PR
* Create a separate PR that breaks apart the existing `changes.h` that is current at the time when you do this; also delete the script again that you use to break apart the existing file. I hope that this finds a quick review from someone so it can get merged quickly and without creating merge conflicts.

We can then go from there and fix any fallout.
