### PR TITLE
Fix scalapack create group

### LINKED ISSUE #6351: scalapack and MPI version
I am getting
```
/ssd/deal-git/source/lac/scalapack.cc:443:91: error: there are no arguments to ‘MPI_Comm_create_group’ that depend on a template parameter, so a declaration of ‘MPI_Comm_create_group’ must be available [-fpermissive]
```
This is using openmpi 1.6.5. Is this function only available in a newer MPI standard? What do we do?

### PR DESCRIPTION
**Pull request by masterleinad**
This is an alternative to #6372 that uses an alternative implementation in case the MPI compiler is not MPI-3.0 conforming.

fixes #6351

### CODE REVIEW

**Comment by davydden** [comment]
```
/Users/cib-osx/auto-dealii-tjhei-osx/dealii/include/deal.II/base/mpi.h:154:28: error: unknown type name 'MPI_Group'
                     const MPI_Group &group,
                           ^
```
i think you forgot to wrap it into `#ifdef DEAL_II_WITH_MPI`.

File: source/base/mpi.cc [hunk 1]
```diff
@@ -91,6 +91,72 @@ namespace Utilities
...
+    int create_group(const MPI_Comm  &comm,
+                     const MPI_Group &group,
+                     const int        tag,
+                     MPI_Comm        *new_comm)
+    {
+#if DEAL_II_MPI_VERSION_GTE(3, 0)
+      return MPI_Comm_create_group(comm, group, tag, new_comm);
+#else
+      int rank;
+      AssertThrowMPI(MPI_Comm_rank(comm, &rank));
```
Comment (bangerth) [inline source/base/mpi.cc]: I think this style is confusing because I don't recall whether the argument inside the `AssertThrowMPI` is executed in release mode. Please write it as
```
  int err = MPI_Comm_rank (...);
  AssertThrowMPI(err);
```
Same below.

File: tests/mpi/create_group_01.cc [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+
+// check that Utilities::MPI::create_group is only collective over the group of
+// processes that actually want to create the communicator.
+
+#include "../tests.h"
+
+int main(int argc, char *argv[])
+{
+  MPI_Init (&argc, &argv);
```
Comment (masterleinad) [inline tests/mpi/create_group_01.cc]: For some reason using `Utilities::MPI::MPI_InitFinalize` leads to a deadlock for the `MPI-3.0` compatible `OpenMPI` version.

Comment (masterleinad) [reply tests/mpi/create_group_01.cc]: Probably, the same issue as https://github.com/cburstedde/p4est/issues/30.

Comment (masterleinad) [reply tests/mpi/create_group_01.cc]: > Now that #6380 is merged would you mind putting that back in as an extra check on our sc settings?

Done.

**Comment by davydden** [comment]
@bangerth do you have further comments or are we good to merge?

**Comment by tjhei** [comment]
This looks good. I think we should merge so we can test if things are working now. @bangerth feel free to voice additional concerns later.

**Comment by bangerth** [comment]
This looks good from my side. Thanks for pulling the trigger!
