### PR TITLE
Make compile with boost bind.

### LINKED ISSUE #1168: #1155 breaks non-C++11 code
If deal.II is compiled without C++11, the patch #1155 makes compilation fail (see http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=10278). The reason is that the compiler does not seem to recognize `&FESystem<dim,spacedim>::template compute_fill_one_base<dim_1>` as first argument to boost::bind. @bangerth could you please take a look? I tried to fix it but error messages for boost::bind are so tricky to understand so I gave up after a few attempts (I worked on such things some five years ago but I don't remember what the correct syntax should be).

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #1168.
I tried to group related fields together, so feel free to suggest other parameter groupings here.
Verified on both gcc-4.4 which does not have enough C++11 support and clang-3.7 with C++11 explicitly disabled.

### CODE REVIEW

File: source/fe/fe_system.cc [hunk 1]
```diff
@@ -1296,16 +1295,15 @@ FESystem<dim,spacedim>::compute_fill (
       Threads::TaskGroup<> task_group;
       for (unsigned int base_no=0; base_no<this->n_base_elements(); ++base_no)
         task_group
-        += Threads::new_task (std_cxx11::function<void ()>(std_cxx11::bind (&FESystem<dim,spacedim>::template compute_fill_one_base<dim_1>,
+        += Threads::new_task (std_cxx11::function<void ()>(std_cxx11::bind (&FESystem<dim,spacedim>::compute_fill_one_base<dim_1>,
```
Comment (tjhei) [inline source/fe/fe_system.cc]: what happened to the ```template``` here? Isn't this still a dependent type?

**Comment by tjhei** [comment]
Looks good otherwise.

File: source/fe/fe_system.cc (hunk 1 above)
Comment (kronbichler) [inline source/fe/fe_system.cc]: Good spot, no reason to change it (it did compile on three different compilation units for me even without, but the second variant should be safer).
