### PR TITLE
Warn users about FE index mismatch instead of silently dropping them.

### LINKED ISSUE #14841: active_dof_index out of range gives no exception when FECollection has size 1
This example should give and exception, but it does not:

- Add a single element to an `FE_Collection`
- Choose an active_fe_index that is out of the range of the collection
```c++
#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria.h>

using namespace dealii;

int
main()
{
  constexpr int dim = 2;

  Triangulation<dim> triangulation;
  GridGenerator::hyper_cube(triangulation);

  hp::FECollection<dim> fe_collection(FE_Q<dim>(1));

  DoFHandler<dim> dof_handler(triangulation);

  auto cell = dof_handler.begin_active();

  // Choose index out of range here.
  cell->set_active_fe_index(1);

  dof_handler.distribute_dofs(fe_collection);
}
```

The problem is that the assert (`dof_handler.cc` line 2181) is only checked if the collection has size larger than 1:

```c++
  if (hp_capability_enabled)
    {
      // make sure every processor knows the active FE indices
      // on both its own cells and all ghost cells
      internal::hp::DoFHandlerImplementation::Implementation::
        communicate_active_fe_indices(*this);

#ifdef DEBUG
      // make sure that the FE collection is large enough to
      // cover all FE indices presently in use on the mesh
      for (const auto &cell : this->active_cell_iterators())
        {
          if (!cell->is_artificial())
            Assert(cell->active_fe_index() < this->fe_collection.size(),
                   ExcInvalidFEIndex(cell->active_fe_index(),
                                     this->fe_collection.size()));
          if (cell->is_locally_owned())
            Assert(cell->future_fe_index() < this->fe_collection.size(),
                   ExcInvalidFEIndex(cell->future_fe_index(),
                                     this->fe_collection.size()));
        }
#endif
    }
```

It looks like the assert should be moved out of the if-statment, but I can not figure what we should do with this call:
```c++
      internal::hp::DoFHandlerImplementation::Implementation::
        communicate_active_fe_indices(*this);
```
It looks like it should only be done when `FECollection` has size larger than 1, but it will affect the assert in parallel. Any ideas?

### PR DESCRIPTION
**Pull request by marcfehling**
Closes #14841.

Moved an assertion to the beginning of a function. It is sufficient to only check locally owned cells, as they will communicated later.

@simonsticko -- I used your example as a test.

### CODE REVIEW

**Comment by marcfehling** [comment]
I have found an interesting bug when calling [`create_triangulation(construction_data)`](https://www.dealii.org/developer/doxygen/deal.II/classTriangulation.html#aa80c37d5d647831736e40e4ffb0e0ee2) and a DoFHandler in hp-mode. @peterrum -- FYI

The DoFHandler connects functions to refinement signals specific to the type of Triangulation class used. For example when using p:d:Tria, we only connect to the `post_distributed_refinement` signals. The `create_triangulation` function internally calls the basic `dealii::Triangulation::execute_coarsening_and_refinement` function and triggers the `post_refinement` signal. When using p:d:Tria, we never connect to the `post_refinement` signal, only to the `post_distributed_refinement` one.

The problem now is that we keep the active FE table updated through these signals. Thus when using p:d:Tria with `create_triangulation(construction_data)`, the FE table will not be updated through refinements. I tried to fix this by triggering the `create` signal once more at the end of the function, i.e., treating the resulting triangulation as a fresh one.

**Comment by bangerth** [comment]
On 3/10/23 03:38, Marc Fehling wrote:
> The DoFHandler connects functions to refinement signals specific to the type 
> of Triangulation class used. For example when using p:d:Tria, we only connect 
> to the |post_distributed_refinement| signals. The |create_triangulation| 
> function internally calls the basic 
> |dealii::Triangulation::execute_coarsening_and_refinement| function and 
> triggers the |post_refinement| signal. When using p:d:Tria, we never connect 
> to the |post_refinement| signal, only to the |post_distributed_refinement| one.

Wasn't that on purpose because refinement of a p:d:T also involved 
re-partitioning, which causes a complete rebuild of the local part of the 
triangulation, with possibly many calls to the 'post_refinement' signal?

**Comment by marcfehling** [comment]
> Wasn't that on purpose because refinement of a p:d:T also involved re-partitioning, which causes a complete rebuild of the local part of the triangulation, with possibly many calls to the 'post_refinement' signal?

I believe this signal has been introduced before I joined the project, but the documentation of the signal matches your statement.
https://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1Signals.html#a3ee8aba0dcbc1ed64aefa2b17a00cbec

At some point, we decided to perform the transfer of FE indices with these signals. This works differently in the parallel distributed case, and we wanted to split this functionality into separate functions (`pre|post_transfer_action()` and `pre|post_distibuted_transfer_action()`)

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
@bangerth are you OK with this change?

**Comment by marcfehling** [comment]
ping

File: source/grid/tria.cc [hunk 1]
```diff
@@ -11898,6 +11898,9 @@ void Triangulation<dim, spacedim>::create_triangulation(
               cell->face(pair.first)->set_boundary_id(pair.second);
         }
     }
+
+  // inform all listeners that the triangulation has been created
+  signals.create();
```
Comment (bangerth) [inline source/grid/tria.cc:11903]: This is an unrelated change. This PR has been sitting around for too long already, but could you add a changelog entry for this, along with a test?

**Review by bangerth — APPROVED** [review]

File: source/grid/tria.cc (hunk 1 above)
Comment (bangerth) [reply source/grid/tria.cc:11903]: ...after I merge, that is.

Comment (marcfehling) [reply source/grid/tria.cc:11903]: The tests `simplex/step-55` and `simplex/step-67` fail without this line of code.

I've provided a changelog in #14866. Do you want me to add another test?

Comment (bangerth) [reply source/grid/tria.cc:11903]: But if these tests fail without this patch, how did they succeed before? Or are you saying that moving the active-fe-index check exposed the bug, and consequently these tests failed and required the calling of the signal?

If so, no, no further tests necessary!

Comment (marcfehling) [reply source/grid/tria.cc:11903]: > Or are you saying that moving the active-fe-index check exposed the bug, and consequently these tests failed and required the calling of the signal?

Exactly this was the case. Moving the check exposed the bug. See also https://github.com/dealii/dealii/pull/14866#issuecomment-1463608649

Comment (bangerth) [reply source/grid/tria.cc:11903]: OK, thanks for confirming!
