### PR TITLE
Fail to install p4est if it is not compiled with zlib.

### LINKED ISSUE #4333: Modify the p4est build script to include zlib
There is a [thread](https://groups.google.com/forum/#!topic/dealii/p-64i1ahEWM) on the mailing list discussing this. We should add a check to our build script to make sure that we really do build p4est correctly.

### PR DESCRIPTION
**Pull request by drwells**
I thought about #4333 a bit more and I think I found a solution: we can check, after building p4est, that p4est set itself up with zlib. If not we can refuse to install it. Since there is no way to fail during configuration I think that this is the way to do it.

Closes #4333.

### CODE REVIEW

**Comment by bangerth** [comment]
This looks reasonable to me. Do we have guidance what a user should do to whom this happens?

**Comment by drwells** [comment]
I don't know enough about p4est to wager more than a guess that zlib needs to be installed in a standard place for p4est to find it. I'll add a hint.

**Comment by drwells** [comment]
I added a bit more text to the explanation.

File: doc/external-libs/p4est-setup.sh [hunk 1]
```diff
@@ -114,6 +114,10 @@ cd "$BUILD_FAST"
         "$@" > config.output || bdie "Error in configure"
 make -C sc -j 8 > make.output || bdie "Error in make sc"
 make -j 8 >> make.output || bdie "Error in make p4est"
+# ensure that we built p4est with zlib
+grep -q 'P4EST_HAVE_ZLIB *1' "$BUILD_FAST/src/p4est_config.h" \
+    || bdie "deal.II requires that p4esT be built with zlib support. Make sure \
```
Comment (tjhei) [inline doc/external-libs/p4est-setup.sh]: p4est not p4esT

File: doc/external-libs/p4est-setup.sh [hunk 2]
```diff
@@ -128,6 +132,10 @@ cd "$BUILD_DEBUG"
         "$@" > config.output || bdie "Error in configure"
 make -C sc -j 8 > make.output || bdie "Error in make sc"
 make -j 8 >> make.output || bdie "Error in make p4est"
+# ensure that we built p4est with zlib
+grep -q 'P4EST_HAVE_ZLIB *1' "$BUILD_DEBUG/src/p4est_config.h" \
+    || bdie "deal.II requires that p4esT be built with zlib support. Make sure \
```
Comment (tjhei) [inline doc/external-libs/p4est-setup.sh]: same here

**Comment by drwells** [comment]
I fixed the typo.

**Comment by kronbichler** [comment]
I didn't really investigate the issue back in #4333 or #4151 but since you only do some grep in the `p4est_config.h` file that is also available at the point we search for the p4est installation at deal.II configure time, I wonder why we can't do it there? Is it because there is no way to do it in cmake? One could make a small build file that fails if `P4EST_HAVE_ZLIB` is not defined...

**Comment by drwells** [comment]
@kronbichler In a sense this PR is redundant because #4193 adds exactly that check. I still think that we should add this check so that users don't use our build script to compile a version of p4est that they cannot use.

**Comment by drwells** [comment]
I added some more hints to the user for what they should do in case zlib detection fails in the form of a much longer error message.

**Comment by kronbichler** [comment]
OK, I understand. Thanks for the clarification. This PR is fine from my point of view.
