### PR TITLE
Fix two bugs in step-86

### LINKED ISSUE #18612: MPI run on tutorial step-86 stalls if more than 16 processors are used
Hi all, I was trying the step-86 tutorial code with MPI. The code works fine with MPI up to 15 processes (i.e., using -np < 16).
However, When I tried `mpirun -np 16 ./build/step-86 ` it stalled after the first solving was finished. Strangely, it did not crash, and no error message popped out. After some simple debugging, I found it stopped at line 458, where the non-homogeneous constraints was distributing the non-ghosted vector:
` current_constraints.distribute(tmp_solution);`.
Initially, I thought it might be a partitioning issue, but the same problem occurs even with a finer mesh, as long as I use more than 15 processors. At this point, I’m unsure what could be causing this behavior. I’m also wondering whether this issue is specific to my system, or if others can reproduce it on their machines.
Thanks in advance for your insights!

### PR DESCRIPTION
**Pull request by kronbichler**
Fixes #18612. 

This turned out to be a difficult-to-track bug since it only appeared for larger processor counts. (In fact, I already saw a problem with 13 MPI ranks, but not 14 or 15). Actually, there were two bugs in the program related to parallel execution, which I will mark up separately in the code soon. It is actually remarkable that this worked before.

FYI @yaobinyang.

### CODE REVIEW

File: examples/step-86/step-86.cc [hunk 1]
```diff
@@ -330,26 +341,28 @@ namespace Step86
...
                                              0,
                                              Functions::ZeroFunction<dim>(),
                                              homogeneous_constraints);
-    homogeneous_constraints.make_consistent_in_parallel(locally_owned_dofs,
-                                                        locally_relevant_dofs,
-                                                        mpi_communicator);
+    homogeneous_constraints.make_consistent_in_parallel(
+      locally_owned_dofs,
+      hanging_node_constraints.get_local_lines(),
+      mpi_communicator);
```
Comment (kronbichler) [inline examples/step-86/step-86.cc:365]: This was bug 1: We want to merge from `hanging_node_constraints`, but due to the call `hanging_node_constraints.make_consistent_in_parallel()` a few lines up we might end up changing the local lines stored in that object. However, if that is the case, we cannot just merge the constraints. While one could try to set the flag `allow_different_local_lines` in the merge function, I am not sure how it would work, so I think it is much better to teach the readers to use the same representation of constraints if they choose to do merging.

File: examples/step-86/step-86.cc [hunk 2]
```diff
@@ -912,15 +925,17 @@ namespace Step86
   template <int dim>
   void HeatEquation<dim>::update_current_constraints(const double time)
   {
-    if (current_constraints.n_constraints() == 0 ||
+    if (Utilities::MPI::sum(current_constraints.n_constraints(),
+                            mpi_communicator) == 0 ||
```
Comment (kronbichler) [inline examples/step-86/step-86.cc:929]: And here is bug 2, and the one that caused the initial hang: Since `AffineConstraints::n_constraints()` returns the number of constraints stored on the local MPI process, it can happen that different processes end up with different opinions. To be precise, as soon as we have 13 (or 16 and more) MPI processes, some end up not having any piece of the boundary, so they never get to see any boundary condition, so their check is different from the ones at the boundary.

I thought if there would be a way to detect this inside the library, but I could not find a simple solution and thought we should just fix the code here.

File: examples/step-86/step-86.cc [hunk 3]
```diff
@@ -203,7 +203,7 @@ namespace Step86
     // the same degrees of freedom, but with zero values even if the boundary
     // values for the solution are non-zero; we will keep this modified set of
     // constraints in `homogeneous_constraints`.
-    AffineConstraints<double> hanging_nodes_constraints;
+    AffineConstraints<double> hanging_node_constraints;
```
Comment (kronbichler) [inline examples/step-86/step-86.cc:206]: I also changed the name here because I stumbled over it. We might not always be consistent with names in deal.II, but apart from step-86 we never use `hanging_nodes_constraints`, but more than a thousand times the term `hanging_node_constraints`.

**Review by tamiko — APPROVED** [review]

File: examples/step-86/step-86.cc [hunk 4]
```diff
@@ -330,26 +341,28 @@ namespace Step86
...
     DoFTools::make_hanging_node_constraints(dof_handler,
-                                            hanging_nodes_constraints);
-    hanging_nodes_constraints.make_consistent_in_parallel(locally_owned_dofs,
-                                                          locally_relevant_dofs,
-                                                          mpi_communicator);
-    hanging_nodes_constraints.close();
+                                            hanging_node_constraints);
+    hanging_node_constraints.make_consistent_in_parallel(locally_owned_dofs,
+                                                         locally_relevant_dofs,
+                                                         mpi_communicator);
```
Comment (drwells) [inline examples/step-86/step-86.cc:350]: Do we always need to call this function nowadays? That's missing from step-45.

Comment (bangerth) [reply examples/step-86/step-86.cc:350]: @drwells I think it's probably good practice. It's probably not *necessary* in all cases, but it avoids subtle bugs that may otherwise be hard to find.

File: examples/step-86/step-86.cc [hunk 5]
```diff
@@ -309,6 +309,17 @@ namespace Step86
   // derivative of the solution when computing the residual. We use the
   // `homogeneous_constraints` object for this purpose.
   //
+  // Note one detail here: The function
+  // AffineConstraints::make_consistent_in_parallel() might change the
```
Comment (bangerth) [inline examples/step-86/step-86.cc]: Perhaps it's worth replacing "change" by "expand"? The fact that the set may become larger (rather than smaller) is important in this context.

File: examples/step-86/step-86.cc (hunk 2 above)
Comment (bangerth) [reply examples/step-86/step-86.cc:929]: Nice find!

**Review by bangerth — COMMENTED** [review]
Couldn't we get away with calling `merge()` first, and *then* `make_consistent_in_parallel()`?

**Comment by yaobinyang** [comment]
Thanks Prof. Kronbichler I thinks this works now

File: examples/step-86/step-86.cc (hunk 2 above)
Comment (tjhei) [reply examples/step-86/step-86.cc:929]: > I thought if there would be a way to detect this inside the library, but I could not find a simple solution and thought we should just fix the code here.

I do not expect there is a way to do this, because ``n_constraints()`` is not collective and there might be a legitimate reason to use it.

**Review by tjhei — APPROVED** [review]

**Comment by kronbichler** [comment]
> Couldn't we get away with calling merge() first, and then make_consistent_in_parallel()?

That's a good question: I believe it should work for the basic case considered here (no hp adaptivity), also because we do not call that function in many other tutorials and they also work. However, I also think that it is good to `close()` the hanging node constraints and resolve possible chains before moving on, because they can be more expensive to resolve than Dirichlet conditions. On the other hand, Dirichlet conditions do give rise to some additional chain resolving steps for hanging nodes near the boundary, so I'm not sure how much it does. I would suggest to leave the code as is, but it might be interesting to look into it to see how it would behave in the future.
