### PR TITLE
Fix serialization of empty SparsityPattern objects

### LINKED ISSUE #13030: SparsityPattern serialization causing segfault
When I serialize the `SparsityPattern` object constructed with default constructor I get a segmentation fault.
A minimal example is given below:
```lang-cpp
#include <deal.II/lac/sparsity_pattern.h>

#include <boost/archive/text_oarchive.hpp>

#include <fstream>

int main()
{
    dealii::SparsityPattern sp;

    std::ofstream ofs("sparsity_test.dat");
    {
        boost::archive::text_oarchive oa(ofs);
        oa << sp;
    }

    return 0;
}
```
The only thing I get as output is:
```
Segmentation fault (core dumped)
```
My detailed.log file is given here:
```
###
#
#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       DebugRelease
#        BUILD_SHARED_LIBS:      ON
#        CMAKE_INSTALL_PREFIX:   /usr/local
#        CMAKE_SOURCE_DIR:       /home/lucas/Application-Data/dealii
#                                (version 10.0.0-pre, shortrev 24e77b90af)
#        CMAKE_BINARY_DIR:       /home/lucas/Application-Data/dealii/build
#        CMAKE_CXX_COMPILER:     GNU 9.3.0 on platform Linux x86_64
#                                /usr/bin/c++
#        C++ language standard:  C++14
#        CMAKE_C_COMPILER:       /usr/bin/cc
#        CMAKE_GENERATOR:        Unix Makefiles
#
#  Base configuration (prior to feature configuration):
#        DEAL_II_CXX_FLAGS:            -fPIC -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-class-memaccess -fopenmp-simd
#        DEAL_II_CXX_FLAGS_RELEASE:    -O2 -funroll-loops -funroll-all-loops -fstrict-aliasing -Wno-unused-local-typedefs
#        DEAL_II_CXX_FLAGS_DEBUG:      -O0 -ggdb -Wa,--compress-debug-sections
#        DEAL_II_LINKER_FLAGS:         -Wl,--as-needed -rdynamic -fuse-ld=gold -lpthread -fopenmp
#        DEAL_II_LINKER_FLAGS_RELEASE: 
#        DEAL_II_LINKER_FLAGS_DEBUG:   -ggdb
#        DEAL_II_DEFINITIONS:          
#        DEAL_II_DEFINITIONS_RELEASE:  NDEBUG
#        DEAL_II_DEFINITIONS_DEBUG:    DEBUG
#        DEAL_II_USER_DEFINITIONS:     
#        DEAL_II_USER_DEFINITIONS_REL: NDEBUG
#        DEAL_II_USER_DEFINITIONS_DEB: DEBUG
#        DEAL_II_INCLUDE_DIRS          
#        DEAL_II_USER_INCLUDE_DIRS:    
#        DEAL_II_BUNDLED_INCLUDE_DIRS: 
#        DEAL_II_LIBRARIES:            
#        DEAL_II_LIBRARIES_RELEASE:    
#        DEAL_II_LIBRARIES_DEBUG:      
#        DEAL_II_VECTORIZATION_WIDTH_IN_BITS: 0
#        DEAL_II_HAVE_CXX14
#
#  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#      ( DEAL_II_WITH_ADOLC = OFF )
#      ( DEAL_II_WITH_ARBORX = OFF )
#      ( DEAL_II_WITH_ARPACK = OFF )
#      ( DEAL_II_WITH_ASSIMP = OFF )
#        DEAL_II_WITH_BOOST set up with external dependencies
#            BOOST_VERSION = 1.76.0
#            BOOST_CXX_FLAGS = -Wno-unused-local-typedefs
#            BOOST_DEFINITIONS = BOOST_NO_AUTO_PTR
#            BOOST_USER_DEFINITIONS = BOOST_NO_AUTO_PTR
#            BOOST_INCLUDE_DIRS = /usr/local/include
#            BOOST_USER_INCLUDE_DIRS = /usr/local/include
#            BOOST_LIBRARIES = /usr/local/lib/libboost_serialization.so;/usr/local/lib/libboost_system.so;/usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_chrono.so;/usr/local/lib/libboost_date_time.so;/usr/local/lib/libboost_atomic.so
#        DEAL_II_WITH_COMPLEX_VALUES = ON
#        DEAL_II_WITH_CUDA set up with external dependencies
#            CUDA_VERSION = 11.4
#            CMAKE_CUDA_COMPILER = /usr/local/cuda-11.4/bin/nvcc
#            CUDA_COMPUTE_CAPABILITY = 7.5
#            DEAL_II_CUDA_FLAGS = -arch=sm_75
#            DEAL_II_CUDA_FLAGS_RELEASE = 
#            DEAL_II_CUDA_FLAGS_DEBUG = -G
#            CUDA_INCLUDE_DIRS = /usr/local/cuda-11.4/include
#            CUDA_USER_INCLUDE_DIRS = /usr/local/cuda-11.4/include
#            CUDA_LIBRARIES = /usr/local/cuda-11.4/lib64/libcudart.so;/usr/local/cuda-11.4/lib64/libcusparse.so;/usr/local/cuda-11.4/lib64/libcusolver.so
#      ( DEAL_II_WITH_GINKGO = OFF )
#      ( DEAL_II_WITH_GMSH = OFF )
#      ( DEAL_II_WITH_GSL = OFF )
#      ( DEAL_II_WITH_HDF5 = OFF )
#      ( DEAL_II_WITH_KOKKOS = OFF )
#        DEAL_II_WITH_LAPACK set up with external dependencies
#            LAPACK_WITH_64BIT_BLAS_INDICES = OFF
#            LAPACK_LINKER_FLAGS = 
#            LAPACK_INCLUDE_DIRS = 
#            LAPACK_USER_INCLUDE_DIRS = 
#            LAPACK_LIBRARIES = /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so
#      ( DEAL_II_WITH_METIS = OFF )
#      ( DEAL_II_WITH_MPI = OFF )
#        DEAL_II_WITH_MUPARSER set up with bundled packages
#            MUPARSER_BUNDLED_INCLUDE_DIRS = /home/lucas/Application-Data/dealii/bundled/muparser_v2_2_4//include
#      ( DEAL_II_WITH_OPENCASCADE = OFF )
#      ( DEAL_II_WITH_P4EST = OFF )
#      ( DEAL_II_WITH_PETSC = OFF )
#      ( DEAL_II_WITH_SCALAPACK = OFF )
#      ( DEAL_II_WITH_SLEPC = OFF )
#      ( DEAL_II_WITH_SUNDIALS = OFF )
#      ( DEAL_II_WITH_SYMENGINE = OFF )
#        DEAL_II_WITH_TASKFLOW set up with bundled packages
#            TASKFLOW_BUNDLED_INCLUDE_DIRS = /home/lucas/Application-Data/dealii/bundled/taskflow-2.5.0/include
#        DEAL_II_WITH_TBB set up with bundled packages
#            TBB_CXX_FLAGS = -Wno-parentheses
#            TBB_BUNDLED_INCLUDE_DIRS = /home/lucas/Application-Data/dealii/bundled/tbb-2018_U2/include
#            TBB_LIBRARIES = dl
#      ( DEAL_II_WITH_TRILINOS = OFF )
#        DEAL_II_WITH_UMFPACK set up with bundled packages
#            UMFPACK_BUNDLED_INCLUDE_DIRS = /home/lucas/Application-Data/dealii/bundled/umfpack/UMFPACK/Include;/home/lucas/Application-Data/dealii/bundled/umfpack/AMD/Include
#      ( DEAL_II_WITH_ZLIB = OFF )
#
#  Component configuration:
#      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
#        DEAL_II_COMPONENT_EXAMPLES
#      ( DEAL_II_COMPONENT_PACKAGE = OFF )
#      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )
#
###
```
Any help is appreciated.

### PR DESCRIPTION
**Pull request by bangerth**
Took a bit more than suggested in #13030, but not very much. Fixes #13030.

Thanks, @lucasmyers97 for the excellent testcase! That made all the difference!

/rebuild

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

File: tests/serialization/sparsity_pattern_empty.cc [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+#include <deal.II/lac/sparsity_pattern.h>
+
+#include "../testmatrix.h"
+#include "serialization.h"
+
+
+void
+test()
+{
+  // Try a sparsity pattern that has nonzero size, but is otherwhise empty
```
Comment (jppelteret) [inline tests/serialization/sparsity_pattern_empty.cc:29]:
```suggestion
  // Try a sparsity pattern that has nonzero size, but is otherwise empty
```
(if you care to make this fix)

**Review by jppelteret — APPROVED** [review]

**Comment by bangerth** [comment]
Fixed as requested.
