### PR TITLE
Fix an issue with spaces in ParameterHandler output.

### LINKED ISSUE #17807: `Parameterhandler::print_parameters`: wrong indentation
Printing parameters with
```
std::ofstream output("parameters.prm");
ParameterAcceptor::prm.print_parameters(output, ParameterHandler::ShortPRM);
```
with the current master branch of deal.II (commit 9627ae39f55379967d76afac92e8c4ad556135df - issue was introduced earlier) now results in the following output:
```
subsection C - Discretization
set geometry              = airfoil
...
  subsection airfoil
set airfoil center                      = -0.5, 0
...
  end
end
```

All the `set ...` statements are moved to the left. Previously we got a properly indented output:
```
subsection C - Discretization
  set geometry              = airfoil
  ...
  subsection airfoil
    set airfoil center                      = -0.5, 0
    ...
  end
end
```

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #17807 by reverting a part of the changes in #17616.

@gassmoeller @tamiko FYI.

### CODE REVIEW

File: source/base/parameter_handler.cc [hunk 1]
```diff
@@ -1602,8 +1602,8 @@ ParameterHandler::recursively_print_parameters(
               }
 
             // print the name and (if set) value of this entry
-            out << std::setw(overall_indent_level * 2) << "set "
-                << demangle(p.first)
+            out << std::setw(overall_indent_level * 2) << ""
+                << "set " << demangle(p.first)
```
Comment (bangerth) [inline source/base/parameter_handler.cc:1606]: The important point here is that the width set with `setw()` is used to put the following object into a box this many characters wide. If you then pass `""`, this creates a number of spaces. If you pass anything else, it gets put into that box. Here (as in the code before #17616), we really just want to pad with a few spaces, so we need to pass an empty string.

Comment (drwells) [reply source/base/parameter_handler.cc:1606]: Interesting case. Is there a reason we can't use `std::right` and `std::setfill(' ')` here? That would be idiomatic.

We should also add a test since we already broke this once.

Comment (bangerth) [reply source/base/parameter_handler.cc:1606]: But I don't actually want to right-align anything. I just want to print a specific number of spaces, and I think the code expresses that. How else would you want to write it?

I'll think about a test.

**Review by gassmoeller — APPROVED** [review]
Yes this makes sense. I am pretty sure I just didnt understand the purpose of the empty string in my previous PR.

**Comment by gassmoeller** [comment]
Feel free to merge as is or to add a test. Is it worth adding your reply as a comment to the code in case someone else wants to delete the "useless" empty string?

File: source/base/parameter_handler.cc (hunk 1 above)
Comment (drwells) [reply source/base/parameter_handler.cc:1606]: Yeah, what I suggested wouldn't work. I don't feel that strongly about it but we could accomplish the same thing via
```cpp
out << std::string(overall_indent_level * 2, ' ')
```
instead of using stream manipulators.

Comment (bangerth) [reply source/base/parameter_handler.cc:1606]: I don't think that's much easier to read. I'll just add a comment.

**Comment by bangerth** [comment]
I added a test.

File: tests/parameter_handler/parameter_handler_6_spaces.cc [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+// This is a variation of the parameter_handler_6 test. At some point,
+// we made an inadvertant change that led to no longer correctly
+// indenting the parameters listed in a section when outputting the
+// current state of a ParameterHandler object. numdiff didn't catch it
+// because it ignores whitespace except to separate tokens. This test
+// therefore outputs everything into a stringstream, replaces every
+// space by an underscore, and outputs that. Changes in indentation
+// will then show up as changes in output in a way that can't be
+// ignored by numdiff.
```
Comment (drwells) [inline tests/parameter_handler/parameter_handler_6_spaces.cc:25]: Thanks for checking this out - this explains why we didn't catch the bug earlier.
