### PR TITLE
Fix FESystem::convert_generalized_support_point_values_to_dof_values

### LINKED ISSUE #4090: Generalize generalized support points
In #4064, @luca-heltai brings up a number of really interesting ideas about generalized support points. Specifically, the second and fourth comment provide ideas about how one would interpret what GSPs are.

It would be useful to codify this interpretation in the glossary, for example, which contains a lengthy discussion (due to #3848) but makes the assumption that there are as many GSPs as there are shape function.

### PR DESCRIPTION
**Pull request by tamiko**
Use generalized_support_points_index_table to correctly convert generalized
support point values to dof values.

In reference to #4992
Closes #4090

### CODE REVIEW

**Comment by tamiko** [comment]
Luca and I took the liberty to rename `convert_generalized_support_point_values_to_nodal_values` to `convert_generalized_support_point_values_to_dof_values` to be a bit more precise.

Unfortunately, this makes this PR a bit more messy.

Final check and a new test coming soon.

**Comment by bangerth** [comment]
Hm, I think the old name was actually better suited. It intends to convey that we are evaluating the *node functionals* to the given function.

But I guess in the end, what we get is the "values of the node functionals" which equals the "values of the degrees of freedom of the interpolant".

File: source/fe/fe_system.cc [hunk 1]
```diff
@@ -2251,64 +2251,71 @@ FESystem<dim,spacedim>::get_constant_modes () const
...
+      const unsigned int multiplicity = this->element_multiplicity(base);
+      const unsigned int n_base_dofs = base_element.dofs_per_cell;
+      const unsigned int n_base_points =
+        base_element.get_generalized_support_points().size();
+      const unsigned int n_base_components = base_element.n_components();
+
+      // FIXME: These temporary vectors are extremely unfortunate. But there
+      // is no easy way around copying all data to make a recursive call...
+      std::vector<double> base_dof_values(n_base_dofs);
+      std::vector<Vector<double> > base_point_values(n_base_points);
```
Comment (bangerth) [inline source/fe/fe_system.cc]: This function is really not called very frequently, so I wouldn't worry about the FIXME. But if you do care, move the declaration of the vector outside the loop and just do a `resize` here.

File: source/fe/fe_system.cc [hunk 2]
```diff
@@ -2251,64 +2251,71 @@ FESystem<dim,spacedim>::get_constant_modes () const
...
+
+      for (unsigned int m = 0; m < multiplicity;
+           ++m, current_vector_component += base_element.n_components())
```
Comment (bangerth) [inline source/fe/fe_system.cc]: for the second increment, you have `n_base_components` defined above

File: source/fe/fe_system.cc [hunk 3]
```diff
@@ -2251,64 +2251,71 @@ FESystem<dim,spacedim>::get_constant_modes () const
...
-          // then call the base element to get its version of the
-          // nodal values
-          base_nodal_values.resize (base_element(base).dofs_per_cell);
-          base_element(base).convert_generalized_support_point_values_to_nodal_values
-          (base_support_point_values, base_nodal_values);
+              // we have to extract the correct slice out of the global
+              // vector of values:
+              const auto n = generalized_support_points_index_table[base][j];
+              const VectorSlice<const Vector<double> > slice(
+                point_values[n], current_vector_component, n_base_components);
```
Comment (bangerth) [inline source/fe/fe_system.cc]: This is really just too obscure -- setting up the `VectorSlice` just so you can call `std::copy`. I had to look up what the constructor arguments mean. Can't you just replace all of this with a hand-written loop that cherry-picks the elements from `point_values` and puts them into `base_point_values`? I think that would be a lot simpler to read.

Comment (tamiko) [reply source/fe/fe_system.cc]: I can replace this with raw iterator ranges, but the call to `std::copy` will remain.

Comment (tamiko) [reply source/fe/fe_system.cc]: Incidentally I converted this from the former to the current format because I think the `VectorSlice` greatly increases readability.

Comment (bangerth) [reply source/fe/fe_system.cc]: I don't see that. I don't think it's (i) easier to read, given that I now need to look up what `VectorSlice` does, (ii) faster given that all of the same index translations still have to happen, (iii) shorter, given that I could write down the whole loop that happens in `std::copy` in just half a dozen lines of code, including all of the index translation.

File: source/fe/fe_system.cc (hunk 1 above)
Comment (tamiko) [reply source/fe/fe_system.cc]: The problem is the recursive call that might allocate this vector again. But let me simply remove the FIXME.

A warning: This function will be called significantly more often in the future, we plan to reimplement VectorTools::interpolate to exclusively use generalized support points.

I suggest we do some benchmarking after that is done and optimize if necessary.

File: source/fe/fe_system.cc (hunk 3 above)
Comment (tamiko) [reply source/fe/fe_system.cc]: The call to std::copy is just four lines (expanded for better readability).

File: source/fe/fe_system.cc (hunk 1 above)
Comment (bangerth) [reply source/fe/fe_system.cc]: That's ok with me. But if you're concerned, you can still move the declaration outside the loop -- this way, at least you don't have to re-allocate memory all the time.

File: source/fe/fe_system.cc [hunk 4]
```diff
@@ -2251,64 +2251,66 @@ FESystem<dim,spacedim>::get_constant_modes () const
...
+          for (unsigned int j = 0; j < base_point_values.size(); ++j)
+            {
+              base_point_values[j].reinit(n_base_components, false);
+
+              // we have to extract the correct slice out of the global
+              // vector of values:
+              const auto begin =
+                std::begin(point_values[n]) + current_vector_component;
+              const auto end = begin + n_base_components;
+              std::copy(begin, end, std::begin(base_point_values[j]));
```
Comment (bangerth) [inline source/fe/fe_system.cc]: yes, I like this better.

**Comment by tamiko** [comment]
@bangerth 
`dof_values` has the advantage that it is the name that is used throughout the library.
That makes it conceptually much clearer what the output can be used for.

File: source/fe/fe_system.cc (hunk 4 above)
Comment (tamiko) [reply source/fe/fe_system.cc]: @bangerth And still not a for loop ;-)

Comment (bangerth) [reply source/fe/fe_system.cc]: :-) :+1:

**Comment by bangerth** [comment]
@tamiko -- that's fine by me. The function is sufficiently obscure that changing its name is not likely going to upset anyone :-)

**Comment by tamiko** [comment]
Very nice. Thanks for the feedback!
I'll go on a short bike ride now and will push the rest later tonight.

**Comment by bangerth** [comment]
Yes, go train for that 100k ride!

Next time you're down here, @tjhei and I will take you on a 100 mile ride into the mountains!

**Comment by tamiko** [comment]
@bangerth :-D

I have added a test and this pull request is finally ready for review :-)

Given the fact that this primitive will be tested much more thoroughly with a new `VectorTools::interpolate` variant, I settled on just adding one test. Further, I have the feeling that `FE_Nedelec::convert_...` is broken. Issue incoming.

**Comment by bangerth** [comment]
There are two tests that fail. Can you take a look?

**Comment by bangerth** [comment]
Other than that, this is good to merge.

**Comment by masterleinad** [comment]
`fe/fe_system_generalized_support_points`is fixed in #5006

**Comment by tamiko** [comment]
@masterleinad Thanks for taking care of this!

**Comment by tamiko** [comment]
@masterleinad @bangerth Merging this PR would make the other three things I want to do easier :-)

**Comment by tjhei** [comment]
This PR broke a test:
```
 /tests/fe/interpolate_system_2.cc:36:28: error: use of deleted function â€˜dealii::FESystem<dim, spacedim>::FESystem(const dealii::FESystem<dim, spacedim>&) [with int dim = 2; int spacedim = 2]â€™
```
@tamiko can you please take a look?

**Comment by tjhei** [comment]
@bangerth you noticed two failing tests and still decided to merge after one got fixed? ;-)

**Comment by bangerth** [comment]
Yes, I clearly didn't pay attention :-(

**Comment by bangerth** [comment]
The test is fixed in #5029.
