### PR TITLE
Tests: base/reference.cc - avoid "use after scope"

### LINKED ISSUE #7314: base/reference.debug - stack-use-after-scope causes segfault with clang
`base/reference.debug` contains the following comment:
```
 99   // Destruction of "Test R" will cause a spurious ExcNotUsed here,              
100   // since D was deleted first. This shows up in address sanitizers              
101   // as stack-use-after-scope, but we can't do anything about it.
```
Unfortunately, it is worse than that. We do indeed perform a stack use after scope which results in an invalid memory access and segfault when compiling with clang:
```
#0  std::__1::__tree<std::__1::__value_type<char const*, unsigned int>, std::__1::__map_value_compare<char const*, std::__1::__value_type<char const*, unsigned int>, std::__1::less<char const*>, true>, std::__1::allocator<std::__1::__value_type<char const*, unsigned int> > >::__lower_bound<char const*> (this=0x7fffffffe050, __v=<optimized out>, 
    __root=<error reading variable: Cannot access memory at address 0x6269726373627553>, __result=0x6269726373627553) at /usr/include/c++/v1/__tree:2483
#1  0x00007ffff3531957 in std::__1::__tree<std::__1::__value_type<char const*, unsigned int>, std::__1::__map_value_compare<char const*, std::__1::__value_type<char const*, unsigned int>, std::__1::less<char const*>, true>, std::__1::allocator<std::__1::__value_type<char const*, unsigned int> > >::find<char const*> (this=0x7fffffffe050, __v=@0x7fffffffdb68: 0x410aa8 "Test R")
    at /usr/include/c++/v1/__tree:2412
#2  0x00007ffff353103c in std::__1::map<char const*, unsigned int, std::__1::less<char const*>, std::__1::allocator<std::__1::pair<char const* const, unsigned int> > >::find (
    this=<optimized out>, __k=@0x410aa8: 0x6300522074736554 <error: Cannot access memory at address 0x6300522074736554>) at /usr/include/c++/v1/map:1210
#3  dealii::Subscriptor::unsubscribe (this=0x7fffffffe040, id=<optimized out>) at /srv/testsuite/dealii/source/base/subscriptor.cc:186
#4  0x000000000040d4b5 in dealii::SmartPointer<Test, Test>::~SmartPointer (this=0x410aa8) at /srv/testsuite/dealii/include/deal.II/base/smartpointer.h:264
#5  0x000000000040c925 in main () at /srv/testsuite/dealii/tests/base/reference.cc:102
```

Maybe we should avoid the `find` call in subscriptor.cc:186 in this case? Or simply not test for this behavior at all?

### PR DESCRIPTION
**Pull request by tamiko**
gcc might be a bit forgiving with our use after scope here,
unfortunately, clang isn't. Let's simply work around this issue by
creating using a sentinel that simply resets the SmartPointer when going
out of scope

Closes #7314

### CODE REVIEW

File: tests/base/reference.cc [hunk 1]
```diff
@@ -60,6 +60,29 @@ class Test : public Subscriptor
...
+public:
+  Sentinel(SmartPointer<T, P> &smart_pointer)
+    : smart_pointer_(smart_pointer)
+  {}
+
+  ~Sentinel()
+  {
+    // This assumes that the first object stored in SmartPointer is a raw
+    // pointer T*
+    *reinterpret_cast<T **>(&smart_pointer_) = nullptr;
```
[the remark this answers is not in the document]
Comment (masterleinad) [reply tests/base/reference.cc]: As long as you don't put something like that in the library itself... :wink:

File: tests/base/reference.cc [hunk 2]
```diff
@@ -94,9 +117,21 @@ main()
...
   r = &c;
+
+  // We have to dance a happy little dance here:
+  //
+  // In our case the object D defined below will go out of scope before the
+  // smartpointer "Test R" does. Under normal circumstances this triggers
+  // an ExcNotUsed and aborts the program. BUT, this is a unit test and so,
+  // aborting on exception is disabled and we continue execution.
+  // Unfortunately, this triggers a "use after scope" memory access error
+  // when finally "Test R" goes out of scope and tries to unsubsribe from D
```
Comment (bangerth) [inline tests/base/reference.cc]: unsubscribe

File: tests/base/reference.cc [hunk 3]
```diff
@@ -94,9 +117,21 @@ main()
...
+  // that already got destructed.
+  //
+  // Work around this issue by creating a sentinel that gets destructed
```
Comment (bangerth) [inline tests/base/reference.cc]: destroyed
