### PR TITLE
Initialize member variables in class ExceptionBase.

### LINKED ISSUE #3379: Static analysis: dealii-git/source/base/exceptions.cc
```
dealii-git/source/base/exceptions.cc	63	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: raw_stacktrace.
dealii-git/source/base/exceptions.cc	77	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: raw_stacktrace.
```

We should address these warnings and errors from the static analysis tool PVS. In response to #3342.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #3379.

### CODE REVIEW

File: source/base/exceptions.cc [hunk 1]
```diff
@@ -70,7 +70,12 @@ ExceptionBase::ExceptionBase ()
   stacktrace (NULL),
   n_stacktrace_frames (0),
   what_str("")
-{}
+{
+#ifdef DEAL_II_HAVE_GLIBC_STACKTRACE
+  for (unsigned int i=0; i<sizeof(raw_stacktrace)/sizeof(raw_stacktrace[0]); ++i)
+    raw_stacktrace[0] = NULL;
```
Comment (bangerth) [inline source/base/exceptions.cc]: Ah, I was too slow pushing my correction :-( It should of course have read `[i]`...
