### PR TITLE
Fix face domination between FE_Q and FE_DGQ.

### LINKED ISSUE #2155: Crash with face domination
The attached program, reported on the mailing list by Korosh Taebi, crashes as follows:

```
-0.75 -0.75     0
-0.25 -0.75     0
-0.75 -0.25     0
-0.25 -0.25     1
0.25 -0.75      0
0.75 -0.75      0
0.25 -0.25      1
0.75 -0.25      0
-0.75 0.25      0
-0.25 0.25      1
-0.75 0.75      0
-0.25 0.75      0
0.25 0.25       1
0.75 0.25       0
0.25 0.75       0
0.75 0.75       0

--------------------------------------------------------
An error occurred in line <879> of file </home/bangerth/p/deal.II/1/dealii/source/fe/fe_q_base.cc> in function
    dealii::FiniteElementDomination::Domination dealii::FE_Q_Base<PolynomialType, dim, spacedim>::compare_for_face_domination(const dealii::FiniteElement<dim, spacedim>&) const [with PolynomialType = dealii::TensorProductPolynomials<2>; int dim = 2; int spacedim = 2]
The violated condition was: 
    false
The name and call sequence of the exception was:
    ExcNotImplemented()
Additional Information: 
You are trying to use functionality in deal.II that is currently not implemented. In many cases, this indicates that there simply didn't appear much of a need for it, or that the author of the original code did not have the time to implement a particular case. If you hit this exception, it is therefore worth the time to look into the code to find out whether you may be able to implement the missing functionality. If you do, please consider providing a patch to the deal.II development sources (see the deal.II website on how to contribute).

Stacktrace:
-----------
#0  /home/bangerth/p/deal.II/1/install/lib/libdeal_II.g.so.8.4.0-pre: dealii::FE_Q_Base<dealii::TensorProductPolynomials<2, dealii::Polynomials::Polynomial<double> >, 2, 2>::compare_for_face_domination(dealii::FiniteElement<2, 2> const&) const
#1  /home/bangerth/p/deal.II/1/install/lib/libdeal_II.g.so.8.4.0-pre: dealii::FESystem<2, 2>::compare_for_face_domination(dealii::FiniteElement<2, 2> const&) const
#2  /home/bangerth/p/deal.II/1/install/lib/libdeal_II.g.so.8.4.0-pre: unsigned int dealii::internal::hp::get_most_dominating_fe_index<2, 2, dealii::TriaIterator<dealii::DoFAccessor<1, dealii::hp::DoFHandler<2, 2>, false> > >(dealii::TriaIterator<dealii::DoFAccessor<1, dealii::hp::DoFHandler<2, 2>, false> > const&)
#3  /home/bangerth/p/deal.II/1/install/lib/libdeal_II.g.so.8.4.0-pre: dealii::hp::DoFHandler<2, 2>::compute_line_dof_identities(std::vector<unsigned int, std::allocator<unsigned int> >&) const
#4  /home/bangerth/p/deal.II/1/install/lib/libdeal_II.g.so.8.4.0-pre: dealii::hp::DoFHandler<2, 2>::distribute_dofs(dealii::hp::FECollection<2, 2> const&)
#5  ./step-1: MixedFE::MixedFECollection<2>::run()
```

### PR DESCRIPTION
**Pull request by bangerth**
Right now, one got an answer if one asked the FE_DGQ whether or not
it dominates the FE_Q, but not the other way around. Make this symmetric.

While there, also include FE_DGP in the test.

Fixes #2155.

### CODE REVIEW

File: source/fe/fe_q_base.cc [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // ---------------------------------------------------------------------
 //
-// Copyright (C) 2000 - 2015 by the deal.II authors
+// Copyright (C) 2000 - 2015, 2017 by the deal.II authors
```
Comment (kronbichler) [inline source/fe/fe_q_base.cc]: Please adjust years.

Comment (bangerth) [inline source/fe/fe_q_base.cc]: Already done before you even noticed it :-)
