### PR TITLE
Fix querying time steps in ARKODE.

### LINKED ISSUE #17094: Fix ARKODE::solve_ode() return value.
@jdannberg asked me what `ARKODE::solve_ode()` returns given that it is documented as 
```
    /**
     * Integrate the initial value problem. This function returns the final
     * number of computed steps.
     *
     * @param solution On input, this vector contains the initial condition. On
     *   output, it contains the solution at the final time.
     */
    unsigned int
    solve_ode(VectorType &solution);
```
But I *believe* that internally it really only returns how many times we have called `DiscreteTime::advance()`, which tracks how many *intermediate time points* we have hit, not how many time steps were taken. We should fix this.

@luca-heltai FYI.

### PR DESCRIPTION
**Pull request by bangerth**
We did not query ARKode for the number of time steps, but the `DiscreteTime` object for how many times the time has been advanced. These two things are different.

Fixes #17094.

### CODE REVIEW

**Comment by bangerth** [comment]
I realized that the same bug also exists in the IDA interfaces. I've pushed commits to fix that too.

File: tests/sundials/ida_01_n_timesteps.cc [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+#include <deal.II/lac/full_matrix.h>
+#include <deal.II/lac/vector.h>
+
+#include <deal.II/sundials/ida.h>
+
+#include "../tests.h"
+
+
+/**
+ * Like the base test, but output the number of time steps performed.
```
Comment (tjhei) [inline tests/sundials/ida_01_n_timesteps.cc:26]: Is the only change to the last test that you add a print statement that shows the number of steps performed (that's what it looked like)? If that is the case, would you mind just extending the existing test? No reason to duplicate computational time and files.

**Review by tjhei — APPROVED** [review]

File: tests/sundials/ida_01_n_timesteps.cc (hunk 1 above)
Comment (bangerth) [reply tests/sundials/ida_01_n_timesteps.cc:26]: I also reduce the amount of output. It's a separate piece of functionality to test the number of time steps, so I thought that in the spirit of unit tests it gets its own test. I don't feel strongly about it, though. Your call.

**Review by masterleinad — APPROVED** [review]

File: tests/sundials/ida_01_n_timesteps.cc (hunk 1 above)
Comment (tjhei) [reply tests/sundials/ida_01_n_timesteps.cc:26]: Like I said. I think it is wasteful (cpu presources, future maintenance cost) to add a test instead of adding a single print statement to an existing test.

**Comment by bangerth** [comment]
Sounds good. I've updated the existing tests and removed the new ones again.

**Review by gassmoeller — APPROVED** [review]
Looks good to me. Thank you.
