### PR TITLE
Fix mapping fe field similarity

### LINKED ISSUE #9757: Test matrix_free/matrix_vector_faces_28.debug fails
As already mentioned in https://github.com/dealii/dealii/pull/9688#issue-391423160, the test fails for me on an Intel Broadwell server node.

The output I get is:
```
DEAL:2d::Degree of element: 1
DEAL:2d::Norm of difference:           4.87e-16
DEAL:2d::Norm of difference no update: 0.0157
DEAL:2d::Norm of difference w update:  0.000202
DEAL:2d::Degree of element: 2
DEAL:2d::Norm of difference:           1.92e-15
DEAL:2d::Norm of difference no update: 0.00672
DEAL:2d::Norm of difference w update:  2.50e-15
DEAL:3d::Degree of element: 1
DEAL:3d::Norm of difference:           1.88e-16
DEAL:3d::Norm of difference no update: 5.11e-05
DEAL:3d::Norm of difference w update:  1.88e-16
DEAL:3d::Degree of element: 2
DEAL:3d::Norm of difference:           1.06e-16
DEAL:3d::Norm of difference no update: 5.82e-05
DEAL:3d::Norm of difference w update:  1.06e-16
```

The expected output is:
```
DEAL:2d::Degree of element: 1
DEAL:2d::Norm of difference:           4.87e-16
DEAL:2d::Norm of difference no update: 0.0179
DEAL:2d::Norm of difference w update:  4.87e-16
DEAL:2d::Degree of element: 2
DEAL:2d::Norm of difference:           1.92e-15
DEAL:2d::Norm of difference no update: 0.00672
DEAL:2d::Norm of difference w update:  2.50e-15
DEAL:3d::Degree of element: 1
DEAL:3d::Norm of difference:           1.88e-16
DEAL:3d::Norm of difference no update: 5.11e-05
DEAL:3d::Norm of difference w update:  1.88e-16
DEAL:3d::Degree of element: 2
DEAL:3d::Norm of difference:           1.06e-16
DEAL:3d::Norm of difference no update: 5.82e-05
DEAL:3d::Norm of difference w update:  1.06e-16
```

The third and forth line do not match.

### PR DESCRIPTION
**Pull request by kronbichler**
We had the cell similarity detection in `MappingFEField` enabled (in analogy to `MappingQGeneric`), even though we cannot know for an Euler vector whether there really is a similarity. Therefore, we must completely disable this concept in case of a `MappingFEField` and similarily also for `MappingManifold`.

Fixes #9757

### CODE REVIEW

**Comment by kronbichler** [comment]
The diff is best watched without whitespace,
https://github.com/dealii/dealii/pull/9769/files?diff=unified&w=1

File: doc/news/changes/minor/20200330MartinKronbichler [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Fixed: FEValues would previously detect cell similarities when combined with
+MappingFEField when the underlying mesh had similarities, even though the
+deformed cells did not. This would lead to wrong Jacobians and transformed
+shape function gradients, among others, when running deal.II without threads.
+This is now fixed.
```
Comment (bangerth) [inline doc/news/changes/minor/20200330MartinKronbichler]: Can you update that the same fix applies to `MappingManifold` (since you also do this in this patch)?

File: source/fe/mapping_fe_field.cc [hunk 2]
```diff
@@ -729,58 +728,50 @@ namespace internal
...
-                      {
-                        unsigned int comp_k =
-                          fe.system_to_component_index(k).first;
-                        if (fe_mask[comp_k])
-                          result[fe_to_real[comp_k]] +=
-                            data.local_dof_values[k] * data_derv[k];
-                      }
+                for (unsigned int k = 0; k < data.n_shape_functions; ++k)
+                  {
+                    unsigned int comp_k = fe.system_to_component_index(k).first;
```
Comment (bangerth) [inline source/fe/mapping_fe_field.cc]:
```suggestion
                    const unsigned int comp_k = fe.system_to_component_index(k).first;
```

File: source/fe/mapping_fe_field.cc [hunk 3]
```diff
@@ -1122,40 +1086,36 @@ namespace internal
...
-                      }
+                DerivativeForm<4, dim, spacedim> result;
 
-                    // never touch any data for j,l,m,n=dim in case
-                    // dim<spacedim, so it will always be zero as it was
-                    // initialized
-                    for (unsigned int i = 0; i < spacedim; ++i)
+                for (unsigned int k = 0; k < data.n_shape_functions; ++k)
+                  {
+                    unsigned int comp_k = fe.system_to_component_index(k).first;
```
Comment (bangerth) [inline source/fe/mapping_fe_field.cc]: While you're there:
```suggestion
                    const unsigned int comp_k = fe.system_to_component_index(k).first;
```

File: source/fe/mapping_fe_field.cc [hunk 4]
```diff
@@ -1190,100 +1149,99 @@ namespace internal
...
-                                    (fourth[k][j][l][m][n] *
-                                     data.local_dof_values[k]);
-                      }
-
-                    // push-forward the j-coordinate
-                    for (unsigned int i = 0; i < spacedim; ++i)
-                      for (unsigned int j = 0; j < spacedim; ++j)
+                for (unsigned int k = 0; k < data.n_shape_functions; ++k)
+                  {
+                    unsigned int comp_k = fe.system_to_component_index(k).first;
```
Comment (bangerth) [inline source/fe/mapping_fe_field.cc]:
```suggestion
                    const unsigned int comp_k = fe.system_to_component_index(k).first;
```

**Comment by kronbichler** [comment]
> Since you're also changing `MappingManifold`, do you want to add a similar test for that class as well?

To be honest, I don't know a good way of how to construct a proper manifold that would trigger this. Let me make a short test with a spherical manifold in 2d.

**Comment by kronbichler** [comment]
It turned out that it was not too complicated to get that test - just take a refined hyper cube and let the edges be deformed differently with `MappingManifold`. Cells are similar but the deformed shapes are not.
I have pushed this test, alongside with the proposed updates.
