### PR TITLE
Step-75: use well-formed deleter

### LINKED ISSUE #13613: compilation issue step-75 on ARM clang 13
```
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/allocator.h:154:28: error: no matching constructor for initialization of 'std::shared_ptr<const dealii::Triangulation<2, 2>>'

        ::new ((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);

                           ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/allocator_traits.h:290:13: note: in instantiation of function template specialization 'std::allocator<std::shared_ptr<const dealii::Triangulation<2, 2>>>::construct<std::shared_ptr<const dealii::Triangulation<2, 2>>, dealii::Triangulation<2, 2> *, (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9)>' requested here

        __a.construct(__p, _VSTD::forward<_Args>(__args)...);

            ^

/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/vector:948:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::shared_ptr<const dealii::Triangulation<2, 2>>>>::construct<std::shared_ptr<const dealii::Triangulation<2, 2>>, dealii::Triangulation<2, 2> *, (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9), void>' requested here

    __alloc_traits::construct(this->__alloc(), _VSTD::__to_address(__tx.__pos_),

                    ^

/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/vector:1706:9: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<const dealii::Triangulation<2, 2>>>::__construct_one_at_end<dealii::Triangulation<2, 2> *, (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9)>' requested here

        __construct_one_at_end(_VSTD::forward<_Args>(__args)...);

        ^

/Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:671:34: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<const dealii::Triangulation<2, 2>>>::emplace_back<dealii::Triangulation<2, 2> *, (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9)>' requested here

      coarse_grid_triangulations.emplace_back(

                                 ^

/Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:1239:5: note: in instantiation of function template specialization 'Step75::solve_with_gmg<dealii::LinearAlgebra::distributed::Vector<double>, Step75::LaplaceOperator<2, double>, 2>' requested here

    solve_with_gmg(solver_control,

    ^

/Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:1473:9: note: in instantiation of member function 'Step75::LaplaceProblem<2>::solve_system' requested here

        solve_system();

        ^

/Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:1506:23: note: in instantiation of member function 'Step75::LaplaceProblem<2>::run' requested here

      laplace_problem.run();

                      ^

/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:469:26: note: candidate constructor template not viable: no known conversion from 'dealii::Triangulation<2, 2> *' to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument

    template <class _Dp> shared_ptr(nullptr_t __p, _Dp __d);

                         ^

/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:464:9: note: candidate template ignored: requirement '__shared_ptr_deleter_ctor_reqs<(lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9), dealii::Triangulation<2, 2>, const dealii::Triangulation<2, 2>>::value' was not satisfied [with _Yp = dealii::Triangulation<2, 2>, _Dp = (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9)]

        shared_ptr(_Yp* __p, _Dp __d,
```

problematic line:
https://github.com/dealii/dealii/blob/e6779913e7f770652da442b3c2460dec3e864029/examples/step-75/step-75.cc#L673

relevant error:
```
shared_ptr.h:464:9: note: candidate template ignored: requirement '__shared_ptr_deleter_ctor_reqs<(lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9), dealii::Triangulation<2, 2>, const dealii::Triangulation<2, 2>>::value' was not satisfied [with _Yp = dealii::Triangulation<2, 2>, _Dp = (lambda at /Users/heister/libs-candi-master-v5/tmp/unpack/deal.II-master/examples/step-75/step-75.cc:673:9)]

        shared_ptr(_Yp* __p, _Dp __d,
```

### PR DESCRIPTION
**Pull request by tamiko**
LLVM/Clang's libc++ library version 13/14 got stricter by checking
requirements of the deleter, in particular, according to [1] a deleter
must pass the requirement `__shared_ptr_deleter_ctor_reqs` which is
defined as follows:
```
template <class _Dp, class _Pt, class = decltype(declval<_Dp>()(declval<_Pt>()))>
static true_type __well_formed_deleter_test(int);

template <class, class>
static false_type __well_formed_deleter_test(...);

template <class _Dp, class _Pt>
struct __well_formed_deleter : decltype(__well_formed_deleter_test<_Dp, _Pt>(0)) {};

template<class _Dp, class _Tp, class _Yp>
struct __shared_ptr_deleter_ctor_reqs
{
    static const bool value = __compatible_with<_Tp, _Yp>::value &&
                              is_move_constructible<_Dp>::value &&
                              __well_formed_deleter<_Dp, _Tp*>::value;
};
```
Unfortunately, our construct
```
coarse_grid_triangulations.emplace_back(
  const_cast<Triangulation<dim> *>(&(dof_handler.get_triangulation())),
  [](auto &) {});
```
does not pass this test. The issue is that the deleter takes a pointer,
not a reference which, so the lambda `[](auto &){}` does not pass above
`__shared_ptr_deleter_ctor_reqs`.

While at it, remove the const cast: `coarse_grid_triangulations` is
declared as a vector holding a `shared_ptr<const Triangulation<dim>>`,
thus we should simply take the address and not convert to a non-const
object.

Fixes
  https://cdash.dealii.43-1.org/viewBuildError.php?buildid=1614
  https://cdash.dealii.43-1.org/viewBuildError.php?buildid=1613

[1] https://github.com/llvm/llvm-project/blob/main/libcxx/include/__memory/shared_ptr.h

Closes #13613

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]
This should fix https://github.com/dealii/dealii/issues/13613, right?

**Comment by tamiko** [comment]
@marcfehling yes. I wasn't aware of the issue.

File: examples/step-75/step-75.cc [hunk 1]
```diff
@@ -669,8 +669,7 @@ namespace Step75
           dof_handler.get_triangulation());
     else
       coarse_grid_triangulations.emplace_back(
-        const_cast<Triangulation<dim> *>(&(dof_handler.get_triangulation())),
-        [](auto &) {});
+        &(dof_handler.get_triangulation()), [](auto) {});
```
Comment (tamiko) [inline examples/step-75/step-75.cc:672]: We could switch to `auto *` if this is deemed to be more elegant. @marcfehling @peterrum

Comment (peterrum) [reply examples/step-75/step-75.cc:672]: Let's do it consistently: https://github.com/dealii/dealii/blob/e6779913e7f770652da442b3c2460dec3e864029/include/deal.II/multigrid/mg_transfer_global_coarsening.templates.h#L2377-L2378

Comment (tamiko) [reply examples/step-75/step-75.cc]: Fixed.

**Review by peterrum — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]
