### PR TITLE
Fix ThreadLocalStorage assigment operators

### LINKED ISSUE #11587: Potential bug in ThreadLocalStorage
We are using `dealii::ThreadLocalStorage<T>` in our project and have had some issues with this class recently.

I think there might be a bug in `dealii::ThreadLocalStorage`. The copy assignment https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L330 and  and the move assignment https://github.com/dealii/dealii/blob/master/include/deal.II/base/thread_local_storage.h#L344 both do not copy/move the `exemplar` member, which is used for constructing new copies for other threads. Additionally, the copy and move constructors do copy/move `exemplar`. I would assume that constructor and assign should "do the same thing".

I am missing something or is this really a bug? Thanks for your help!

### PR DESCRIPTION
**Pull request by nmuch**
The copy and move assignment operators must also copy/move the `exemplar` in case the `data` is still empty.

Closes #11587

### CODE REVIEW

**Review by bangerth — COMMENTED** [review]
Good work! Thanks for taking this on!

Do you think you could write a short test that checks that this works now? Take a look at some of the `tests/multithreading/thread_local_storage_*` tests.

**Comment by nmuch** [comment]
I added tests that check if the `exemplar` is copied/moved by the respective assignment operators of `ThreadLocalStorage`. Without the exemplar the threads would create new instances of `X` instead of copying them and the tests fail.

**Review by peterrum — APPROVED** [review]

File: tests/multithreading/thread_local_storage_08.cc [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+struct X
+{
+  X()
+  {
+    deallog << "Creating" << std::endl;
+  };
+  X(const X &)
+  {
+    deallog << "Copying" << std::endl;
+  };
```
Comment (masterleinad) [inline tests/multithreading/thread_local_storage_08.cc:35]:
```suggestion
  X(X &&)
  {
    deallog << "Moving" << std::endl;
  };
```

File: tests/multithreading/thread_local_storage_08.cc [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+// it, and/or modify it under the terms of the GNU Lesser General
+// Public License as published by the Free Software Foundation; either
+// version 2.1 of the License, or (at your option) any later version.
+// The full text of the license can be found in the file LICENSE.md at
+// the top level directory of deal.II.
+//
+// ---------------------------------------------------------------------
+
+
+// test if ThreadLocalStorage::operator= (const ThreadLocalStorage<T> &&t) moves
```
Comment (masterleinad) [inline tests/multithreading/thread_local_storage_08.cc:17]:
```suggestion
// test if ThreadLocalStorage::operator= (ThreadLocalStorage<T> &&t) moves
```

File: tests/multithreading/thread_local_storage_08.output [hunk 3]
```diff
@@ -0,0 +1,8 @@
+
+DEAL::Creating
+DEAL::Copying
+DEAL::Copying
+DEAL::Copying
+DEAL::Copying
+DEAL::Copying
+DEAL::Copying
```
Comment (masterleinad) [inline tests/multithreading/thread_local_storage_08.output:8]:
```suggestion
DEAL::Moving
DEAL::Moving
DEAL::Moving
DEAL::Moving
DEAL::Moving
DEAL::Moving
```

**Review by masterleinad — CHANGES_REQUESTED** [review]
I think you wanted to check the move assignemt operator in the last test.

File: tests/multithreading/thread_local_storage_08.cc (hunk 1 above)
Comment (nmuch) [reply tests/multithreading/thread_local_storage_08.cc:35]: I want to test the move assignment of `ThreadLocalStorage` which does not move the `exemplar`. It moves a shared pointer to the `exemplar` which does not move the instance of `X`.

File: tests/multithreading/thread_local_storage_08.output (hunk 3 above)
Comment (nmuch) [reply tests/multithreading/thread_local_storage_08.output:8]: The `exemplar` is used to copy its value into the thread-local `data` if `data` is still empty on a thread. If the `exemplar` is empty, new instances of `X` are constructed instead, using the default ctor.

Without the bugfix in this PR the `exemplar` is not copied/moved and the threads in this test would "create" new instances of `X` instead of copy-constructing them.

File: tests/multithreading/thread_local_storage_08.cc (hunk 2 above)
Comment (nmuch) [reply tests/multithreading/thread_local_storage_08.cc]: Thank you for the correction. I changed the comment so it says that `ThreadLocalStorage::operator=(ThreadLocalStorage<T> &&t=` moves the shared pointer to the exemplar and not the exemplar directly.

File: tests/multithreading/thread_local_storage_08.cc (hunk 1 above)
Comment (masterleinad) [reply tests/multithreading/thread_local_storage_08.cc:35]: Yes, I didn't look carefully enough.

**Review by masterleinad — APPROVED** [review]
