### PR TITLE
Fix and enable compression of hp DoF indices.

### LINKED ISSUE #3728: internal::hp::DoFLevel::uncompress_data is a no-op
This function currently does nothing since it starts with a return statement:

```cpp
template <int dim, int spacedim>
void
DoFLevel::uncompress_data(const dealii::hp::FECollection<dim,spacedim> &fe_collection)
{
  return;

  if (dof_offsets.size() == 0 || dof_indices.size()==0)
    return;

  // in a first run through, count how many new slots we need in the
  // dof_indices array after uncompression.
  unsigned int new_size = 0;
  for (unsigned int cell=0; cell<dof_offsets.size(); ++cell)
    if (dof_offsets[cell] != (offset_type)(-1))
      {
        // we know now that the slot for this cell is used. extract the
        // active_fe_index for it and see how many entries we need
        new_size += fe_collection[active_fe_index(cell)].template n_dofs_per_object<dim>();
      }
  [...]
```

We should determine whether or not we want to keep it: this function was added in late 2013 and has always been a no-op.

This was also found by cppcheck.

### PR DESCRIPTION
**Pull request by bangerth**
A previous patch, a long time ago, implemented a scheme to compress the data structure
that stores the DoF indices in the hp case. For reasons no longer clear, the functions
that do the compression and decompression just returned immediately, without actually
doing anything (see #3728). Maybe not surprisingly, the algorithm -- not executed after all -- did
not work.

This patch fixes the algorithm at various locations and enables the compression. To understand what the algorithm actually does, consider this comment from the class docs of `hp::DoFLevel`:
```
     * <h3>Compression</h3>
     *
     * It is common for the indices stored in @p dof_indices for one cell to
     * be numbered consecutively. For example, using the standard numbering
     * (without renumbering DoFs), the quad dofs on the first cell of a mesh
     * when using a $Q_3$ element will be numbered <tt>12, 13, 14, 15</tt>.
     * This allows for compression if we only store the first entry and have
     * some way to mark the DoFs on this object as compressed. Here,
     * compression means that we know that subsequent DoF indices can be
     * obtained from the previous ones by just incrementing them by one -- in
     * other words, we use a variant of doing run-length encoding. The way to
     * do this is that we use positive FE indices for uncompressed sets of
     * DoFs and if a set of indices is compressed, then we instead store the
     * FE index in binary complement (which we can identify by looking at the
     * sign bit when interpreting the number as a signed one). There are two
     * functions, compress_data() and uncompress_data() that convert between
     * the two possible representations.
     *
     * Note that compression is not always possible. For example, if one
     * renumbered the example above using DoFRenumbering::downstream with
     * $(1,0)^T$ as direction, then they would likely be numbered <tt>12, 14,
     * 13, 15</tt>, which can not be compressed using run-length encoding.
```

Passes the entire testsuite. Fixes #3728 .

### CODE REVIEW

**Comment by bangerth** [comment]
Just for the record, running this compression on step-27 leads to the following numbers for the compression of the `dof_indices` array, with numbers before->after (for each level of the mesh; later cycles obviously have more levels):
```
Cycle 0:
*** Compression: 768 -> 768

Cycle 1:
*** Compression:  264 -> 264
*** Compression: 1197 -> 702

Cycle 2:
*** Compression:    1 -> 1
*** Compression:  140 -> 140
*** Compression:  954 -> 329
*** Compression: 1692 -> 673

Cycle 3:
*** Compression:    5 -> 2
*** Compression:  116 -> 116
*** Compression:  565 -> 187
*** Compression: 1786 -> 406
*** Compression: 2044 -> 645


Cycle 4:
*** Compression:    8 -> 2
*** Compression:  132 -> 132
*** Compression:  503 -> 151
*** Compression: 1496 -> 258
*** Compression: 2483 -> 621
*** Compression: 2545 -> 480

Cycle 5:
*** Compression:    8 -> 2
*** Compression:   80 -> 80
*** Compression:  322 -> 112
*** Compression:  836 -> 151
*** Compression: 1818 -> 266
*** Compression: 2883 -> 502
*** Compression: 3414 -> 615
```

**Comment by bangerth** [comment]
And this is step-46, the other program that uses hp:
```
Refinement cycle 0
*** Compression: 80 -> 40

Refinement cycle 1
*** Compression:  36 -> 18
*** Compression: 176 -> 88

Refinement cycle 2
*** Compression: 208 -> 104
*** Compression: 448 -> 224

Refinement cycle 3
*** Compression:  64 -> 32
*** Compression: 784 -> 392
*** Compression: 960 -> 480

Refinement cycle 4
*** Compression:  512 -> 256
*** Compression:  768 -> 384
*** Compression: 1920 -> 960

Refinement cycle 5
*** Compression:  496 -> 248
*** Compression:  576 -> 288
*** Compression: 2032 -> 1016
*** Compression: 2592 -> 1296
```
The compression appears to be exactly a factor of two here.

File: source/hp/dof_level.cc [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // ---------------------------------------------------------------------
 //
-// Copyright (C) 2003 - 2015 by the deal.II authors
+// Copyright (C) 2003 - 2015, 2017 by the deal.II authors
```
Comment (Rombur) [inline source/hp/dof_level.cc]: date

File: include/deal.II/hp/dof_level.h [hunk 2]
```diff
@@ -296,15 +317,16 @@ namespace internal
...
-      // been allocated at all
+      // make sure we are on an object for which DoFs have been
+      // allocated at all
       Assert (dof_offsets[obj_index] != (offset_type)(-1),
               ExcMessage ("You are trying to access degree of freedom "
                           "information for an object on which no such "
                           "information is available"));
 
-      Assert (fe_index == active_fe_indices[obj_index],
+      Assert (fe_index == ((signed_active_fe_index_type)active_fe_indices[obj_index]>=0 ?
```
Comment (Rombur) [inline include/deal.II/hp/dof_level.h]: These three lines confuse me. What are you doing here? `active_fe_indices` is `unsigned` you cast it to a `signed` and check that it is not negative but this could only happened if the `active_fe_indices[obj_index]` is large, right? Can't you just check the value of `active_fe_indices[obj_index]` directly?

File: include/deal.II/hp/dof_level.h [hunk 3]
```diff
@@ -296,15 +317,16 @@ namespace internal
...
+                           active_fe_indices[obj_index] :
+                           (active_fe_index_type)~(signed_active_fe_index_type)active_fe_indices[obj_index]),
```
Comment (Rombur) [inline include/deal.II/hp/dof_level.h]: Why do you this? If I understand correctly, you cast to a `signed`, flip all the bits, and then recast to a `unsigned`.

File: source/hp/dof_level.cc [hunk 4]
```diff
@@ -196,8 +197,14 @@ namespace internal
                 // apparently so. uncompress
                 Assert (next_offset-dof_offsets[cell] == 1,
                         ExcInternalError());
-                for (unsigned int i=0; i<fe_collection[active_fe_indices[cell]].template n_dofs_per_object<dim>(); ++i)
+                const unsigned int dofs_per_object
+                  = fe_collection[(active_fe_index_type)~(signed_active_fe_index_type)active_fe_indices[cell]]
```
Comment (Rombur) [inline source/hp/dof_level.cc]: Can you create a function for this cast/bit flips that you are doing and give it a name that explains what it does.

**Comment by bangerth** [comment]
Let's if you like this version better :-)

**Comment by bangerth** [comment]
As an aside, there are about 500 tests that have "hp" in their name. While developing this patch, whenever something didn't work, it usually wrecked a couple dozen tests. So I figure that there is adequate testsuite coverage. (Not surprisingly, since this is the central data structure of `hp::DoFHandler` I'm touching here.)
