### PR TITLE
Make sure distribute_dofs doesn't copy unnecessarily

### LINKED ISSUE #5715: Bug using MappingFEField and refinements
Working with @luca-heltai we discover that the following code fails. We don't know yet who or what introduced this issue. The code fails because the subscriptor of gradient_dh, which is needed from MappingFEField, is not zero when the second distribute_dofs comes in place. With version 8.5 the code is functioning just fine.

```
#include <deal.II/base/utilities.h>
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/geometry_info.h>
#include<deal.II/dofs/dof_handler.h>
#include<deal.II/dofs/dof_accessor.h>
#include<deal.II/dofs/dof_tools.h>
#include<deal.II/fe/fe_q.h>
#include<deal.II/fe/fe_values.h>
#include<deal.II/fe/fe_system.h>
#include<deal.II/fe/mapping_q1_eulerian.h>
#include<deal.II/fe/mapping_q1.h>
#include <deal.II/fe/mapping_fe_field.h>
#include <deal.II/grid/grid_generator.h>
#include<deal.II/numerics/vector_tools.h>

using namespace dealii;
int main()
{


  Triangulation<2> tria;
  GridGenerator::hyper_cube (tria);
  tria.refine_global (1);
  FE_Q<2> fe(1);
  FESystem<2> gradient_fe(FE_Q<2> (1),1,FE_Q<2> (1),1);
  DoFHandler<2,2> dh(tria);
  DoFHandler<2,2> gradient_dh(tria);
  dh.distribute_dofs(fe);
  gradient_dh.distribute_dofs(gradient_fe);
  std::cout<<tria.n_active_cells()<<" "<<dh.n_dofs()<<std::endl;
  Vector<double> map_vector;
  map_vector.reinit(gradient_dh.n_dofs());
  VectorTools::get_position_vector(gradient_dh, map_vector);
  MappingFEField<2, 2> mapping(gradient_dh, map_vector);
  tria.refine_global (1);
  dh.distribute_dofs(fe);
  gradient_dh.distribute_dofs(gradient_fe);
  std::cout<<tria.n_active_cells()<<" "<<dh.n_dofs()<<std::endl;
}
```

### PR DESCRIPTION
**Pull request by masterleinad**
Relates to #5715.

### CODE REVIEW

File: source/dofs/dof_handler.cc [hunk 1]
```diff
@@ -997,7 +997,10 @@ void DoFHandler<dim,spacedim>::distribute_dofs (const FiniteElement<dim,spacedim
   Assert (tria->n_levels() > 0,
           ExcMessage("The Triangulation you are using is empty!"));
 
-  fe_collection = std_cxx14::make_unique<hp::FECollection<dim, spacedim>>(ff);
+  // Only recreate the FECollection if we don't already store an instance
+  // of the FiniteElement class given.
+  if (fe_collection == nullptr || typeid((*fe_collection)[0]) != typeid(ff))
```
Comment (bangerth) [inline source/dofs/dof_handler.cc]: that's not good enough. You wouldn't be able to distinguish `FE_Q(1)` from `FE_Q(2)` this way.

I think you want to just compare the actual pointers. I.e., if someone calls
```
  dof_handler.distribute_dofs (dof_handler.get_fe());
```
then avoid the cloning. That's in essence what @luca-heltai is trying to do, after all.

File: source/hp/dof_handler.cc [hunk 2]
```diff
@@ -1286,7 +1286,18 @@ namespace hp
     Assert (tria->n_levels() > 0,
             ExcMessage("The Triangulation you are using is empty!"));
 
-    finite_elements = &ff;
+    // Only recreate the FECollection if we don't already store an instance
+    // that constains the same FiniteElement objects.
+    bool create = true;
+    if (fe_collection != nullptr && fe_collection->size() == ff.size())
+      for (unsigned int i=0; i<fe_collection->size(); ++i)
+        if (typeid((*fe_collection)[i]) != typeid(ff[i]))
```
Comment (bangerth) [inline source/hp/dof_handler.cc]: same here. you can probably just compare the addresses of the collections.

File: source/hp/dof_handler.cc [hunk 3]
```diff
@@ -1286,7 +1286,18 @@ namespace hp
     Assert (tria->n_levels() > 0,
             ExcMessage("The Triangulation you are using is empty!"));
 
-    finite_elements = &ff;
+    // Only recreate the FECollection if we don't already store an instance
+    // that constains the same FiniteElement objects.
```
Comment (bangerth) [inline source/hp/dof_handler.cc]: I don't actually understand the logic here -- the class *already* only stores a reference/pointer to the object owned by user code. All you do here is possibly resetting a pointer, which is so cheap that it's not worth checking.
