### PR TITLE
Tests: Make base/timer_03 test more robust

### LINKED ISSUE #4439: base/timer_03.release unstable
On a run with slightly higher load [1]:
```
base/timer_03.release: DIFF failed. ------ First 50 lines diff output:
*** /srv/testsuite/dealii/tests/base/timer_03.output	Sat May 27 18:11:26 2017
--- output	Mon May 29 17:05:35 2017
***************
*** 3,8 ****
  DEAL::OK
  DEAL::OK
  DEAL::OK
! DEAL::OK
  DEAL::OK
  DEAL::OK
--- 3,8 ----
  DEAL::OK
  DEAL::OK
  DEAL::OK
! DEAL::Ratio 0.666667 should be 1.00000
  DEAL::OK
  DEAL::OK
```

[1] https://cdash.kyomu.43-1.org/testDetails.php?test=24812856&build=7589

### PR DESCRIPTION
**Pull request by tamiko**
Closes #4439

### CODE REVIEW

**Comment by tamiko** [comment]
@class4kayaker Please have a look.

File: tests/base/timer_03.cc [hunk 1]
```diff
@@ -79,30 +79,36 @@ int main ()
...
+
+  if (wall_times["Section1"] * wall_times["Section2"] > 0.)
+    deallog << "OK" << std::endl;
+  else
+    deallog << "ERROR - total wall time 0" << std::endl;
 
   compare (cpu_times["Section1"],cpu_times["Section2"],1.);
-  compare (cpu_times["Section1"],cpu_times["Section3"],2.);
-  compare (cpu_times["Section3"],cpu_times["Section4"],1.);
+  compare (wall_times["Section1"],wall_times["Section2"],1.);
```
Comment (tamiko) [inline tests/base/timer_03.cc]: @class4kayaker: These two comparisons should be numerically identical regardless of current CPU clock speed, scheduling, etc.

File: tests/base/timer_03.cc [hunk 2]
```diff
@@ -79,30 +79,36 @@ int main ()
...
+  tO.exit_section("Section1");
 
-  std::map<std::string, double> cpu_times = tO.get_summary_data(TimerOutput::OutputData::total_cpu_time);
-  std::map<std::string, double> calls = tO.get_summary_data(TimerOutput::OutputData::n_calls);
+  std::map<std::string, double> cpu_times =
+      tO.get_summary_data(TimerOutput::OutputData::total_cpu_time);
+  std::map<std::string, double> wall_times =
+      tO.get_summary_data(TimerOutput::OutputData::total_wall_time);
+  std::map<std::string, double> calls =
+      tO.get_summary_data(TimerOutput::OutputData::n_calls);
```
Comment (tamiko) [inline tests/base/timer_03.cc]: @class4kayaker Always a good idea to check for the full interface you implemented. Thus, I added the third variant with `OutputData::total_wall_time` as well. :-)

Comment (class4kayaker) [inline tests/base/timer_03.cc]: I avoided that case due to thinking that it would be far more likely to be fragile, being dependent on the wall clock time.

**Comment by class4kayaker** [comment]
Looks like a reasonable adjustment.

**Comment by tamiko** [comment]
@dealii/dealii *ping* :-)
