### PR TITLE
Fix a memory leak in step-39.

### LINKED ISSUE #3520: Fix memory leak in step-39
step-39 has this code:
```
  template <int dim>
  void InteriorPenaltyProblem<dim>::output_results (const unsigned int cycle) const
  {
    // Output of the solution in gnuplot format.
    char *fn = new char[100];
    sprintf(fn, "sol-%02d", cycle);

    std::string filename(fn);
    filename += ".gnuplot";
    deallog << "Writing solution to <" << filename << ">..."
            << std::endl << std::endl;
    std::ofstream gnuplot_output (filename.c_str());

    DataOut<dim> data_out;
    data_out.attach_dof_handler (dof_handler);
    data_out.add_data_vector (solution, "u");
    data_out.add_data_vector (estimates.block(0), "est");

    data_out.build_patches ();

    data_out.write_gnuplot(gnuplot_output);
  }
```
This leaks the memory allocated for `fn`. I think this might be more elegantly done using an `ostringstream`.

### PR DESCRIPTION
**Pull request by bangerth**
Also avoid some obscure old-style C functions.

Fixes #3520.

### CODE REVIEW

File: examples/step-39/step-39.cc [hunk 1]
```diff
@@ -859,16 +860,18 @@ namespace Step39
...
   template <int dim>
   void InteriorPenaltyProblem<dim>::output_results (const unsigned int cycle) const
   {
-    // Output of the solution in gnuplot format.
-    char *fn = new char[100];
-    sprintf(fn, "sol-%02d", cycle);
+    std::ostringstream filename_stream;
+    filename_stream << "sol-" << Utilities::int_to_string(cycle,2)
+                    << ".gnuplot";
+    const std::string filename = filename_stream.str();
```
Comment (drwells) [inline examples/step-39/step-39.cc]: Since we are left with three strings at the end of the day we could make this a bit simpler by writing
```cpp
const std::string filename = "sol-" + Utilities::to_string(cycle, 2) + ".gnuplot";
```

instead of using the string stream.

Comment (bangerth) [inline examples/step-39/step-39.cc]: Oh, yes, how stupid of me. I started down the road because I wanted to format the cycle number, then remembered that we have `Utilities::int_to_string`, and didn't question any more what I was doing.

**Comment by bangerth** [comment]
Updated patch is now here.
