### PR TITLE
Use a valid communicator.

### LINKED ISSUE #13469: invalid communicator in tests/fullydistributed_grids/repartitioning_05.cc
This happens with MPICH:
```
terminate called after throwing an instance of 'dealii::StandardExceptions::ExcMPI'
  what():  
--------------------------------------------------------
An error occurred in line <132> of file <../source/base/mpi.cc> in function
    unsigned int dealii::Utilities::MPI::this_mpi_process(const MPI_Comm&)
The violated condition was: 
    ierr == MPI_SUCCESS
```
call stack:
```
#2  0x00007fffec39865a in dealii::Utilities::MPI::this_mpi_process (mpi_communicator=@0x7fffffffc5b8: 67108864) at ../source/base/mpi.cc:132
#3  0x00007fffee592090 in dealii::parallel::TriangulationBase<2, 2>::TriangulationBase (this=0x7fffffffc1e0, mpi_communicator=@0x7fffffffc16c: 67108864, 
    smooth_grid=dealii::Triangulation<2, 2>::none, check_for_distorted_cells=false) at ../source/distributed/tria_base.cc:55
#4  0x00007fffee598e5e in dealii::parallel::DistributedTriangulationBase<2, 2>::DistributedTriangulationBase (this=0x7fffffffc1e0, 
    mpi_communicator=@0x7fffffffc16c: 67108864, smooth_grid=dealii::Triangulation<2, 2>::none, check_for_distorted_cells=false)
    at ../source/distributed/tria_base.cc:675
#5  0x00007fffee5467ff in dealii::parallel::distributed::Triangulation<2, 2>::Triangulation (this=0x7fffffffc1e0, mpi_communicator=@0x7fffffffc16c: 67108864, 
    smooth_grid=dealii::Triangulation<2, 2>::none, settings=dealii::parallel::distributed::Triangulation<2, 2>::default_setting)
    at ../source/distributed/tria.cc:1712
#6  0x00005555555b6057 in test<2> (comm=1140850688, n_partitions=1) at /ssd/deal-git/tests/fullydistributed_grids/repartitioning_05.cc:110
#7  0x00005555555ab732 in main (argc=1, argv=0x7fffffffdab8) at /ssd/deal-git/tests/fullydistributed_grids/repartitioning_05.cc:157

```

It looks like we create a tria with MPI_COMM_NULL and this can't work.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #13469.

/rebuild

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks reasonable.

File: tests/fullydistributed_grids/repartitioning_05.cc [hunk 1]
```diff
@@ -109,7 +109,7 @@ test(const MPI_Comm comm, const unsigned int n_partitions)
 
   parallel::distributed::Triangulation<dim> tria(sub_comm);
 
-  if (sub_comm != MPI_COMM_NULL)
+  if (sub_comm != MPI_COMM_SELF)
```
Comment (peterrum) [inline tests/fullydistributed_grids/repartitioning_05.cc:112]: Thanks for tackling this! 

I am not sure if this is equivalent to the previous code: this only works if `MPI_COMM_WORLD` and `MPI_COMM_SELF` are not the same (and if a subcommunicator of size one is not equivalent to `MPI_COMM_SELF`) for a serial execution. Is this the case?

**Comment by bangerth** [comment]
Rebased.

**Review by tamiko — APPROVED** [review]
