### PR TITLE
 Parse boundary_ids in GMSH-4 format  correctly

### LINKED ISSUE #7501: Incorrect assignment of boundary indicators when reading in GMSH-4 meshes
https://groups.google.com/forum/#!topic/dealii/NWe7cCSvP9k reports that boundary indicators are not set correctly for GMSH-4 meshes. The attached [archive](https://github.com/dealii/dealii/files/2644238/test_gmsh_4.tar.gz) shows a failing example.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7501. As already assumed in #7501, we need to parse the `$Entities` section as well.
Looking at the `GMSH-4` description at http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029 this PR should be pretty straight-forward. The description for `$Entities` reads:
```
$Entities
  numPoints(unsigned long) numCurves(unsigned long)
    numSurfaces(unsigned long) numVolumes(unsigned long)
  // points
  tag(int) boxMinX(double) boxMinY(double) boxMinZ(double)
    boxMaxX(double) boxMaxY(double) boxMaxZ(double)
    numPhysicals(unsigned long) physicalTag(int) ...
  ...
  // curves
  tag(int) boxMinX(double) boxMinY(double) boxMinZ(double)
     boxMaxX(double) boxMaxY(double) boxMaxZ(double)
     numPhysicals(unsigned long) physicalTag(int) ...
     numBoundingPoints(unsigned long) tagPoint(int) ...
  ...
  // surfaces
  tag(int) boxMinX(double) boxMinY(double) boxMinZ(double)
    boxMaxX(double) boxMaxY(double) boxMaxZ(double)
    numPhysicals(unsigned long) physicalTag(int) ...
    numBoundingCurves(unsigned long) tagCurve(int) ...
  ...
  // volumes
  tag(int) boxMinX(double) boxMinY(double) boxMinZ(double)
    boxMaxX(double) boxMaxY(double) boxMaxZ(double)
    numPhysicals(unsigned long) physicalTag(int) ...
    numBoundngSurfaces(unsigned long) tagSurfaces(int) ...
  ...
$EndEntities
```
and we use the same variable names below. In the end, we just care for the first `physicalTag` for each `Entity`. In case there is more then one, we simply throw an exception.
For each `Element` `tagEntity` is used as key to find the correct boundary id in the maps defined by `Entities`.

For verifying that everything works correctly, I converted all the GMSH-2 files we use in the testsuite to GMSH-4 files and copied the corresponding tests (if possible). This approach did not succeed for 
`tests/grid/grid_in_msh_version_4` and `tests/grid/grid_in_gmsh_01_v4`. 

In the first case, the cells are in reversed order in the GMSH-2 file as compared to the GMSH-4 file and the lines and faces are swapped as well. Hence, we loop through the cells for one of the triangulations in reverse and create sets for the interesting properties on each of the two corresponding cells and compare these.

In the second case, the numbering of the vertices was different. So we only test that the vertex locations were the same (and then boundary ids for all faces and lines).

### CODE REVIEW

File: source/grid/grid_in.cc [hunk 1]
```diff
@@ -1451,14 +1452,73 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+      // if the next block is of kind $Entities, parse it
       if (line == "$Entities")
         {
-          do
+          unsigned long numPoints, numCurves, numSurfaces, numVolumes,
+            numPhysicals;
+          int    tag, physicalTag;
+          double boxMinX, boxMinY, boxMinZ, boxMaxX, boxMaxY, boxMaxZ;
+
+          in >> numPoints >> numCurves >> numSurfaces >> numVolumes;
```
Comment (drwells) [inline source/grid/grid_in.cc]: It was already like this, but could you convert these to `snake_case` (e.g., `n_points` instead of `numPoints`)?

File: source/grid/grid_in.cc [hunk 2]
```diff
@@ -1451,14 +1452,73 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+                          ExcMessage("More than one tag is not supported!"));
+              for (unsigned int j = 0; j < numPhysicals; ++j)
+                in >> physicalTag;
+              tag_maps[3][tag] = (numPhysicals == 0) ? 0 : physicalTag;
+              in >> numSurfaces;
+              for (unsigned int j = 0; j < numSurfaces; ++j)
+                in >> tag;
             }
-          while (line != "$EndEntities");
+          std::cout << line << std::endl;
```
Comment (drwells) [inline source/grid/grid_in.cc]: remove the `cout` calls :)

File: source/grid/grid_in.cc [hunk 3]
```diff
@@ -1451,14 +1452,73 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+              in >> tag >> boxMinX >> boxMinY >> boxMinZ >> boxMaxX >>
+                boxMaxY >> boxMaxZ >> numPhysicals;
+              AssertThrow(numPhysicals < 2,
+                          ExcMessage("More than one tag is not supported!"));
+              for (unsigned int j = 0; j < numPhysicals; ++j)
+                in >> physicalTag;
+              tag_maps[1][tag] = (numPhysicals == 0) ? 0 : physicalTag;
+              in >> numPoints;
+              for (unsigned int j = 0; j < numPoints; ++j)
+                in >> tag;
```
Comment (drwells) [inline source/grid/grid_in.cc]: Why do we ignore these tags?

File: source/grid/grid_in.cc [hunk 4]
```diff
@@ -1451,14 +1452,73 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+              in >> tag >> boxMinX >> boxMinY >> boxMinZ >> boxMaxX >>
+                boxMaxY >> boxMaxZ >> numPhysicals;
+              AssertThrow(numPhysicals < 2,
+                          ExcMessage("More than one tag is not supported!"));
+              for (unsigned int j = 0; j < numPhysicals; ++j)
+                in >> physicalTag;
+              tag_maps[3][tag] = (numPhysicals == 0) ? 0 : physicalTag;
+              in >> numSurfaces;
+              for (unsigned int j = 0; j < numSurfaces; ++j)
+                in >> tag;
```
Comment (drwells) [inline source/grid/grid_in.cc]: same

File: source/grid/grid_in.cc [hunk 5]
```diff
@@ -1451,14 +1452,73 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+              in >> tag >> boxMinX >> boxMinY >> boxMinZ >> boxMaxX >>
+                boxMaxY >> boxMaxZ >> numPhysicals;
+              AssertThrow(numPhysicals < 2,
+                          ExcMessage("More than one tag is not supported!"));
+              for (unsigned int j = 0; j < numPhysicals; ++j)
+                in >> physicalTag;
+              tag_maps[2][tag] = (numPhysicals == 0) ? 0 : physicalTag;
+              in >> numCurves;
+              for (unsigned int j = 0; j < numCurves; ++j)
+                in >> tag;
```
Comment (drwells) [inline source/grid/grid_in.cc]: same

File: source/grid/grid_in.cc (hunk 3 above)
Comment (masterleinad) [reply source/grid/grid_in.cc]: I don't know what to do with them. The one we care for is `physical_tag`.

File: source/grid/grid_in.cc [hunk 6]
```diff
@@ -1497,20 +1556,19 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
     unsigned int global_vertex = 0;
     for (int entity_block = 0; entity_block < n_entity_blocks; ++entity_block)
       {
-        int           tagEntity;
-        int           dimEntity;
         int           parametric;
         unsigned long numNodes;
```
Comment (drwells) [inline source/grid/grid_in.cc]: I didn't realize the camel case code was already here. We should just deal with that in a followup PR.

File: source/grid/grid_in.cc [hunk 7]
```diff
@@ -1451,14 +1452,72 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
             {
-              in >> line;
+              // parse point ids
+              in >> tag >> box_min_x >> box_min_y >> box_min_z >> box_max_x >>
+                box_max_y >> box_max_z >> n_physicals;
+              AssertThrow(n_physicals < 2,
+                          ExcMessage("More than one tag is not supported!"));
+              for (unsigned int j = 0; j < n_physicals; ++j)
+                in >> physical_tag;
+              tag_maps[0][tag] = (n_physicals == 0) ? 0 : physical_tag;
```
Comment (bangerth) [inline source/grid/grid_in.cc]: So you're taking the last tag there is, or zero if there is none. Is this the correct choice? I have no idea what these tags do.

In any case, maybe you could add a comment here to state what I have in my first sentence and explain why.

File: source/grid/grid_in.cc [hunk 8]
```diff
@@ -1451,14 +1452,72 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+            }
+          for (unsigned int i = 0; i < n_curves; ++i)
```
Comment (bangerth) [inline source/grid/grid_in.cc]: maybe say something along the lines of "We really don't care about the curves, but we have to parse them because their format is unstructured".

same for the other sections below.

File: source/grid/grid_in.cc (hunk 7 above)
Comment (masterleinad) [reply source/grid/grid_in.cc]: In all the files I have converted, there was never more than one "physical tag" and if one was present it matched the boundary id we should use later. If there is none, we use 0 as default
in conformance with the default boundary id. I don't know what to do if there is more than one tag. That's the reason for the `Assert`.

I added at least one comment saying where these tags will be used.

Comment (bangerth) [reply source/grid/grid_in.cc]: Good enough -- we can always deal with the case of what to do if there are more than one tag when someone shows us an input file :-)

Comment (masterleinad) [reply source/grid/grid_in.cc]: ... and tells us what to do with it.

Comment (bangerth) [reply source/grid/grid_in.cc]: That too, yes :-)

File: source/grid/grid_in.cc [hunk 9]
```diff
@@ -1404,10 +1404,11 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
 
-  unsigned int n_vertices;
-  unsigned int n_cells;
-  unsigned int dummy;
-  std::string  line;
+  unsigned int                      n_vertices;
+  unsigned int                      n_cells;
+  unsigned int                      dummy;
+  std::string                       line;
+  std::array<std::map<int, int>, 4> tag_maps;
```
Comment (bangerth) [inline source/grid/grid_in.cc]: Can you document what this maps from and to, and what the `4` stands for? I suspect it's the dimension of the object or some such?

File: source/grid/grid_in.cc [hunk 10]
```diff
@@ -1451,14 +1452,90 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
 
-      // if the next block is of kind $Entities, ignore it
+      // if the next block is of kind $Entities, parse it
       if (line == "$Entities")
         {
-          do
+          unsigned long n_points, n_curves, n_surfaces, n_volumes, n_physicals;
+          int           tag, physical_tag;
+          double        box_min_x, box_min_y, box_min_z, box_max_x, box_max_y,
+            box_max_z;
```
Comment (bangerth) [inline source/grid/grid_in.cc]: Can you move the declaration of `tag`...`box_max_z` into each of the brace-enclosed blocks below? This duplicates their declarations, but at least one never has to wonder whether the state of a variable is carried from one block to another.

File: source/grid/grid_in.cc [hunk 11]
```diff
@@ -1451,14 +1452,90 @@ GridIn<dim, spacedim>::read_msh(std::istream &in)
...
+
+          // we only care for 'physical_tag' to fill tag_maps
+          in >> n_points >> n_curves >> n_surfaces >> n_volumes;
```
Comment (bangerth) [inline source/grid/grid_in.cc]: the comment seems misplaced since it doesn't attach to what you're actually doing in the following line

File: source/grid/grid_in.cc (hunk 8 above)
Comment (bangerth) [reply source/grid/grid_in.cc]: Ah, forget it -- you actually do care.
