### PR TITLE
Make sure `stride_small_size` is at least 1.

### LINKED ISSUE #17633: 'integer divide by zero' in `ComputeIndexOwner`
Running additional tests in the hp-framework surfaced a new error.

I'm running a 3D Poisson scenario on a L-shaped domain, very similar to step-75. I will try if we can reproduce it also with step-75 itself.

Potentially #17485 brought this issue to our attention.

Any idea what's going on here? (I truncated the output for convenience)

```
Running poisson_mg-asm_cycles with dealii & Trilinos on 12 MPI rank(s)...
...
Cycle 5:
   Number of global levels:      11
   Number of active cells:       256854
     by partition:               25320 21839 23549 21178 16242 20138 17404 19246 ...
   Max active FE index in use  : 6
   Frequencies of poly. degrees: 2:94538 3:72056 4:66812 5:20080 6:3304 7:64
   Number of degrees of freedom: 12416562
     by partition:               1002985 1044105 1012960 1048903 1089618 1044122 1073453 1047778 ...
   Number of constraints:        3275643
     by partition:               259306 298811 268982 304565 259888 247056 258790 249987 ...
   Fraction of constraints:      26.3812%
   Number of identities:         37278
     by partition:               2522 4008 2752 3841 2820 2669 2753 2760 ...
   Fraction of identities:       0.300228%
   Number of patch DoFs:         255364
   Fraction of patch DoFs:       2.05664%
[...] Caught signal 8 (Floating point exception: integer divide by zero)
==== backtrace (tid:  36359) ====
 0 0x000000000004d212 ucs_event_set_fd_get()  ???:0
 1 0x000000000004d4ea ucs_event_set_fd_get()  ???:0
 2 0x000000000003d1d0 __sigaction()  ???:0
 3 0x0000000006e43856 dealii::Utilities::MPI::internal::ComputeIndexOwner::Dictionary::partition()  ???:0
 4 0x0000000006e44f3f dealii::Utilities::MPI::internal::ComputeIndexOwner::Dictionary::reinit()  ???:0
 5 0x0000000006e46926 dealii::Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmsPayload::ConsensusAlgorithmsPayload()  ???:0
 6 0x00000000002f47c7 dealii::internal::BlackBoxFineDoFHandlerView<3>::reinit()  ???:0
 7 0x000000000033b892 dealii::internal::GlobalCoarseningFineDoFHandlerView<3>::GlobalCoarseningFineDoFHandlerView()  ???:0
 8 0x000000000039239e dealii::internal::MGTwoLevelTransferImplementation::reinit_geometric_transfer<3, double>()  ???:0
 9 0x00000000003e2f3d Poisson::Problem<3, dealiiTrilinos, 3>::solve()  ???:0
10 0x00000000003ead86 Poisson::Problem<3, dealiiTrilinos, 3>::run()  ???:0
11 0x00000000001fc831 main()  ???:0
12 0x0000000000025e08 __libc_init_first()  ???:0
13 0x0000000000025ecc __libc_start_main()  ???:0
14 0x00000000001fef15 _start()  ???:0
=================================
```

### PR DESCRIPTION
**Pull request by marcfehling**
Related to #17633.

### CODE REVIEW

**Review by drwells — APPROVED** [review]

**Comment by tjhei** [comment]
```
/Users/runner/work/dealii/dealii/source/base/mpi_compute_index_owner_internal.cc:443:13: error: no matching function for call to 'max'
            std::max((size + n_procs - 1) / n_procs, range_minimum_grain_size);
            ^~~~~~~~
```

**Comment by marcfehling** [comment]
`size` is a `global_dof_index`, while `range_minimum_grain_size` is an `unsigned int`. I specified the template of `std::max`.

File: source/base/mpi_compute_index_owner_internal.cc [hunk 1]
```diff
@@ -437,14 +439,13 @@ namespace Utilities
...
-          if (dofs_per_process < range_minimum_grain_size)
-            {
-              dofs_per_process  = range_minimum_grain_size;
-              stride_small_size = dofs_per_process * n_procs / size;
-            }
-          else
-            stride_small_size = 1;
+          dofs_per_process =
+            std::max<types::global_dof_index>((size + n_procs - 1) / n_procs,
+                                              range_minimum_grain_size);
```
Comment (bangerth) [inline source/base/mpi_compute_index_owner_internal.cc:444]: Is this right? I think you only want to set `stride_small_size`, but not modify `dofs_per_process`.

Comment (kronbichler) [reply source/base/mpi_compute_index_owner_internal.cc:444]: I think this should be ok, because we previously set `dofs_per_process` and modified it if it was below the threshold.

**Review by kronbichler — APPROVED** [review]
I agree with the change and the code looks nicer in my opinion. However, I am confused why the old code was wrong because I would have thought that the checks were such that the division by `size` in line 444 would always involve a number `>= size`, but anyway this seems fine.

File: source/base/mpi_compute_index_owner_internal.cc (hunk 1 above)
Comment (marcfehling) [reply source/base/mpi_compute_index_owner_internal.cc:444]: After outsourcing the `stride_small_size = std::max(...)` assignment in commit 034fee0c8bcf7a5b33683a97745c8b34eff22f7c, the remaining lines regarding `dofs_per_process` were:
```
dofs_per_process = (size + n_procs - 1) / n_procs;
if (dofs_per_process < range_minimum_grain_size)
  dofs_per_process = range_minimum_grain_size;
```
This looked like a good application for `std::max` to me.

---

We can debate about whether my commit in 034fee0c8bcf7a5b33683a97745c8b34eff22f7c is right in the first place.

**Review by masterleinad — APPROVED** [review]
