### PR TITLE
Util::MPI::compute_n_point_to_point_communications() add fallback

### LINKED ISSUE #13074: Failure in ConsensusAlgorithms::NBX<T1, T2>::answer_requests()
On my system, I have a number (~30) tests that perpetually seem to fail. Here is one:
```
> mpirun -np 3 ./fe_tools_extrapolate_05.debug 

--------------------------------------------------------
An error occurred in line <220> of file </raid/bangerth/p/deal.II/1/dealii/include/deal.II/base/mpi_consensus_algorithms.templates.h> in function
    void dealii::Utilities::MPI::ConsensusAlgorithms::NBX<T1, T2>::answer_requests() [with T1 = char; T2 = char]
The violated condition was: 
    requesting_processes.find(other_rank) == requesting_processes.end()
Additional information: 
    Process is requesting a second time!
--------------------------------------------------------

Calling MPI_Abort now.
To break execution in a GDB session, execute 'break MPI_Abort' before running. You can also put the following into your ~/.gdbinit:
  set breakpoint pending on
  break MPI_Abort
  set breakpoint pending auto
--------------------------------------------------------------------------
```

Does anyone have an idea what is at the root of this? `mpi/fe_tools_extrapolate_05` is a test that is supposed to be run with 3 processes, as shown by the output files in `tests/mpi/`, so the invocation above should work.

I specifically care about this because after the error, the whole test hangs and ultimately times out after 600 seconds (as do the others mentioned above). This slows down the turn-around time on my system substantially.

### PR DESCRIPTION
**Pull request by peterrum**
closes #13074

I have misread the documentation when making the change: 

> destinations: The list of processors the current process wants to send information to. This list need not be sorted in any way. If it contains duplicate entries that means that multiple messages are intended for a given destination.

I still find it odd that `destination` can have multiple times the same rank.

### CODE REVIEW

**Comment by bangerth** [comment]
We can add an assertion and change the documentation if you think that would be useful.

File: source/base/mpi.cc [hunk 1]
```diff
@@ -511,9 +511,82 @@ namespace Utilities
...
-      return compute_point_to_point_communication_pattern(mpi_comm,
-                                                          destinations)
-        .size();
+      auto destinations_unique = destinations;
+      std::sort(destinations_unique.begin(), destinations_unique.end());
+      destinations_unique.erase(std::unique(destinations_unique.begin(),
+                                            destinations_unique.end()),
+                                destinations_unique.end());
+
+      if (Utilities::MPI::min<unsigned int>(destinations.size() ==
```
Comment (bangerth) [inline source/base/mpi.cc:520]: can you add a comment what the `if` actually checks? Maybe "If the list of destinations did not include any duplicates, then ..."

File: source/base/mpi.cc [hunk 2]
```diff
@@ -511,9 +511,82 @@ namespace Utilities
...
+                                              destinations_unique.size(),
+                                            mpi_comm))
+        {
+          return compute_point_to_point_communication_pattern(mpi_comm,
```
Comment (bangerth) [inline source/base/mpi.cc:524]: what does the documentation of that function say about duplicates? I tend to think that the two functions should have the same semantics regarding duplicates, given that their names are almost the same.

**Review by bangerth — DISMISSED** [review]

File: source/base/mpi.cc (hunk 2 above)
Comment (peterrum) [reply source/base/mpi.cc:539]: Good point. The documentation states:

> destinations	The list of processors the current process wants to send information to. This list need not be sorted in any way. If it contains duplicate entries that means that multiple messages are intended for a given destination.

> A list of processors that have indicated that they want to send something to the current processor. The resulting list is not sorted. It may contain duplicate entries if processors enter the same destination more than once in their destinations list.

But, the function has the same problem as `compute_n_point_to_point_communications()`. I have fixed it.

**Review by kronbichler — APPROVED** [review]
This looks good to me.

**Comment by bangerth** [comment]
@peterrum :
Out of curiosity, this patch only enables the consensus algorithm if we have MPI 3.0 or later. It seems odd to have that here, rather than in the consensus algorithm itself. Is the consensus algorithm NBX not actually implemented for previous MPI versions?
