### PR TITLE
Provide some guarantees with regard to exceptions in ParameterHandler.

### LINKED ISSUE #4280: ParameterHandler, actions, and exceptions
#4247 adds actions to the `ParameterHandler` class, but it does not say what happens if you throw an exception in an action. We should try to gracefully handle this.

Along the same line, if we can't match a parameter to its pattern, then this also triggers an exception. In both cases, the `ParameterHandler` object gets stuck in the section it currently is in, but I think we should try to unravel to the top level first.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #4280.

### CODE REVIEW

File: source/base/parameter_handler.cc [hunk 1]
```diff
@@ -1697,16 +1697,53 @@ void ParameterHandler::parse_input (std::istream &input,
...
+              throw;
+            }
+
           fully_concatenated_line.clear();
         }
     }
 
   // While it does not make much sense for anyone to actually do this, allow
-  // the last line to end in a backslash.
+  // the last line to end in a backslash. to do do, we need to parse
```
Comment (luca-heltai) [inline source/base/parameter_handler.cc]: to do so

**Comment by luca-heltai** [comment]
Merge yourself after the minor typo has been corrected.

File: source/base/parameter_handler.cc (hunk 1 above)
Comment (drwells) [inline source/base/parameter_handler.cc]: While not particularly important, my intent with the variable names in this section was that a 'concatenated line' referred to several lines that had been joined by `\`s. Hence it would be more consistent to write "To do this, we need to parse whatever concatenated line is left over.

Also, would it be possible to encapsulate this try-catch block with a lambda? It would be nice to not write the same thing in two places.

**Comment by bangerth** [comment]
Nice idea for an idiom to package repeated lines of code into a lambda -- I learned something new today. Thanks, @drwells !

Maybe like this now?

**Comment by drwells** [comment]
You are welcome. I like this little idiom a lot: it lets us write (more or less) safe macros.

This looks good. My only nitpick is that we should use `[&, this, saved_path]` to avoid copying `saved_path`.

**Comment by bangerth** [comment]
I just learned another thing -- I had misunderstood the syntax of lambdas. But I think so did you: `[&, this, saved_path]` means that `saved_path` is copied and everything else is taken by reference. (`this` is treated differently anyway.)

Anyway, how about now?

**Comment by bangerth** [comment]
See the example with `struct S2` here: http://en.cppreference.com/w/cpp/language/lambda

**Comment by drwells** [comment]
Yes, you are right (what I proposed would still copy things). What you wrote is better, anyway, since it explicitly shows which parameters we want to store (and that one is by reference).

This should be good to go if the tester is happy.
