### PR TITLE
Explicit Instantiate GridTools::collect_periodic_faces with Meshtype = parallel::shared::triangulation<1,1>

### LINKED ISSUE #14879: GridTools::collect_periodic_faces with parallel:shared::Triangulation in 1D
Hi everyone,

I have an issue with the function GridTools::collect_periodic_faces when I use it with parallel::shared::Triangulation as MeshType and dim = 1. During the linking stage of the compilation, I get the following error
```
my_application.cpp:375: error: undefined reference to 'void dealii::GridTools::collect_periodic_faces<dealii::parallel::shared::Triangulation<1, 1> >(dealii::parallel::shared::Triangulation<1, 1> const&, unsigned int, unsigned int, unsigned int, std::vector<dealii::GridTools::PeriodicFacePair<dealii::parallel::shared::Triangulation<1, 1>::cell_iterator>, std::allocator<dealii::GridTools::PeriodicFacePair<dealii::parallel::shared::Triangulation<1, 1>::cell_iterator> > >&, dealii::Tensor<1, dealii::parallel::shared::Triangulation<1, 1>::space_dimension, double> const&, dealii::FullMatrix<double> const&)'
collect2: error: ld returned 1 exit status
```
To me it looks like the explicit instantiation of the templated function GridTools::collect_periodic_faces() did not happen. I tried to explicitly instantiate it myself and I played around with the macro if conditions in the file grid_tools_dofs_handlers.inst.in. But I was not able to get it working. 
Can you help me to fix this issue?

Thank you very much.

### PR DESCRIPTION
**Pull request by nils-schween**
Resolves #14879

### CODE REVIEW

File: tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+    Point<dim> p2{1.};
+    std::vector<unsigned int> repitions{num_refinements};
+    GridGenerator::subdivided_hyper_rectangle(tria, repitions, p1, p2, true);
+
+    // Collect periodic faces in the x-direction
+    GridTools::collect_periodic_faces(tria, 0, 1, 0, matched_pairs);
+    // Check the size of the matched_pairs vector
+    if (matched_pairs.size() != 1) {
+      // throw error
+    }
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc:49]:
```suggestion
    deallog << matched_pairs.size()  << std::endl;
```

File: tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+  } else if constexpr (dim == 3) {
+    Point<dim> p1{0., 0., 0.};
+    Point<dim> p2{1., 1., 1.};
+    std::vector<unsigned int> repitions{num_refinements, num_refinements,
+                                        num_refinements};
+    GridGenerator::subdivided_hyper_rectangle(tria, repitions, p1, p2, true);
+
+    GridTools::collect_periodic_faces(tria, 0, 1, 0, matched_pairs);
+    if (matched_pairs.size() != 256) {
+    }
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc:68]:
```suggestion
    deallog << matched_pairs.size() << std::endl;
```

File: tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+  } else if constexpr (dim == 2) {
+    Point<dim> p1{0., 0.};
+    Point<dim> p2{1., 1.};
+    std::vector<unsigned int> repitions{num_refinements, num_refinements};
+    GridGenerator::subdivided_hyper_rectangle(tria, repitions, p1, p2, true);
+
+    GridTools::collect_periodic_faces(tria, 0, 1, 0, matched_pairs);
+    if (matched_pairs.size() != 16) {
+    }
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_period_faces_parallel_shared_tria.cc:58]:
```suggestion
    deallog << matched_pairs.size() << std::endl;
```

**Comment by nils-schween** [comment]
I had some issues with numdiff tool. It timed out, I had to locally adapt the `macro_deal_ii_pickup_tests.cmake` and increase the timeout out. Maybe a higher default value would be a good idea. I took me a while to pin this down. Calling make indent gives me the following error message
```
 This indent script requires clang-format version 11.1,
***   but version 15.0 was found instead.
```

**Comment by masterleinad** [comment]
> Calling make indent gives me the following error message
> This indent script requires clang-format version 11.1,
> ***   but version 15.0 was found instead.

Hmm... I had hoped that it would tell you to run ` ./contrib/utilities/download_clang_format`. Would you mind trying that and then running `make indent` again?

**Comment by nils-schween** [comment]
I am sorry that I had to force push the branch, but `make indent` complained about my `user.name`. It has to be `Nils Schween` and not `nils-schween`. While force-pushing, I did not preserve the merges. I hope that this is okay.

**Comment by nils-schween** [comment]
I overlooked one of the merged commits and I had to force-push again. Now, it should be correct.

File: tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+  deallog << "dim = " << dim << std::endl;
+  parallel::shared::Triangulation<dim> tria(comm);
+
+  std::vector<typename GridTools::PeriodicFacePair<
+    typename parallel::shared::Triangulation<dim>::cell_iterator>>
+    matched_pairs;
+
+  unsigned int num_refinements = 1 << 4;
+
+  if constexpr (dim == 1)
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc:44]: Sorry for not catching that earlier but you can't use C++17 features. We are only requiring C++14.

Comment (nils-schween) [reply tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc]: Your Godbolt example looks very interesting, even though I do not fully understand. If it is only about the `if constexpr`, then it might be easier to just write a for loop as suggested in my last commit. `GridGenerator` functions and `GridTools` function are "run-time" functions (i.e. there arguments do not have to be known during compilation).

Comment (nils-schween) [reply tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc]: I just saw, that I mispelled the variable `repititions`, in the above program it is `repitions`. Should I change it, or just leave it as it is?

File: tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+  unsigned int              num_refinements = 1 << 4;
+  Point<dim>                p1;
+  Point<dim>                p2;
+  std::vector<unsigned int> repititions(dim);
+
+  for (unsigned int i = 0; i < dim; ++i)
+    {
+      p1[i]          = 0.;
+      p2[i]          = 1.;
+      repititions[i] = num_refinements;
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc:51]:
```suggestion
      repetitions[i] = num_refinements;
```

File: tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+  parallel::shared::Triangulation<dim> tria(comm);
+
+  std::vector<typename GridTools::PeriodicFacePair<
+    typename parallel::shared::Triangulation<dim>::cell_iterator>>
+    matched_pairs;
+
+  unsigned int              num_refinements = 1 << 4;
+  Point<dim>                p1;
+  Point<dim>                p2;
+  std::vector<unsigned int> repititions(dim);
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc:45]:
```suggestion
  std::vector<unsigned int> repetitions(dim);
```

File: tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+
+  for (unsigned int i = 0; i < dim; ++i)
+    {
+      p1[i]          = 0.;
+      p2[i]          = 1.;
+      repititions[i] = num_refinements;
+    }
+  GridGenerator::subdivided_hyper_rectangle(tria, repititions, p1, p2, true);
```
Comment (masterleinad) [inline tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc:53]:
```suggestion
  GridGenerator::subdivided_hyper_rectangle(tria, repetitions, p1, p2, true);
```

**Review by masterleinad — APPROVED** [review]
Looks good to me now. Let's see what our CI says.

**Comment by masterleinad** [comment]
I don't care much if you fix the typo or not.

File: tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc (hunk 4 above)
Comment (masterleinad) [reply tests/grid/grid_tools_collect_periodic_faces_parallel_shared_tria.cc]: Yeah, writing the loop explicitly is good.

**Comment by masterleinad** [comment]
```
invalid author 'nils-schween' without firstname and lastname
```

**Comment by nils-schween** [comment]
I am sorry for the chaos. It is my first time conritbuting to dealii.

 I used the github webpage to include your correction of my typo, hence the wrong author. I updated the author. It should work now.

**Review by bangerth — APPROVED** [review]
Excellent, thank you! And now you are also set up correctly for future patches :-)

**Comment by nils-schween** [comment]
Thank you! It's great to see it being merged. Next time a patch will be much more straightforward
