### PR TITLE
Use the new version of find_active_cell_around_point() in step62

### LINKED ISSUE #10737: HDF5 and step-62 are not compatible with find_active_cell_around_point()
Step-62 hangs. This related to two issues.
- find_active_cell_around_point() fails in parallel. Even if a point is inside the domain some of the MPI ranks will fail. I think that it is related to #10478 but I'm not sure.
- The `AssertThrow` of find_active_cell_around_point() fails and hangs the program. This is related to #10736

I'm going to prepare a small test to isolate the problem.

### PR DESCRIPTION
**Pull request by dangars**
This fixes #10737

We should wait until #11276 has been merged before merge this PR.

### CODE REVIEW

File: examples/step-62/step-62.cc [hunk 1]
```diff
@@ -1055,6 +1057,13 @@ namespace step62
     // displacement_data contains the value of the displacement at these points.
     std::vector<hsize_t>              coordinates;
     std::vector<std::complex<double>> displacement_data;
+
+    auto                       mapping = StaticMappingQ1<dim>::mapping;
```
Comment (bangerth) [inline examples/step-62/step-62.cc:1061]: If you rebase, this should now be as follows:
```suggestion
    auto                       mapping = get_default_linear_mapping(triangulation);
```

File: examples/step-62/step-62.cc [hunk 2]
```diff
@@ -1055,6 +1057,13 @@ namespace step62
...
+    GridTools::Cache<dim, dim> cache(triangulation, mapping);
+    auto cell_hint = typename Triangulation<dim, dim>::active_cell_iterator();
```
Comment (bangerth) [inline examples/step-62/step-62.cc:1063]:
```suggestion
    typename Triangulation<dim, dim>::active_cell_iterator cell_hint{};
```

File: examples/step-62/step-62.cc [hunk 3]
```diff
@@ -1055,6 +1057,13 @@ namespace step62
...
+    std::vector<bool> marked_vertices = {};
+    double            tolerance       = 1.e-10;
```
Comment (bangerth) [inline examples/step-62/step-62.cc:1065]:
```suggestion
    const double            tolerance       = 1.e-10;
```

File: examples/step-62/step-62.cc [hunk 4]
```diff
@@ -1064,17 +1073,19 @@ namespace step62
...
-            cell_point = GridTools::find_active_cell_around_point(mapping,
-                                                                  dof_handler,
-                                                                  point);
-
-          point_in_locally_owned_cell = cell_point.first->is_locally_owned();
+          auto cell_and_ref_point = GridTools::find_active_cell_around_point(
+            cache, point, cell_hint, marked_vertices, tolerance);
+          if (cell_and_ref_point.first != triangulation.end())
+            {
+              if (cell_and_ref_point.first.state() == IteratorState::valid)
```
Comment (bangerth) [inline examples/step-62/step-62.cc:1082]: I don't think you need this second check. The first one is already what you need, the second just is a different way of asking the same question.

**Comment by dangars** [comment]
@bangerth I'm really sorry for the late reply. This was a busy month. I'll make the modifications this week :)

I'll also update #10747

**Comment by bangerth** [comment]
No worries!

File: examples/step-62/step-62.cc (hunk 1 above)
Comment (dangars) [reply examples/step-62/step-62.cc:1062]: I added `get_default_linear_mapping` as a _todo comment_. I think that the branch of luca that I use as base is too old. I'll update this once the branch of luca is in master

File: examples/step-62/step-62.cc (hunk 4 above)
Comment (dangars) [reply examples/step-62/step-62.cc:1083]: It looks like I need both `ifs`. If I remove the second `if`, I get the following error:
```
--------------------------------------------------------
An error occurred in line <1014> of file </home/daniel/repositories/dealii/include/deal.II/grid/tria_iterator.h> in function                                                                                        
    Accessor &dealii::TriaRawIterator<dealii::CellAccessor<2, 2> >::operator*() [Accessor = dealii::CellAccessor<2, 2>]                                                                                             
The violated condition was:
    Accessor::structure_dimension != Accessor::dimension || state() == IteratorState::valid
Additional information:
    You tried to dereference a cell iterator for which this is not possible. More information on this iterator: level=-2, index=-2, state=invalid                                                                   

Stacktrace:
-----------
#0  step-62.debug: dealii::TriaRawIterator<dealii::CellAccessor<2, 2> >::operator*()
#1  step-62.debug: dealii::TriaRawIterator<dealii::CellAccessor<2, 2> >::operator->()
#2  step-62.debug: step62::ElasticWave<2>::store_frequency_step_data(unsigned int)
#3  step-62.debug: step62::ElasticWave<2>::frequency_sweep()
#4  step-62.debug: step62::ElasticWave<2>::run()
#5  step-62.debug: main
--------------------------------------------------------

Calling MPI_Abort now.
```

File: examples/step-62/step-62.cc (hunk 1 above)
Comment (dangars) [reply examples/step-62/step-62.cc:1061]: @bangerth I rebased and as you suggested I tried to use the following line of code:
```c++
auto                       mapping = get_default_linear_mapping(triangulation);
```
But it I use that line of code I get the following. Do you know why I get this compilation error?
```cmake
examples/step-62/step-62.cc:1061:32: error: variable type 'dealii::Mapping<2, 2>' is an abstract class                                                        
    auto                       mapping = get_default_linear_mapping(triangulation);                                                                                                            
                               ^                                                                                                                                                               
examples/step-62/step-62.cc:1309:9: note: in instantiation of member function 'step62::ElasticWave<2>::store_frequency_step_data' requested here              
        store_frequency_step_data(frequency_idx);                                                                                                                                              
        ^                                                                                                                                                                                      
examples/step-62/step-62.cc:1365:5: note: in instantiation of member function 'step62::ElasticWave<2>::frequency_sweep' requested here                        
    frequency_sweep();                                                                                                                                                                         
    ^                                                                                                                                                                                          
examples/step-62/step-62.cc:1487:25: note: in instantiation of member function 'step62::ElasticWave<2>::run' requested here                                   
        elastic_problem.run();                                                                                                                                                                 
                        ^                                                                                                                                                                      
include/deal.II/fe/mapping.h:321:3: note: unimplemented pure virtual method 'clone' in 'Mapping'                                                              
  clone() const = 0;                                                                                                                                                                           
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:402:3: note: unimplemented pure virtual method 'preserves_vertex_locations' in 'Mapping'                                         
  preserves_vertex_locations() const = 0;                                                                                                                                                      
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:409:3: note: unimplemented pure virtual method 'is_compatible_with' in 'Mapping'                                                 
  is_compatible_with(const ReferenceCell &reference_cell) const = 0;                                                                                                                           
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:428:3: note: unimplemented pure virtual method 'transform_unit_to_real_cell' in 'Mapping'                                        
  transform_unit_to_real_cell(                                                                                                                                                                 
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:461:3: note: unimplemented pure virtual method 'transform_real_to_unit_cell' in 'Mapping'                                        
  transform_real_to_unit_cell(                                                                                                                                                                 
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:687:3: note: unimplemented pure virtual method 'requires_update_flags' in 'Mapping'                                              
  requires_update_flags(const UpdateFlags update_flags) const = 0;                                                                                                                             
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:738:3: note: unimplemented pure virtual method 'get_data' in 'Mapping'                                                           
  get_data(const UpdateFlags      update_flags,                                                                                                                                                
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:808:3: note: unimplemented pure virtual method 'get_subface_data' in 'Mapping'                                                   
  get_subface_data(const UpdateFlags          update_flags,                                                                                                                                    
  ^                                                                                                                                                                                            
include/deal.II/fe/mapping.h:895:3: note: unimplemented pure virtual method 'fill_fe_values' in 'Mapping'                                                     
  fill_fe_values(                                                                                                                                                                              
  ^
include/deal.II/fe/mapping.h:975:3: note: unimplemented pure virtual method 'fill_fe_subface_values' in 'Mapping'
  fill_fe_subface_values(
  ^
include/deal.II/fe/mapping.h:1058:3: note: unimplemented pure virtual method 'transform' in 'Mapping'
  transform(const ArrayView<const Tensor<1, dim>> &                  input,
  ^
include/deal.II/fe/mapping.h:1111:3: note: unimplemented pure virtual method 'transform' in 'Mapping'
  transform(const ArrayView<const DerivativeForm<1, dim, spacedim>> &input,
  ^
include/deal.II/fe/mapping.h:1169:3: note: unimplemented pure virtual method 'transform' in 'Mapping'
  transform(const ArrayView<const Tensor<2, dim>> &                  input,
  ^
include/deal.II/fe/mapping.h:1216:3: note: unimplemented pure virtual method 'transform' in 'Mapping'
  transform(const ArrayView<const DerivativeForm<2, dim, spacedim>> &input,
  ^
include/deal.II/fe/mapping.h:1269:3: note: unimplemented pure virtual method 'transform' in 'Mapping'
  transform(const ArrayView<const Tensor<3, dim>> &                  input,
  ^
1 error generated.
```

Comment (jppelteret) [reply examples/step-62/step-62.cc:1061]: You probably need to write this as
```
const auto &mapping = get_default_linear_mapping(triangulation);
```
What you had is probably trying to store the mapping in an instance of the abstract class `Mapping<dim, spacedim>`, which is not permitted. The `get_default_linear_mapping()` function returns a reference to a concrete instance of a mapping.

Comment (dangars) [reply examples/step-62/step-62.cc]: Thanks a lot @jppelteret, that was a really quick reply!
Now it works :)

**Comment by dangars** [comment]
Now that #11276 has been merged. This PR is ready to review.

@luca-heltai could you take a look to this PR and let me know if this is the right approach to use `find_active_cell_around_point()` ? Thanks

File: examples/step-62/step-62.cc (hunk 4 above)
Comment (luca-heltai) [reply examples/step-62/step-62.cc:1081]: Apparently, the default constructor of `active_cell_iterator` is not equal to `end()`. I think this is a bug and should be fixed.

Comment (dangars) [reply examples/step-62/step-62.cc]: @luca-heltai I updated the PR and now I use only the second `if`. Maybe we can merge this PR like this and when `active_cell_iterator` is fixed I can change this to use only the first `if`

That's right the default constructor of `active_cell_iterator` is not equal to `end()`. Should I do a separate PR to address this issue?

Comment (luca-heltai) [reply examples/step-62/step-62.cc]: > That's right the default constructor of active_cell_iterator is not equal to end(). Should I do a separate PR to address this issue?

this would be great, and the correct solution.

**Review by luca-heltai — APPROVED** [review]

File: examples/step-62/step-62.cc (hunk 4 above)
Comment (dangars) [reply examples/step-62/step-62.cc]: Sounds good! I'll prepare a separate PR

**Review by peterrum — APPROVED** [review]
