### PR TITLE
Fix `active_fe_index` query to consider cell categorization

### LINKED ISSUE #16250: `MatrixFreeTools::compute_diagonal` fails with cell vectorization categories
Using [`MatrixFreeTools::compute_diagonal()`](https://github.com/dealii/dealii/blob/578fcb0c15df4b88c42f71d676ac29a93ae007f3/include/deal.II/matrix_free/tools.h#L62) in combination with `MatrixFree<>::AdditionalData::cell_vectorization_category` emits the following stacktrace on my system:

```bash
An error occurred in line <2866> of file <~/dealii/include/deal.II/matrix_free/matrix_free.h> in function
    const dealii::internal::MatrixFreeFunctions::ShapeInfo<VectorizedArrayType>& dealii::MatrixFree<<anonymous>, <template-parameter-1-2>, <template-parameter-1-3>>::get_shape_info(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const [with int dim = 3; Number = double; VectorizedArrayType = dealii::VectorizedArray<double, 4>]
The violated condition was: 
    ::dealii::deal_II_exceptions::internals::compare_less_than(active_fe_index, shape_info.size(2))
Additional information: 
    Index 5 is not in the half-open range [0,1).
```

```bash

Stacktrace:
-----------
#0  solver: dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >::get_shape_info(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const
#1  solver: dealii::FEEvaluationData<3, dealii::VectorizedArray<double, 4ul>, false>::InitializationData dealii::internal::extract_initialization_data<false, 3, double, dealii::VectorizedArray<double, 4ul> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)
#2  solver: dealii::FEEvaluationBase<3, 3, double, false, dealii::VectorizedArray<double, 4ul> >::FEEvaluationBase(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, unsigned int, unsigned int, unsigned int)
#3  solver: dealii::FEEvaluationAccess<3, 3, double, false, dealii::VectorizedArray<double, 4ul> >::FEEvaluationAccess(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, unsigned int, unsigned int, unsigned int)
#4  solver: dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >::FEEvaluation(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)
#5  solver: dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >::FEEvaluation(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, std::pair<unsigned int, unsigned int> const&, unsigned int, unsigned int, unsigned int)
#6  solver: dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}::operator()(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#7  solver: void std::__invoke_impl<void, dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&>(std::__invoke_other, dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#8  solver: std::enable_if<is_invocable_r_v<void, dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&>, void>::type std::__invoke_r<void, dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&>(dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#9  solver: std::_Function_handler<void (dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&), dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}>::_M_invoke(std::_Any_data const&, dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#10  solver: std::function<void (dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)>::operator()(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&) const
#11  solver: dealii::internal::MFClassWrapper<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >::cell_integrator(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&) const
#12  solver: dealii::internal::MFWorker<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::internal::MFClassWrapper<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >, true>::process_range(void (dealii::internal::MFClassWrapper<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >::* const&)(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&) const, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned int)
#13  solver: dealii::internal::MFWorker<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::internal::MFClassWrapper<dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >, int, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >, true>::cell(unsigned int)
#14  ~/dealii/build/lib/libdeal_II.g.so.9.5.1: dealii::internal::MatrixFreeFunctions::TaskInfo::loop(dealii::internal::MFWorkerInterface&) const
#15  solver: void dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> >::cell_loop<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, int>(std::function<void (dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)> const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, int const&, bool) const
#16  solver: void dealii::MatrixFreeTools::compute_diagonal<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&)> const&, unsigned int, unsigned int, unsigned int)
#17  solver: void dealii::MatrixFreeTools::compute_diagonal<Operator<3, double>, 3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(dealii::MatrixFree<3, double, dealii::VectorizedArray<double, 4ul> > const&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, void (Operator<3, double>::*)(dealii::FEEvaluation<3, -1, 0, 3, double, dealii::VectorizedArray<double, 4ul> >&) const, Operator<3, double> const*, unsigned int, unsigned int, unsigned int)
```

The reason for the assertion hit is the value of `active_fe_index` as determined in these lines:

https://github.com/dealii/dealii/blob/32778f423309ceab6ab06f5e941a4a8998ee05c0/include/deal.II/matrix_free/fe_evaluation.h#L2790-L2796

Changing the `active_fe_index` in the deal.II source code to zero (essentially as a hard-fix) as opposed to categorization number which was used before fixes the issue for me and the code runs as usual. I'm sure that's not a proper solution, but could give some evidence for the actual issue here.

After some discussion with @peterrum, there seems to be an idea about the failure at hand. From the user API, however, I cannot alter the `active_fe_index` or anything similar in the first place. The assertion hit stems from (a base class instantiation) of `FEEvaluation`, which is handled in `MatrixFreeTools::compute_diagonal()` itself.

However, I can easily reproduce the issue by modifying one of the [compute diagonal integration tests](https://github.com/dealii/dealii/blob/master/tests/matrix_free/compute_diagonal_01.cc)

```diff
--- a/tests/matrix_free/compute_diagonal_01.cc
+++ b/tests/matrix_free/compute_diagonal_01.cc
@@ -38,6 +38,13 @@ test()
       cell->set_refine_flag();
   tria.execute_coarsening_and_refinement();
 
+  for (auto &cell : tria.active_cell_iterators())
+    if (cell->is_active() && cell->is_locally_owned() &&
+        cell->center()[0] < 0.0)
+      cell->set_material_id(42);
+    else
+      cell->set_material_id(0);
+
   const FE_Q<dim>     fe_q(fe_degree);
   const FESystem<dim> fe(fe_q, n_components);
 
@@ -60,6 +67,14 @@ test()
     additional_data;
   additional_data.mapping_update_flags = update_values | update_gradients;
 
+  additional_data.cell_vectorization_category.resize(tria.n_active_cells());
+  for (const auto &cell : tria.active_cell_iterators())
+    if (cell->is_locally_owned())
+      additional_data.cell_vectorization_category[cell->active_cell_index()] =
+        cell->material_id();
+
+  additional_data.cell_vectorization_categories_strict = true;
+
   MappingQ<dim> mapping(1);
   QGauss<1>     quad(fe_degree + 1);
```

Although the final assertion hit looks slightly different, the error source should be the same (from my limited understanding).

@peterrum documenting this here for reference and to provide the test code I can use to reproduce the issue.

### PR DESCRIPTION
**Pull request by davidscn**
As described in #16250

I extended the existing test to also run the code with cell categorization to avoid code duplication, but I'm not sure if that complies to the test concept.

Also, I'm not completely sure about the formatting of the test output.

Resolves #16250

### CODE REVIEW

File: tests/matrix_free/compute_diagonal_01.cc [hunk 1]
```diff
@@ -25,7 +25,7 @@ template <int dim,
           typename Number              = double,
           typename VectorizedArrayType = VectorizedArray<Number>>
 void
-test()
+test(bool use_categorization = false)
```
Comment (peterrum) [inline tests/matrix_free/compute_diagonal_01.cc:28]: Could you add to the top of the file a description what the extended test is testing?

File: include/deal.II/matrix_free/matrix_free.h [hunk 2]
```diff
@@ -2689,11 +2689,12 @@ MatrixFree<dim, Number, VectorizedArrayType>::n_active_fe_indices() const
 template <int dim, typename Number, typename VectorizedArrayType>
 unsigned int
 MatrixFree<dim, Number, VectorizedArrayType>::get_cell_active_fe_index(
-  const std::pair<unsigned int, unsigned int> range) const
+  const std::pair<unsigned int, unsigned int> range, unsigned int dof_handler_index) const
```
Comment (peterrum) [inline include/deal.II/matrix_free/matrix_free.h:2692]: I don't think we need to pass here `dof_handler_index`. I think it is enough to use the first one.

Comment (davidscn) [reply include/deal.II/matrix_free/matrix_free.h]: I was actually not sure about it. I changed it now.

Comment (kronbichler) [reply include/deal.II/matrix_free/matrix_free.h]: I think there could be made a case for this (at least as a general interface): We could have multiple `DoFHandler` objects, and it could be that the second or third `DoFHandler` in the list of `MatrixFree::dof_handlers` could be the one with `hp` capability, and then we would miss this. Currently, we let `dof_handlers[0]` determine this information, see e.g. https://github.com/dealii/dealii/blob/578fcb0c15df4b88c42f71d676ac29a93ae007f3/include/deal.II/matrix_free/matrix_free.templates.h#L798-L812 and https://github.com/dealii/dealii/blob/578fcb0c15df4b88c42f71d676ac29a93ae007f3/include/deal.II/matrix_free/matrix_free.templates.h#L1557-L1564 and many other places assuming the index from `dh[0]`, but I think that could be relaxed and then the interface makes sense. That said, we can opt for a small change now and check it later.

**Comment by peterrum** [comment]
@davidscn There seems to be an issue with the output of the parallel run. Could you check?

**Comment by davidscn** [comment]
> > Also, I'm not completely sure about the formatting of the test output.
> @davidscn There seems to be an issue with the output of the parallel run. Could you check?

I think or hope it is only a matter of formatting the test output correctly. Should work now.

**Review by peterrum — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
Do you want to write a short changelog entry in the `doc/news/changes/minor` section? I think this is useful information for all users. (I can also merge as is and you/we open a follow-up PR.)

**Comment by davidscn** [comment]
> Do you want to write a short changelog entry in the `doc/news/changes/minor` section? I think this is useful information for all users. (I can also merge as is and you/we open a follow-up PR.)

I added an entry, but feel free to edit it as I'm not familiar with the changelog style used. Also, the actual fix was provided by @kronbichler, so I'm also fine if you put your name instead.
