### PR TITLE
Use std::string in SmartPointer and Subscriptor interface

### LINKED ISSUE #7892: Heap use after free in ParameterAcceptor::ParameterAcceptor(const std::string &name)
In `source/base/parameter_acceptor.cc`:
```
 32 ParameterAcceptor::ParameterAcceptor(const std::string &name)                    
 33   : acceptor_id(class_list.size())                                               
 34   , section_name(name)                                                           
 35 {                                                                                
 36   SmartPointer<ParameterAcceptor> pt(                                            
 37     this, boost::core::demangle(typeid(*this).name()).c_str());                  
 38   class_list.push_back(pt);                                                      
 39 }
```
Line 37 causes a heap use after free due to `SmartPointer` storing the C-style string pointer: `include/deal.II/base/smartpointer.h`:
```
237 template <typename T, typename P>                                                
238 inline SmartPointer<T, P>::SmartPointer(T *t, const char *id)                    
239   : t(t)                                                                         
240   , id(id)                                                                       
...
```

I suggest we bite the bullet and convert the C-style string handling in `SmartPointer` to `std::string`. In release mode everything gets thrown out anyway... I am happy to make a pull request with this change later this week. Before I proceed, opinions?

Minimal example:
```
#include <deal.II/base/parameter_acceptor.h>

class Foo : public dealii::ParameterAcceptor
{
};

int main()
{
  Foo foo;
}
```
Compile and link with clang and `-fsanitize=address -fsanitize-address-use-after-scope`.

```
=================================================================
==14582==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300001d950 at pc 0x00000043a72d bp 0x7ffeef1e5bb0 sp 0x7ffeef1e5338
READ of size 2 at 0x60300001d950 thread T0
    #0 0x43a72c in strcmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-8.0.0/work/compiler-rt-8.0.0.src/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:442:3
    #1 0x7f576a4a458b in dealii::Subscriptor::MapCompare::operator()(char const*, char const*) const /var/tmp/portage/sci-libs/dealii-9999/work/dealii-9999/include/deal.II/base/subscriptor.h:234:14
    #2 0x7f576a4a4525 in std::_Rb_tree<char const*, std::pair<char const* const, unsigned int>, std::_Select1st<std::pair<char const* const, unsigned int> >, dealii::Subscriptor::MapCompare, std::allocator<std::pair<char const* const, unsigned int> > >::_M_lower_bound(std::_Rb_tree_node<std::pair<char const* const, unsigned int> >*, std::_Rb_tree_node_base*, char const* const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_tree.h:1888:7
    #3 0x7f576a4a448f in std::_Rb_tree<char const*, std::pair<char const* const, unsigned int>, std::_Select1st<std::pair<char const* const, unsigned int> >, dealii::Subscriptor::MapCompare, std::allocator<std::pair<char const* const, unsigned int> > >::find(char const* const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_tree.h:2539:22
    #4 0x7f576a4a3343 in std::enable_if<std::is_same<char const*, char const*>::value, void>::type dealii::Subscriptor::subscribe<char const*>(std::atomic<bool>*, char const*) const /var/tmp/portage/sci-libs/dealii-9999/work/dealii-9999/source/base/subscriptor.cc:142:33
    #5 0x7f576a41a2f8 in void std::vector<dealii::SmartPointer<dealii::ParameterAcceptor, void>, std::allocator<dealii::SmartPointer<dealii::ParameterAcceptor, void> > >::_M_realloc_insert<dealii::SmartPointer<dealii::ParameterAcceptor, void> const&>(__gnu_cxx::__normal_iterator<dealii::SmartPointer<dealii::ParameterAcceptor, void>*, std::vector<dealii::SmartPointer<dealii::ParameterAcceptor, void>, std::allocator<dealii::SmartPointer<dealii::ParameterAcceptor, void> > > >, dealii::SmartPointer<dealii::ParameterAcceptor, void> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/vector.tcc:436:4
    #6 0x7f576a4182a3 in dealii::ParameterAcceptor::ParameterAcceptor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /var/tmp/portage/sci-libs/dealii-9999/work/dealii-9999/source/base/parameter_acceptor.cc:38:14
    #7 0x5058d0 in Foo::Foo() /home/tamiko/workspace/step/step.cc:3:7
    #8 0x50545b in main /home/tamiko/workspace/step/step.cc:9:7
    #9 0x7f574c5494fa in __libc_start_main (/usr/lib64/libc.so.6+0x244fa)
    #10 0x4235a9 in _start (/home/tamiko/workspace/step/step+0x4235a9)

0x60300001d950 is located 0 bytes inside of 26-byte region [0x60300001d950,0x60300001d96a)
freed by thread T0 here:
    #0 0x503072 in operator delete(void*) /var/tmp/portage/sys-libs/compiler-rt-sanitizers-8.0.0/work/compiler-rt-8.0.0.src/lib/asan/asan_new_delete.cc:167:3
    #1 0x506cd9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy(unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:226:9
    #2 0x50545b in main /home/tamiko/workspace/step/step.cc:9:7
    #3 0x7f574c5494fa in __libc_start_main (/usr/lib64/libc.so.6+0x244fa)

previously allocated by thread T0 here:
    #0 0x502432 in operator new(unsigned long) /var/tmp/portage/sys-libs/compiler-rt-sanitizers-8.0.0/work/compiler-rt-8.0.0.src/lib/asan/asan_new_delete.cc:106:3
    #1 0x508c85 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.tcc:219:14
    #2 0x508b37 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:516:9
    #3 0x50545b in main /home/tamiko/workspace/step/step.cc:9:7
    #4 0x7f574c5494fa in __libc_start_main (/usr/lib64/libc.so.6+0x244fa)

SUMMARY: AddressSanitizer: heap-use-after-free /var/tmp/portage/sys-libs/compiler-rt-sanitizers-8.0.0/work/compiler-rt-8.0.0.src/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:442:3 in strcmp
Shadow bytes around the buggy address:
  0x0c067fffbad0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbaf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbb00: 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x0c067fffbb10: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
=>0x0c067fffbb20: 00 fa fa fa fd fd fd fd fa fa[fd]fd fd fd fa fa
  0x0c067fffbb30: 00 00 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbb40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbb50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbb60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffbb70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==14582==ABORTING
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7892. Using `std::string` instead of `const char *` in `SmartPointer` and `Subscriptor` is just easier.

### CODE REVIEW

File: source/base/subscriptor.cc [hunk 1]
```diff
@@ -126,18 +126,17 @@ Subscriptor::operator=(Subscriptor &&s) noexcept
...
+                       const std::string &      id) const
 {
   std::lock_guard<std::mutex> lock(mutex);
 
   if (object_info == nullptr)
     object_info = &typeid(*this);
   ++counter;
 
-  const char *const name = (id != nullptr) ? id : unknown_subscriber;
+  const std::string name = (id != "") ? id : unknown_subscriber;
```
Comment (drwells) [inline source/base/subscriptor.cc]: Could we go ahead and just use `std::string::empty()` here?

File: tests/base/unsubscribe_subscriptor.debug.output.intel [hunk 2]
```diff
@@ -3,7 +3,7 @@ DEAL::Exception: ExcNoSubscriber(object_info->name(), name)
 DEAL::
 --------------------------------------------------------
 An error occurred in file <subscriptor.cc> in function
-    void dealii::Subscriptor::unsubscribe(std::atomic<bool> *, const char *) const
+    void dealii::Subscriptor::unsubscribe(std::atomic<bool> *, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &) const
```
Comment (drwells) [inline tests/base/unsubscribe_subscriptor.debug.output.intel]: Nice catch!

File: source/base/data_out_base.cc [hunk 3]
```diff
@@ -5345,7 +5345,7 @@ namespace DataOutBase
         // underscores unless a vector name has been specified
         out << "VECTORS ";
 
-        if (std::get<2>(nonscalar_data_range) != "")
+        if (!std::get<2>(nonscalar_data_range).empty())
```
Comment (drwells) [inline source/base/data_out_base.cc]: Thanks for editing these too. I don't mind including them in the PR as long as they stay in a separate commit.

File: source/base/subscriptor.cc [hunk 4]
```diff
@@ -126,18 +126,17 @@ Subscriptor::operator=(Subscriptor &&s) noexcept
...
+                       const std::string &      id) const
 {
   std::lock_guard<std::mutex> lock(mutex);
 
   if (object_info == nullptr)
     object_info = &typeid(*this);
   ++counter;
 
-  const char *const name = (id != nullptr) ? id : unknown_subscriber;
+  const std::string name = (!id.empty()) ? id : unknown_subscriber;
```
Comment (drwells) [inline source/base/subscriptor.cc]: Its not critical, but would you mind switching the order on these so that we don't need the negation? i.e.,
```cpp
id.empty() ? unknown_subscriber : id;
```
Furthermore, could we use a value here and move it into the counter map below?

**Comment by masterleinad** [comment]
@drwells Is there more you would like me to change? Maybe, I also misunderstood "could we use a value here and move it into the counter map below".

**Comment by drwells** [comment]
I am not sure what I was thinking when I wrote that yesterday; this looks fine.

**Comment by tjhei** [comment]
```
In file included from /jenkins/workspace/dealii_PR-7901/tests/bits/block_matrix_array_01.cc:21:0:
/jenkins/workspace/dealii_PR-7901/include/deal.II/lac/block_matrix_array.h: In instantiation of ‘void dealii::BlockMatrixArray<number, BlockVectorType>::print_latex(StreamType&) const [with StreamType = dealii::LogStream; number = double; BlockVectorType = dealii::BlockVector<double>]’:
/jenkins/workspace/dealii_PR-7901/tests/bits/block_matrix_array_01.cc:45:28:   required from here
/jenkins/workspace/dealii_PR-7901/include/deal.II/lac/block_matrix_array.h:612:11: error: ‘using value_type = class std::__cxx11::basic_string<char> {aka class std::__cxx11::basic_string<char>}’ has no member named ‘is_empty’
       if (!array(m->row, m->col).is_empty() && m->prefix >= 0)
           ^
``` (https://jenkins.tjhei.info/blue/organizations/jenkins/dealii/detail/PR-7901/4/pipeline#step-69-log-1831)

**Comment by drwells** [comment]
It looks like the tester is stuck at
```
[669/676] Linking CXX executable bin/step-23.debug
```

**Comment by drwells** [comment]
This time the link failed.

**Comment by tjhei** [comment]
one more time for good luck: /rebuild

**Comment by tamiko** [comment]
*fingers crossed* I really need this :-)

**Comment by tjhei** [comment]
main tests passed, clang-tidy failed, rerunning now: https://jenkins.tjhei.info/blue/organizations/jenkins/dealii-tidy/detail/PR-7901/10/pipeline
