### PR TITLE
Fix for MGConstrainedDoFs behavior in presence of refinement edges across periodic boundary conditions

### LINKED ISSUE #7046: MGConstrainedDoFs::initialize does not check if cells are of same level
When constructing level constraints, MGConstrainedDoFs uses `CellAccessor::periodic_neighbor` to find face pairs which must be identically constrained onto each other. However, this function can return a cell of the same level or one level coarser (which should be covered by the hanging node constraints of the Multigrid engine). In the second case the constraint assembly will fail because the MG DoFs for the neighboring cell are not available on the present level (or, in a distributed setting, potentially because it is artificial).

A simple fix should be to change line 213 in include/deal.II/multigrid/mg_constrained_dofs.h from
`if (cell->has_periodic_neighbor(f))`
to
`if (cell->has_periodic_neighbor(f) && cell -> periodic_neighbor(f) -> level() == cell -> level())`
but I didn't have time to test that yet.

The MWE

	#include <deal.II/grid/tria.h>
	#include <deal.II/grid/grid_tools.h>
	#include <deal.II/grid/grid_generator.h>
	#include <deal.II/dofs/dof_handler.h>
	#include <deal.II/multigrid/mg_constrained_dofs.h>

	#include <vector>

	constexpr int DIM = 2;

	using namespace dealii;

	int main() {
		typedef Triangulation<DIM> Tria;
		// Create triangulation
		Tria tria(
			Tria::limit_level_difference_at_vertices
		);

		// Create coarse grid
		GridGenerator::hyper_cube(tria, -1, 1, true);

		// Create periodic boundary along x axis
		std::vector<GridTools::PeriodicFacePair<Tria::cell_iterator>> face_pairs;

		GridTools::collect_periodic_faces(
			tria,
			0, 1,
			0,
			face_pairs
		);

		tria.add_periodicity(face_pairs);

		// Refine once and then refine the corner again
		tria.refine_global(1);

		tria.begin_active() -> set_refine_flag();
		tria.prepare_coarsening_and_refinement();
		tria.execute_coarsening_and_refinement();
		
		// Assemble DoFs
		DoFHandler<DIM> dof_handler(tria);
		FE_Q<DIM> fe_q(1);

		dof_handler.distribute_dofs(fe_q);
		dof_handler.distribute_mg_dofs();

		// Try to assemble MGConstrainedDofs
		MGConstrainedDoFs constrained_dofs;
		constrained_dofs.initialize(dof_handler);

		return 0;
	}

fails on my system (spack build from the development branch) with

	--------------------------------------------------------
	An error occurred in line <1587> of file </home/alexander/git_repos/spack/opt/spack/linux-ubuntu17.10-x86_64/gcc-7.2.0/dealii-develop-urwe6fvrjadj3b6pzx62d5ghb4dndjvx/include/deal.II/dofs/dof_handler.h> in function
		dealii::types::global_dof_index dealii::DoFHandler<dim, spacedim>::MGVertexDoFs::get_index(unsigned int, unsigned int, unsigned int) const [with int dim = 2; int spacedim = 2; dealii::types::global_dof_index = unsigned int]
	The violated condition was: 
		(level >= coarsest_level) && (level <= finest_level)
	Additional information: 
		The given level 2 is not in the valid range!

	Stacktrace:
	-----------
	#0  ./mwe: void dealii::internal::DoFAccessorImplementation::get_mg_dof_indices<dealii::DoFHandler<2, 2>, false>(dealii::DoFAccessor<1, dealii::DoFHandler<2, 2>, false> const&, int, std::vector<unsigned int, std::allocator<unsigned int> >&, unsigned int)
	#1  ./mwe: void dealii::MGConstrainedDoFs::initialize<2, 2>(dealii::DoFHandler<2, 2> const&)
	#2  ./mwe: main
	--------------------------------------------------------

### PR DESCRIPTION
**Pull request by alexrobomind**
This pull request fixes the problems detailed in issue #7046 and adds a test for them.

One thing I would like to put up for discussion is whether the way of making an extra copy of `MGTools::extract_inner_interface_dofs` (here named `extract_inner_or_periodic_interface_dofs`) is really the way to go or if `extract_inner_interface_dofs` (and `extract_non_interface_dofs`) should be adapted to new behavior in presence of periodic boundary conditions (which would be the cleaner solution but break the interface).

Where is `MGTools::extract_non_interface_dofs` actually used?

Todo:

- [x] Indentation
- [x]  Add changelist

edit (@masterleinad): Make sure that this closes #7046.

### CODE REVIEW

**Comment by masterleinad** [comment]
`MGTools::extract_non_interface_dofs` was first introduced in https://github.com/dealii/dealii/commit/843d6fe146f3b16bdece05fcd13711f675af8a5e and https://github.com/dealii/dealii/commit/d4681a29fd10d21984dd08436cc7d161f337bb1b where it was used inside of `MGConstrainedDoFs::initialize` to initialize `std::vector<std::set<types::global_dof_index> > non_refinement_edge_indices;`. This latter variable was removed in https://github.com/dealii/dealii/commit/1e88b5536929514e4ea7d14ef2fb6a32a0dfdca3 along with a few others. Currently, `MGTools::extract_non_interface_dofs` is not used anywhere. Hence, we should just remove that function in the long run. I will address that in a PR.

The approach we are currently following with respect to periodic boundary conditions is to just assume that periodic boundary faces should be treated as internal faces after `Triangulation::add_periodicity` has been called. For more fine-grained control (on a rather low level) there are both the `*neighbor*` and the `*periodic_neighbor*` functions.
As for `MGTools::extract_inner_interface_dofs`, I would simply update the function to address periodic faces as well rather than duplicating all the code.

**Comment by masterleinad** [comment]
See #7051.

File: tests/multigrid/dof_06.cc [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+    ExcMessage(
+      "Please use a finite element with at least 1 DoF for this test"));
+
+  std::vector<types::global_dof_index> mg_dofs(
+    face->get_fe(0).n_dofs_per_face());
+  face->get_mg_dof_indices(level, mg_dofs);
+
+  // Print face DoFs
+  std::cout << mg_dofs[0];
+  for (unsigned int i_dof = 1; i_dof < mg_dofs.size(); ++i_dof)
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: You could also just use a range-based loop here as well:
```
for (const auto mg_dof : mg_dofs)
  deallog << ", " << mg_dof;
```

File: tests/multigrid/dof_06.cc [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+          for (unsigned int i_face = 0; i_face < 2 * dim; ++i_face)
+            {
+              if ((level_cell->at_boundary(i_face) &&
+                   !level_cell->has_periodic_neighbor(i_face)) ||
+                  level_cell->neighbor_or_periodic_neighbor(i_face)->level() ==
+                    level_cell->level())
+                continue;
+
+              // Get face
+              auto face = level_cell->face(i_face);
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: This could be `const` as well.

File: tests/multigrid/dof_06.cc [hunk 3]
```diff
@@ -0,0 +1,172 @@
...
+
+      // Print faces that connect to coarser DoF
+      std::cout << "  Faces neighboring coarser cells:" << std::endl;
+      for (typename DoFHandler<dim>::cell_iterator level_cell =
+             dof_handler.begin(level);
+           level_cell != dof_handler.end(level);
+           ++level_cell)
+        {
+          // Iterate over all faces
+          for (unsigned int i_face = 0; i_face < 2 * dim; ++i_face)
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: We prefer `GeometryInfo<dim>::faces_per_cell` over the explicit `2*dim`. Would you mind changing that here and below?

File: tests/multigrid/dof_06.cc [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+      constrained_dofs.get_refinement_edge_indices(level).print(std::cout);
+      std::cout << std::endl;
+
+      // Print faces that have periodic neighbors
+      std::cout << "  Faces having periodic neighbors of same level:"
+                << std::endl;
+      for (typename DoFHandler<dim>::cell_iterator level_cell =
+             dof_handler.begin(level);
+           level_cell != dof_handler.end(level);
+           ++level_cell)
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: This can again be a range-based loop.

File: tests/multigrid/dof_06.cc [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+        {
+          // Iterate over all faces
+          for (unsigned int i_face = 0; i_face < 2 * dim; ++i_face)
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: `GeometryInfo<dim>::faces_per_cell`

File: tests/multigrid/dof_06.cc [hunk 6]
```diff
@@ -0,0 +1,172 @@
...
+              // Each side only once
+              if (level_cell->index() > neighbor_cell->index())
+                continue;
+
+              unsigned int neighbor_i_face =
+                level_cell->periodic_neighbor_face_no(i_face);
+
+              // Get face
+              auto face          = level_cell->face(i_face);
+              auto neighbor_face = neighbor_cell->face(neighbor_i_face);
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: `const auto face` and `const auto neighbor_face`.

File: tests/multigrid/dof_06.cc [hunk 7]
```diff
@@ -0,0 +1,172 @@
...
+
+      // Print constraint matrix
+      std::cout << "  Constraint matrix:" << std::endl;
+      constrained_dofs.get_level_constraint_matrix(level).print(std::cout);
+    }
+}
+
+int
+main()
+{
```
Comment (masterleinad) [inline tests/multigrid/dof_06.cc]: Please add `initlog();` here.

File: tests/multigrid/dof_06.output [hunk 8]
```diff
@@ -0,0 +1,88 @@
+--- DIM 2 OK ---
```
Comment (masterleinad) [inline tests/multigrid/dof_06.output]: I believe that this is not the output that is generated by running `ctest`.
For generating the conforming output, run 
```
$ make setup_tests_multigrid
```
and
```
$ ctest -R "multigrid/dof_06"
```
in your build directory and copy the output via
```
cp tests/multigrid/dof_06.debug/output ${SOURCE_DIR}/tests/multigrid/dof_06.output
```
to your source directory, i.e. this file.

Comment (alexrobomind) [reply tests/multigrid/dof_06.output]: That's exactly what I did, I just ran the test using ctest and it passed.

File: tests/multigrid/dof_06.cc [hunk 9]
```diff
@@ -0,0 +1,172 @@
...
+      "Please use a finite element with at least 1 DoF for this test"));
+
+  std::vector<types::global_dof_index> mg_dofs(
+    face->get_fe(0).n_dofs_per_face());
+  face->get_mg_dof_indices(level, mg_dofs);
+
+  // Print face DoFs
+  std::cout << mg_dofs[0];
+  for (unsigned int i_dof = 1; i_dof < mg_dofs.size(); ++i_dof)
+    std::cout << ", " << mg_dofs[i_dof];
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: I initially used deallog, but AffineConstraints only prints to std::ostream.

File: tests/multigrid/dof_06.output (hunk 8 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.output]: Will address all points that I did not further comment on directly, the two I commented on need some discussion.

File: tests/multigrid/dof_06.cc (hunk 1 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: How can i exclude the first element from such a loop?

File: tests/multigrid/dof_06.cc [hunk 10]
```diff
@@ -0,0 +1,172 @@
+#include <deal.II/base/exceptions.h>
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Do you mean "../tests.h"?

File: tests/multigrid/dof_06.cc [hunk 11]
```diff
@@ -0,0 +1,172 @@
...
+#include <deal.II/dofs/dof_handler.h>
+
+#include <deal.II/grid/grid_generator.h>
+#include <deal.II/grid/grid_tools.h>
+#include <deal.II/grid/tria.h>
+
+#include <deal.II/multigrid/mg_constrained_dofs.h>
+
+#include <vector>
+
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done

File: tests/multigrid/dof_06.cc [hunk 12]
```diff
@@ -0,0 +1,172 @@
...
+constexpr int DIM = 2;
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done

File: tests/multigrid/dof_06.cc [hunk 13]
```diff
@@ -0,0 +1,172 @@
...
+  std::cout << mg_dofs[0];
+  for (unsigned int i_dof = 1; i_dof < mg_dofs.size(); ++i_dof)
+    std::cout << ", " << mg_dofs[i_dof];
+}
+
+template <int dim>
+void
+check()
+{
+  typedef Triangulation<dim> Tria;
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done

File: tests/multigrid/dof_06.cc [hunk 14]
```diff
@@ -0,0 +1,172 @@
...
+  for (unsigned int level = 0; level < tria.n_global_levels(); ++level)
+    {
+      std::cout << "Level " << level << ": " << std::endl;
+
+      // Print faces that connect to coarser DoF
+      std::cout << "  Faces neighboring coarser cells:" << std::endl;
+      for (typename DoFHandler<dim>::cell_iterator level_cell =
+             dof_handler.begin(level);
+           level_cell != dof_handler.end(level);
+           ++level_cell)
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done

File: tests/multigrid/dof_06.cc [hunk 15]
```diff
@@ -0,0 +1,172 @@
...
+
+#include <vector>
+
+constexpr int DIM = 2;
+
+using namespace dealii;
+
+template <typename FaceType>
+void
+print_face(const FaceType &face, unsigned int level)
```
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done in 2nd commit.

File: tests/multigrid/dof_06.cc (hunk 2 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done.

File: tests/multigrid/dof_06.cc (hunk 3 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done ( unless I missed one).

File: tests/multigrid/dof_06.cc (hunk 7 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done

File: tests/multigrid/dof_06.cc (hunk 6 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done.

File: tests/multigrid/dof_06.cc (hunk 5 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Done (I think, messed up the lines already by the for loop change)

File: tests/multigrid/dof_06.cc (hunk 4 above)
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: I think that's done too.

File: tests/multigrid/dof_06.cc (hunk 10 above)
[the remark this answers is not in the document]
Comment (masterleinad) [reply tests/multigrid/dof_06.cc]: No, it's:
```
 // ---------------------------------------------------------------------
 //
 // Copyright (C) 2018 by the deal.II authors
 //
 // This file is part of the deal.II library.
 //
 // The deal.II library is free software; you can use it, redistribute
 // it, and/or modify it under the terms of the GNU Lesser General
 // Public License as published by the Free Software Foundation; either
 // version 2.1 of the License, or (at your option) any later version.
 // The full text of the license can be found in the file LICENSE.md at
 // the top level directory of deal.II.
 //
 // ---------------------------------------------------------------------
```

File: tests/multigrid/dof_06.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (masterleinad) [reply tests/multigrid/dof_06.cc]: Yes, you can get a suitable object via `deallog.get_file_stream()`.

File: tests/multigrid/dof_06.output (hunk 8 above)
Comment (masterleinad) [reply tests/multigrid/dof_06.output]: > That's exactly what I did, I just ran the test using ctest and it passed.

Great!

File: tests/multigrid/dof_06.cc (hunk 1 above)
Comment (masterleinad) [reply tests/multigrid/dof_06.cc]: Ah, I missed that you want to treat the first element special. Of course, you could use newlines instead
```
for (const auto mg_dof : mg_dofs)
  deallog << mg_dof <<'\n';
```
or just leave as is. Either is fine.

File: tests/multigrid/dof_06.cc (hunk 10 above)
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Oh, I misunderstood that. Sorry.

File: tests/multigrid/dof_06.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (alexrobomind) [reply tests/multigrid/dof_06.cc]: Nice, didn't know that.

**Comment by alexrobomind** [comment]
I **think** all of your comments should be addressed now. If there are no more comments on the file contents, I would rename the test to 'constrained_dofs_05' (overlooked that category when first browsing the directory), add a changelog entry and squash the commits.

**Comment by masterleinad** [comment]
Yes, that looks good. Thanks for addressing my pedantic comments!

**Comment by alexrobomind** [comment]
Nothing wrong with keeping the code clean. It's one of the things I like about this library (plus, I learn a few new tricks from those comments as well).

**Comment by alexrobomind** [comment]
OK, that's pretty much it. Could someone please schedule the tests so that I know whether I have to do some more work on this please? I don't want to squash the commits until then.

**Comment by masterleinad** [comment]
Sure. If you wait with squashing, we need to wait for the testers to finish twice though.

/run-tests

**Comment by alexrobomind** [comment]
> Sure.

I'm not sure what you referred to here. Should I update `MGTools::extract_non_interface_dofs`? It is going to be deprecated in #7051 anyway.

**Comment by masterleinad** [comment]
I meant that I can start the testers. When you edit a comment no notifications are sent. Hence, I didn't realize that you added another question. Most often it is better to just add another comment.

**Comment by masterleinad** [comment]
> Wait, I forgot something: Even though it's being deprecated, should I still update MGTools::extract_non_interface_dofs as well?

Yes, please do that while squashing (but let us now wait for the testers first).

**Comment by masterleinad** [comment]
@alexrobomind The testers went through with no issues reported.

**Comment by alexrobomind** [comment]
Nice. I will then adapt extract_non_interface_dofs later when I have time (I'm in the middle of an experimental session right now) and squash again.

**Comment by alexrobomind** [comment]
- Updated extract_non_interface_dofs
- make indent
- Squashed
- Checked build & new test again (no change)

**Comment by alexrobomind** [comment]
From my side this is all. I think if the test system says OK, this can be merged, unless someone requests additional changes.

**Comment by masterleinad** [comment]
Looks good to me!

**Comment by alexrobomind** [comment]
@masterleinad 
Thank you for doing the review and supervision for this PR.

**Comment by masterleinad** [comment]
Thank you again for fixing!

**Comment by masterleinad** [comment]
I edited your initial pull request description to use one of GitHub`s keywords for closing #7046 when this PR is merged.
