### PR TITLE
Fix parameter handler dos files

### LINKED ISSUE #1691: Make ParameterHandler deal with DOS/Unix/Mac files more gracefully
If you feed ParameterHandler a DOS file on a Mac, you get obscure error messages about parameters and subsections not being declared that have in fact been declared. The problem is that what ParameterHandler actually sees is the section name *plus the DOS ending*, but the error message does not actually reflect this, and consequently it is all very confusing.

We should handle this more gracefully.

### PR DESCRIPTION
**Pull request by drwells**
This should close #1691. The issue was in the function `Utilities::trim`, which left hanging `\r`s at the end of lines. I resolved this by writing a more general `Utilities::trim_whitespace` function, which inspects the current locale to figure out what counts as a whitespace character or not.

### CODE REVIEW

**Comment by bangerth** [comment]
Nice. Any reason not to extend the existing function?

**Comment by natashasharma** [comment]
E

File: source/base/utilities.cc [hunk 1]
```diff
@@ -123,6 +124,37 @@ namespace Utilities
...
+  trim_whitespace(const std::string &input)
+  {
+    std::string::size_type left = 0;
+    std::string::size_type right = input.size() - 1;
+
+    std::locale current_locale;
+
+    for (; left < input.size(); ++left)
+      {
+        if (!std::isspace(input[left], current_locale))
```
Comment (tjhei) [inline source/base/utilities.cc]: this should be equivalent to ```std::isspace(input[left])```

**Comment by tjhei** [comment]
Are you sure the line endings of the .prm are not modified by git upon commit and/or checkout? Can we test loading a .prm from a string with these in there?

**Comment by drwells** [comment]
@bangerth I am probably being too careful, but that would change the functionality of `trim` slightly (which only does spaces and not line breaks) and might break things.

@tjhei Good question. I am only *pretty sure* that git will not change the line endings with our current configuration settings (it is not in `.gitattributes` and we have a few `DOS` files in the repository right now). Regardless, those policies might change, so I should fix the test in the way you recommend.

File: source/base/utilities.cc (hunk 1 above)
Comment (drwells) [inline source/base/utilities.cc]: Is that always true? The C++ docs say that the current locale may define extra whitespace characters not in the standard one. I am probably being too conservative here. Would it be better to ignore that problem and just use the `C` locale whitespace characters?

**Comment by drwells** [comment]
In response to @tjhei's remarks I now build the parameter file with a string stream. Since the test does not use the IO facilities it should not convert line endings on any platform.

File: source/base/utilities.cc (hunk 1 above)
Comment (tjhei) [inline source/base/utilities.cc]: http://en.cppreference.com/w/cpp/string/byte/isspace says "classified by the currently installed C locale" which looks like is the same thing you are doing or not? Looking at the table at the bottom of the page it looks like this is exactly what you want...

**Comment by tjhei** [comment]
> I am only pretty sure that git will not change the line endings with our current configuration settings (it is not in .gitattributes and we have a few DOS files in the repository right now)

If a file is stored in text mode (like the .output files in the test directory), it will be converted to windows line endings if you check them out on windows, because the default is to convert to local encoding.

File: include/deal.II/base/utilities.h [hunk 2]
```diff
@@ -204,6 +204,14 @@ namespace Utilities
   std::string trim(const std::string &input);
 
   /**
+   * Return a string with all whitespace at the beginning and end of @p input
+   * removed. This function uses the current locale to determine what counts
```
Comment (tjhei) [inline include/deal.II/base/utilities.h]: can you please add "including \t,\n,\r"?

**Comment by drwells** [comment]
@tjhei Does this mean that all of the parameter handler tests fail on windows currently?

@tjhei I added the extra documentation.

File: source/base/utilities.cc (hunk 1 above)
Comment (drwells) [inline source/base/utilities.cc]: Yes, but my intent was to use the current locale, which may define things as whitespace which the current C locale does not. The 'C locale' is really a POSIX standard for character definitions [1]. I believe "the currently installed C locale" may be different from the global locale C++ uses for this reason. Internationalization is hard and I might still not understand how this whole thing works.

Regardless, I think it would be best to ignore the current locale alltogether and do what you recommend (it is not like this bit of code can handle generic unicode spaces anyway). 

[1] http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap07.html

**Comment by bangerth** [comment]
On 12/04/2015 06:49 AM, David Wells wrote:
> @bangerth <https://github.com/bangerth> I am probably being too careful, but
> that would change the functionality of |trim| slightly (which only does spaces
> and not line breaks) and might break things.

I don't think it's worth worrying about. It only changes cases that I would 
currently consider broken (namely, \r and \n in strings -- nobody in their 
right mind would have relied on the current behavior of the function for these 
characters in strings).

**Comment by tjhei** [comment]
> Does this mean that all of the parameter handler tests fail on windows currently?

1. Tests are not really working on windows anyways. :-)
2. This should work, because the std library will drop the native line encodings automatically and pretend you are just getting \n (and will add \r when you write to a file).

**Comment by drwells** [comment]
@bangerth Fair enough. I will add an imcompatibility notice to make myself feel better.

I have made all the recommended changes.

**Comment by tjhei** [comment]
great, thanks!
