### PR TITLE
Fix erroneous assert and add a test

### LINKED ISSUE #5376: DoFRenumbering::subdomain_wise fails with p::s::Tria
In subdomain_wise, you allocate array like that

https://github.com/dealii/dealii/blob/78b76649de62dae7513458922076c67676f76cd3/source/dofs/dof_renumbering.cc#L1881

Later, the function calls renumber_dofs, which has the following assert

https://github.com/dealii/dealii/blob/78b76649de62dae7513458922076c67676f76cd3/source/dofs/dof_handler.cc#L1107

which gets triggered for shared triangulation ran on > 1 MPI processes. Is this intented?

### PR DESCRIPTION
**Pull request by agrayver**
Fixes #5376

### CODE REVIEW

**Comment by davydden** [comment]
please run indentation script `./contrib/utilities/indent` with `astyle@2.04` in path.

**Comment by tjhei** [comment]
Did you check if this breaks the parallel::distributed renumberings like tests/mpi/p4est_2d_renumber* ?

**Comment by agrayver** [comment]
Calling DoFRenumbering::subdomain_wise with p::d::Triangulation does not work anyway: 

> An error occurred in line <1422> of file </home/agrayver/lib/dealii/source/dofs/dof_tools.cc> in function
>     void dealii::DoFTools::get_subdomain_association(const DoFHandlerType&, std::vector<unsigned int>&) [with DoFHandlerType = dealii::DoFHandler<2, 2>]
> The violated condition was: 
>     (dynamic_cast<const parallel::distributed:: Triangulation<DoFHandlerType::dimension,DoFHandlerType::space_dimension> *> (&dof_handler.get_triangulation()) == nullptr)
> Additional information: 
>     For parallel::distributed::Triangulation objects and associated DoF handler objects, asking for any subdomain other than the locally owned one does not make sense.

**Comment by tjhei** [comment]
> Calling DoFRenumbering::subdomain_wise with p::d::Triangulation does not work anyway:

No, but you modify ``renumber_dofs()`` which is used by other functions like ``component_wise``, which are implemented for ``p::d::Tria``. I assume that your change will break that functionality.

File: source/dofs/dof_handler.cc [hunk 1]
```diff
@@ -1104,7 +1104,7 @@ DoFHandler<dim,spacedim>::renumber_dofs (const std::vector<types::global_dof_ind
 {
   Assert(levels.size()>0, ExcMessage("You need to distribute DoFs before you can renumber them."));
 
-  AssertDimension (new_numbers.size(), n_locally_owned_dofs());
+  AssertDimension (new_numbers.size(), n_dofs());
```
Comment (bangerth) [inline source/dofs/dof_handler.cc]: This change cannot be correct. I'm pretty sure that the function documents that it wants a vector of length `n_locally_owned_dofs()`, which is the only reasonable thing in the parallel distributed context where we may have billions of unknowns and we could not possibly create a vector of that length.

So the function must expect a vector of that length in the parallel distributed case.

The `parallel::shared::Triangulation` is a corner case because there every processor has knowledge about all DoFs. So one could in principle think of doing something like this:
* If p::d::Triangulation, then require `n_locally_owned_dofs()`
* If p::s::Triangulation, then we could debate which one is correct
* If sequential Triangulation, then the two are the same anyway.

To decide what to do in the second case, your testcase seems to suggest that calling `policy->renumber_dofs()` works with a vector of size `n_dofs()` -- is this correct?

Comment (bangerth) [reply source/dofs/dof_handler.cc]: On second thought, since `p::s::Triangulation` originated in a scheme where the DoFHandler knows everything and only the matrix and vectors are distributed, I think that it makes sense to expect that the function takes a vector of size `n_dofs()`. So I think what is necessary is to make the assertion check different things depending on what kind of triangulation is being used. You can use that with a `dynamic_cast`, for which I am pretty sure there are examples in this file.

**Comment by agrayver** [comment]
> calling policy->renumber_dofs() works with a vector of size n_dofs() -- is this correct?

Yes, this is correct. 

> So I think what is necessary is to make the assertion check different things depending on what kind of triangulation is being used

Ok, I tried. Can you have a look?

**Comment by agrayver** [comment]
Hm, I looked at `ParallelShared::renumber_dofs` and it seems it supports both `n_dofs()` and `n_locally_owned_dofs()` cases:

https://github.com/dealii/dealii/blob/8a638451eb88841dcd4d9f9fe561a1426b253264/source/dofs/dof_handler_policy.cc#L2851-L2859

**Comment by bangerth** [comment]
Ah, very interesting find. Then, indeed, `DoFHandler::renumber_dofs()` should accept both vector lengths when building on a `parallel::shared::Triangulation`.

File: source/dofs/dof_handler.cc [hunk 2]
```diff
@@ -1104,9 +1104,16 @@ DoFHandler<dim,spacedim>::renumber_dofs (const std::vector<types::global_dof_ind
...
-
 #ifdef DEBUG
+  if (dynamic_cast<const parallel::shared::Triangulation< dim, spacedim>*> (&*tria) != nullptr)
+    {
+      AssertDimension (new_numbers.size(), n_dofs());
+    }
+  else if (dynamic_cast<const parallel::distributed::Triangulation< dim, spacedim >*> (&*tria) != nullptr)
+    {
+      AssertDimension (new_numbers.size(), n_locally_owned_dofs());
+    }
```
Comment (bangerth) [inline source/dofs/dof_handler.cc]: add another `else` (no `if`) here where you test the sequential case where the size needs to be `n_dofs()`.

**Comment by bangerth** [comment]
Great, thanks for working through all of this with us!

OK to merge once the tester is happy.

**Comment by bangerth** [comment]
Also, special thanks for thinking of including a test! We can never have enough tests!

**Comment by bangerth** [comment]
Follow-up in #5424.
