### PR TITLE
Use a fixed size data structure for MappingManifold::InternalData::unit_tangentials.

### LINKED ISSUE #2424: Better data structure for Mapping*::InternalDataBase::unit_tangentials
As pointed out in a comment in #2272, the `Mapping*::InternalDataBase::unit_tangentials` fields are stored as vectors-of-vectors, but both dimensions are actually known at compile time. Use a better data structure for this that is cheaper to allocate and access.

In reference to #1198.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes #2424 in the same way as was previously already done in #2471, but for the `MappingManifold` class introduced in #2272.

In reference to #1198.

### CODE REVIEW

File: source/fe/mapping_manifold.cc [hunk 1]
```diff
@@ -160,8 +159,9 @@ initialize_face (const UpdateFlags      update_flags,
                   // points on this face
                   std::fill (unit_tangentials[i].begin(),
                              unit_tangentials[i].end(), tang1);
-                  std::fill (unit_tangentials[nfaces+i].begin(),
-                             unit_tangentials[nfaces+i].end(), tang2);
+                  std::fill (unit_tangentials[GeometryInfo<dim>::faces_per_cell+i].begin(),
+                             unit_tangentials[GeometryInfo<dim>::faces_per_cell+i].end(),
+                             tang2);
```
Comment (drwells) [inline source/fe/mapping_manifold.cc]: Perhaps I am missing something obvious but this indexing looks wrong. In 3D `i` goes from `0` to `5`; hence `GeometryInfo<3>::faces_per_cell + i` can be `11`, but the `unit_tangentials` only has `8` entries.

**Comment by drwells** [comment]
This looks good, though if I am correct in my comment I am a little hesitant to merge this if we need to rewrite something anyway.

File: source/fe/mapping_manifold.cc (hunk 1 above)
Comment (bangerth) [inline source/fe/mapping_manifold.cc]: The array has size faces_per_cell times  (dim-1), so no problem here.

Comment (drwells) [inline source/fe/mapping_manifold.cc]: oh, duh...
