### PR TITLE
Bugfix: DoFHandler connects to Triangulation::Signals only in hp-mode.

### LINKED ISSUE #11768: p::d::SolutionTransfer::deserialize() fails on non-coarse meshes
Hi everybody,

the [attached code](https://github.com/dealii/dealii/files/5997690/serialization.zip) (inspired by [this test](https://github.com/dealii/dealii/blob/master/tests/fullydistributed_grids/solution_transfer_01.cc)) fails if run in parallel.

It shows a simple use of `p::d::SolutionTransfer::{serialize,deserialize}()` for de-serializing a non-coarse `p::d::Triangulation`.

Success or failure depends on the number of MPI cores (on my machine it fails with 6 cores).
The problem arises both in 2D and in 3D, using either deal.II or Trilinos or PETSc distributed vectors and on older deal.II releases.

The code works correctly for `p::f::Triangulation`s or if the serialized triangulation is coarse.

Any clues?

Thanks!

Attachment:
[serialization.zip](https://github.com/dealii/dealii/files/5997690/serialization.zip)

### PR DESCRIPTION
**Pull request by marcfehling**
Closes #11768.

Whenever a `Triangulation` will be cleared, the enumeration of dofs on associated `DoFHandlers` is no longer valid. This PR proposes to also clear the `DoFHandlers` as well.

### CODE REVIEW

**Comment by marcfehling** [comment]
This might break [tests/fullydistributed_grids/solution_transfer_01.cc](https://github.com/dealii/dealii/blob/master/tests/fullydistributed_grids/solution_transfer_01.cc). I'll have a look.

**Comment by marcfehling** [comment]
Test [tests/fullydistributed_grids/solution_transfer_01.cc](https://github.com/dealii/dealii/blob/master/tests/fullydistributed_grids/solution_transfer_01.cc) should fail, but it passes, and I don't know why right now.

If I manually add `dof_handler.clear()` after `triangulation.clear()`, the test fails. Without it, it passes.
It seems like the `clear` signal does not get triggered here. I'll investigate.

File: source/dofs/dof_handler.cc [hunk 1]
```diff
@@ -2006,10 +2006,7 @@ DoFHandler<dim, spacedim>::~DoFHandler()
   this->tria_listeners.clear();
 
   // release allocated memory
-  // virtual functions called in constructors and destructors never use the
-  // override in a derived class
-  // for clarity be explicit on which function is called
-  DoFHandler<dim, spacedim>::clear();
+  clear();
```
Comment (bangerth) [inline source/dofs/dof_handler.cc:2009]: I guess you're changing this because we no longer have classes derived from `DoFHandler`?

File: source/dofs/dof_handler.cc [hunk 2]
```diff
@@ -3044,6 +3041,8 @@ DoFHandler<dim, spacedim>::connect_to_triangulation_signals()
   // connect functions to signals of the underlying triangulation
   this->tria_listeners.push_back(this->tria->signals.create.connect(
     [this]() { this->reinit(*(this->tria)); }));
+  this->tria_listeners.push_back(
+    this->tria->signals.clear.connect([this]() { this->clear(); }));
```
Comment (bangerth) [inline source/dofs/dof_handler.cc:3045]: This looks correct to me. Nothing good can happen if the triangulation is cleared and we still have dangling data.

**Comment by bangerth** [comment]
It might be that the `clear()` signal gets triggered *at the beginning of* `Triangulation::clear()` (which is where it should be in my mind).

**Comment by marcfehling** [comment]
> It might be that the `clear()` signal gets triggered _at the beginning of_ `Triangulation::clear()` (which is where it should be in my mind).

I found the issue. It's because we clear all connections to `Triangulation` signals in non-hp-mode. It's a relic from merging both `DoFHandler` classes. I'm about to prepare a fix.

File: source/dofs/dof_handler.cc (hunk 1 above)
Comment (marcfehling) [reply source/dofs/dof_handler.cc:2009]: Exactly. We can also get rid of most `this` pointers in the implementation.

However, this does not have to be part of this PR. I tend to move it to a separate one.

Comment (bangerth) [reply source/dofs/dof_handler.cc:2009]: That's ok, but it's also fine as is.

**Comment by marcfehling** [comment]
Blocked by #11800.

I had to separate the signal connection in a general and a hp-mode collection. Once we leave hp-mode, only the latter collection will be cleared, while the first one will persist.

`tests/fullydistributed_grids/solution_transfer_01.cc` now fails as expected. I adjusted it to resemble a use case with a fresh `Triangulation`. It works with one process, but still fails with more than one. @elauksap  @peterrum -- Do you have an idea?

**Comment by marcfehling** [comment]
Some more information about the error:
- occurs only on more than 1 MPI process
- happens when updating ghost values after deserialization on [line 110](https://github.com/dealii/dealii/blob/667d1c1d14cc01a2299a0d82f36e4798e78442ba/tests/fullydistributed_grids/solution_transfer_01.cc#L110)
- exception thrown:
```
--------------------------------------------------------
An error occurred in line <635> of file </home/nonfac/f/fehling/raid/dealii/include/deal.II/base/partitioner.templates.h> in function
    void dealii::Utilities::MPI::Partitioner::import_from_ghosted_array_finish(dealii::VectorOperation::values, const dealii::ArrayView<const ElementType, MemorySpaceType>&, const dealii::ArrayView<ElementType, MemorySpace>&, const dealii::ArrayView<ElementType, MemorySpace>&, std::vector<ompi_request_t*, std::allocator<ompi_request_t*> >&) const [with Number = double; MemorySpaceType = dealii::MemorySpace::Host]
The violated condition was: 
    *read_position == Number() || internal::get_abs(locally_owned_array[j] - *read_position) <= internal::get_abs(locally_owned_array[j] + *read_position) * 100000. * std::numeric_limits<typename numbers::NumberTraits< Number>::real_type>::epsilon()
Additional information: 
    Called compress(VectorOperation::insert), but the element received
    from a remote processor, value 0.125, does not match with the value
    0.5153882032022076 on the owner processor 0
--------------------------------------------------------
```

**Comment by marcfehling** [comment]
Closes #11768.

**Comment by elauksap** [comment]
@marcfehling thanks for your work!

I've found out that adding either of the following modifications (lines marked with a `//`) actually makes the test pass:
```
  // Line 78.
  else if (mode == "load")
    {
      triangulation.load(filename);

      triangulation.clear(); //
      triangulation.load(filename); //
    }
```

```
  // Line 108.
  else if (mode == "load")
    {
      triangulation.clear(); //
      triangulation.load(filename); //
      solution_transfer.deserialize(vector);

      vector.update_ghost_values();
    }
```

I have no idea why, it is very strange. I try to investigate further.

File: source/dofs/dof_handler.cc (hunk 2 above)
Comment (bangerth) [reply source/dofs/dof_handler.cc:3055]: I continue to think that this is correct as is. If you want, break this uncontroversial part out into a patch of its own. Let's get the easy pieces out of the way already.

File: source/dofs/dof_handler.cc (hunk 1 above)
Comment (marcfehling) [reply source/dofs/dof_handler.cc:2012]: Hmm, we still have the deprecated `hp::DoFHandler` around that will probably need this. I'll revert it.

**Comment by marcfehling** [comment]
Moved the original PR to #11801.

I left this PR at the current state to keep the comments.

File: source/dofs/dof_handler.cc (hunk 1 above)
Comment (masterleinad) [reply source/dofs/dof_handler.cc]: It really doesn't make a difference in practice. The code is just clearly telling what's happening here (which some static analyzers demanded).

**Comment by bangerth** [comment]
Can you rebase now?

File: include/deal.II/dofs/dof_handler.h [hunk 3]
```diff
@@ -1700,8 +1707,7 @@ class DoFHandler : public Subscriptor
   setup_policy();
 
   /**
-   * Setup connections to refinement signals of the underlying triangulation.
-   * Necessary for the hp-mode.
+   * Setup connections to signals of the underlying triangulation.
```
Comment (bangerth) [inline include/deal.II/dofs/dof_handler.h:1710]: We do this wrongly in many places, but the correct use of the word is "Set up connections...". For sure for verbs, it should be spelled apart. For nouns ("the setup we have here") might be spelled together, though "the set up of these connections" would probably still be apart.

Really not important here, but I've been finding these places all over the library.

File: source/distributed/solution_transfer.cc [hunk 4]
```diff
@@ -137,6 +137,12 @@ namespace parallel
       prepare_for_coarsening_and_refinement(
         const std::vector<const VectorType *> &all_in)
     {
+#  ifdef DEBUG
+      for (unsigned int i = 0; i < all_in.size(); ++i)
+        Assert(all_in[i]->size() == dof_handler->n_dofs(),
```
Comment (bangerth) [inline source/distributed/solution_transfer.cc:142]: I think you can remove the `#ifdef`. The `Assert` expands to nothing in release mode and the compiler can hopefully see that the `all_in.size()` call doesn't change any state of `all_in` so that the whole loop becomes a no-op.

File: source/distributed/solution_transfer.cc [hunk 5]
```diff
@@ -228,8 +234,13 @@ namespace parallel
     SolutionTransfer<dim, VectorType, DoFHandlerType>::interpolate(
       std::vector<VectorType *> &all_out)
     {
+#  ifdef DEBUG
```
Comment (bangerth) [inline source/distributed/solution_transfer.cc:237]: same here

File: source/dofs/dof_handler.cc [hunk 6]
```diff
@@ -2431,10 +2438,10 @@ DoFHandler<dim, spacedim>::set_fe(const hp::FECollection<dim, spacedim> &ff)
         {
           hp_capability_enabled = false;
 
-          // unsubscribe connections to signals
-          for (auto &connection : this->tria_listeners)
+          // unsubscribe connections to signals that are relevant for hp-mode
+          for (auto &connection : this->tria_listeners_for_transfer)
```
Comment (bangerth) [inline source/dofs/dof_handler.cc:2442]: It took me a little bit to see why this is possible -- because you aren't actually in hp mode any more. Maybe say that in the comment: "...that are only relevant for hp-mode, but we only have a single element here" (emphasis on *only*)

File: source/dofs/dof_handler.cc [hunk 7]
```diff
@@ -2510,10 +2517,10 @@ DoFHandler<dim, spacedim>::distribute_dofs(
         {
           hp_capability_enabled = false;
 
-          // unsubscribe connections to signals
-          for (auto &connection : this->tria_listeners)
+          // unsubscribe connections to signals that are relevant for hp-mode
```
Comment (bangerth) [inline source/dofs/dof_handler.cc:2520]: same here

**Review by bangerth — COMMENTED** [review]
Nearly there.

File: source/distributed/solution_transfer.cc (hunk 4 above)
Comment (marcfehling) [reply source/distributed/solution_transfer.cc:142]: I don't have a preference on the `DEBUG` macros here. I like being more explicit about sections that only happen in `DEBUG` mode, but right here and in the beginning of the function it should be obvious. Will comply and remove them!

**Comment by marcfehling** [comment]
This PR still breaks `tests/fullydistributed_grids/solution_transfer_01.cc`.
Once we figured out how to fix it, I will recover the PR from its draft state.

**Comment by marcfehling** [comment]
On the other hand, we could deal with changing `tests/fullydistributed_grids/solution_transfer_01.cc` to resemble an actual use case on a separate PR and get this merged. As @bangerth reviewed this PR already, feel free to start the testsuite.

File: tests/fullydistributed_grids/solution_transfer_01.cc [hunk 8]
```diff
@@ -89,6 +89,7 @@ test(TriangulationType &triangulation)
 
   {
     triangulation.load(filename);
+    dof_handler.distribute_dofs(FE_Q<dim>(2));
```
Comment (bangerth) [inline tests/fullydistributed_grids/solution_transfer_01.cc:92]: Yes, this makes sense. The fact that this worked before is a complete coincidence and it's probably good that you broke this.

**Review by bangerth — APPROVED** [review]
