### PR TITLE
Fix rotation matrix definition in step-18

### LINKED ISSUE #468: Fix rotation matrix as described in step-18
In step 18, the rotation matrix is defined as

 const double rotation[3][3]
= {{
t *axis[0] *axis[0]+c,
t *axis[0] *axis[1]+s *axis[2],
t *axis[0] *axis[2]-s *axis[1]
},
{
t *axis[0] *axis[1]-s *axis[2],
t *axis[1] *axis[1]+c,
t *axis[1] *axis[2]+s *axis[0]
},
{
t *axis[0] *axis[2]+s *axis[1],
t *axis[1] *axis[1]-s *axis[0],
t *axis[2] *axis[2]+c
}
};

However, entry (3,2) should be:
t *axis[1] *axis[2]-s *axis[0],
rather than:
t *axis[1] *axis[1]-s *axis[0],

as can be seen in http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199

You may notice that entry (1,3) disagrees also between step-18 and http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199, however there is a typo in that entry in http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199 and step-18 is correct (as can be verified by checking the previous set of equations preceding the rotation matrix at http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199).

### PR DESCRIPTION
**Pull request by jppelteret**
This PR adds tested functions to compute rotation matrices in 2d and 3d, and uses them in step-18 in preference to the hard-coded versions currently implemented therein.

Fixes #468

**TODO**
- [x] Check documentation of new functions
- [x] Use newly implemented functions in `step-18`
- [x] Check if `step-18` results differ from those in documentation (they do - these changes appear to remove the buckling previously exhibited by this problem)

### CODE REVIEW

**Comment by jppelteret** [comment]
This updated version of step-18 produces the same result as that of the [original step-18](https://github.com/dealii/dealii/blob/dealii-8.4/examples/step-18/step-18.cc), but with the rotation matrix fixed as suggested by @kuberry  in #468.

File: examples/step-18/step-18.cc [hunk 1]
```diff
@@ -313,44 +320,19 @@ namespace Step18
...
-        t *axis[1] *axis[2]+s *axis[0]
-      },
-      {
-        t *axis[0] *axis[2]+s *axis[1],
-        t *axis[1] *axis[1]-s *axis[0],
-        t *axis[2] *axis[2]+c
-      }
-    };
-    return Tensor<2,3>(rotation);
+    return Physics::Transformations::Angular::rotation_matrix_3d(axis,-angle);
```
Comment (tjhei) [inline examples/step-18/step-18.cc]: space before ``-angle``?

File: include/deal.II/physics/transformations.h [hunk 2]
```diff
@@ -29,6 +30,109 @@ namespace Physics
...
+    {
+      /**
+       * @name Rotation matrices
+       */
+//@{
+
+      /**
+      * Returns the rotation matrix for 2-d Euclidean space, namely
+      * @f[
+      *  \mathbf{R} := \left[ \begin{array}{ccc}
```
Comment (tjhei) [inline include/deal.II/physics/transformations.h]: cc instead of ccc?

**Comment by jppelteret** [comment]
@tjhei I'm not sure what you want to do about `step-18`'s results. Would you like to update them in this PR or leave them for later?

**Comment by tjhei** [comment]
> I'm not sure what you want to do about step-18's results. Would you like to update them in this PR or leave them for later?

I see that some of the output is outdated already (.d2 files?!). We need to update them for sure, but if you prefer to do that at a later time, just open an issue and we can merge this PR as is.

**Comment by jppelteret** [comment]
Ok, let's leave it for later then. I'll open an issue.

File: doc/news/changes/minor/20170109Jean-PaulPelteret_1 [hunk 3]
```diff
@@ -0,0 +1,6 @@
+Fixed: A bug in the rotation matrix used in step-18 has now been corrected.
+This tutorial now uses the function
+Physics::Transformations::Angular::rotation_matrix_3d to compute the 3d rotation
+matrix.
+<br>
+(Jean-Paul Pelteret, 2017/01/09)
```
Comment (bangerth) [inline doc/news/changes/minor/20170109Jean-PaulPelteret_1]: I think it would be nice to also credit @kuberry, who pointed out the problem in #468.

File: examples/step-18/step-18.cc [hunk 4]
```diff
@@ -280,11 +285,12 @@ namespace Step18
...
     const double angle = std::atan (curl);
 
-    // And from this, build the antisymmetric rotation matrix:
-    const double t[2][2] = {{ cos(angle), sin(angle) },
-      {-sin(angle), cos(angle) }
-    };
-    return Tensor<2,2>(t);
+    // And from this, build the antisymmetric rotation matrix. We want this
+    // rotation matrix to represent the rotation of the local coordinate system
+    // with respect to the global Cartesian bases, to we construct it with a
```
Comment (bangerth) [inline examples/step-18/step-18.cc]: basis?

File: examples/step-18/step-18.cc [hunk 5]
```diff
@@ -299,7 +305,8 @@ namespace Step18
                          grad_u[1][0] - grad_u[0][1]);
 
     // From this vector, using its magnitude, compute the tangent of the angle
-    // of rotation, and from it the actual angle:
+    // of rotation, and from it the actual angle of rotation with respect to
+    // the Cartesian bases:
```
Comment (bangerth) [inline examples/step-18/step-18.cc]: same here

File: include/deal.II/physics/transformations.h [hunk 6]
```diff
@@ -29,6 +30,73 @@ namespace Physics
   {
 
     /**
+     * Transformation functions and tensors that are defined in terms of
+     * rotation angles and axes of rotation.
+     *
+     * @author Jean-Paul Pelteret, 2017
+    */
+    namespace Angular
```
Comment (bangerth) [inline include/deal.II/physics/transformations.h]: That's an adjective, but we've usually named namespaces as nouns. Since you're dealing with rotations etc, why not just call the namespace `Rotations` or similar?

File: include/deal.II/physics/transformations.h [hunk 7]
```diff
@@ -29,6 +30,73 @@ namespace Physics
...
+      *  \mathbf{R} := \left[ \begin{array}{cc}
+      *  cos(\theta) & sin(\theta) \\
+      *  -sin(\theta) & cos(\theta)
+      * \end{array}\right]
+      * @f]
+      * where $\theta$ is the rotation angle given in radians.
+      * In particular, this describes the rotation of a vector
+      * relative to a <a href="http://mathworld.wolfram.com/RotationMatrix.html">fixed set of axes</a>.
+      *
+      * @param[in] angle The rotation angle (about the z-axis) in radians
```
Comment (bangerth) [inline include/deal.II/physics/transformations.h]: maybe say "counter-clockwise" here? (I assume that's what you mean.)

File: include/deal.II/physics/transformations.h [hunk 8]
```diff
@@ -789,6 +857,55 @@ namespace internal
 
 
 
+template<typename Number>
+Tensor<2,2,Number>
+Physics::Transformations::Angular::rotation_matrix_2d (const Number &angle)
+{
+  return Tensor<2,2> (
+  {
+    {
```
Comment (bangerth) [inline include/deal.II/physics/transformations.h]: This requires C++11. But you can make it compatible with C++98 if you just declare a 2x2 local array and pass that as explicit argument to the constructor.

File: include/deal.II/physics/transformations.h [hunk 9]
```diff
@@ -789,6 +857,55 @@ namespace internal
...
+                                                       const Number          &angle)
+{
+  Assert(std::abs(axis.norm() - 1.0) < 1e-9,
+         ExcMessage("The supplied axial vector is not a unit vector."));
+  const Number c = std::cos(angle);
+  const Number s = std::sin(angle);
+  const Number t = 1.-c;
+  return Tensor<2,3,Number>(
+  {
+    {
```
Comment (bangerth) [inline include/deal.II/physics/transformations.h]: same here

File: doc/news/changes/minor/20170109Jean-PaulPelteret_1 (hunk 3 above)
Comment (jppelteret) [inline doc/news/changes/minor/20170109Jean-PaulPelteret_1]: Yes of course, that was an oversight on my part. @kuberry would you mind providing me with your name so that I can add it to the changelog?

File: include/deal.II/physics/transformations.h (hunk 8 above)
Comment (jppelteret) [inline include/deal.II/physics/transformations.h]: Ok thanks. I was trying to avoid the creation of temporary data, but if its not C++98 compatible I'll make the change.

File: doc/news/changes/minor/20170109Jean-PaulPelteret_1 (hunk 3 above)
Comment (kuberry) [inline doc/news/changes/minor/20170109Jean-PaulPelteret_1]: Sure, it is Paul Kuberry.

File: include/deal.II/physics/transformations.h (hunk 8 above)
Comment (bangerth) [inline include/deal.II/physics/transformations.h]: Yes, let the compiler take care of moving data around as necessary. At least in optimized mode, the end result will be exactly the same.

File: doc/news/changes/minor/20170109Jean-PaulPelteret_1 (hunk 3 above)
Comment (jppelteret) [inline doc/news/changes/minor/20170109Jean-PaulPelteret_1]: Thanks a lot!

File: include/deal.II/physics/transformations.h (hunk 7 above)
Comment (jppelteret) [inline include/deal.II/physics/transformations.h]: I've updated both of the descriptions of the rotations to be more specific. Would you mind please confirming that you're happy with the changes I've made?

**Comment by bangerth** [comment]
Yes, looks good. Thanks for the work!

Feel free to merge once the tester is happy (or obviously stuck on something unrelated, as it appears to have done on occasion recently).
