### PR TITLE
Throw when running into errors reading gmsh files.

### LINKED ISSUE #18914: GridIn throws runtime error when reading high-order (quadratic) Gmsh mesh
[cube.zip](https://github.com/user-attachments/files/22698849/cube.zip)

I am working on an eigenvalue problem using FE_SimplexP<3>(2) and would like to use a quadratic Gmsh mesh (.msh format with high-order nodes).

When I try to load such a mesh with the following code:

```
GridIn<3> grid_in;
grid_in.attach_triangulation(triangulation);
grid_in.read_msh("file_X.msh");

```
I get this error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```
I assume this happens because GridIn currently does not support high-order (curved) elements in Gmsh files.

Is there currently support — or any planned support — for reading high-order Gmsh meshes directly in deal.II?

If not, it might be helpful to produce a clearer message instead of the generic std::out_of_range exception when encountering such meshes. ( I spend days debugging the real problem)

**Additional Information**

I provided the .msh file that triggers this error if needed for debugging. Also, I can provide the code that generates the mesh if needed.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #18914.

I must admit that I'm not clear why OP in #18914 didn't get the error we produce given that we have 
```
            if (cell_type == ...)
               ...
            else
              {
                AssertThrow(false, ExcGmshUnsupportedGeometry(cell_type));
              }
```

### CODE REVIEW

File: source/grid/grid_in.cc [hunk 1]
```diff
@@ -2818,8 +2824,10 @@ GridIn<dim, spacedim>::read_msh(std::istream &input_stream)
                          std::numeric_limits<types::boundary_id>::max()));
                 // we use only boundary_ids in the range from 0 to
                 // numbers::internal_face_boundary_id-1
-                AssertIndexRange(material_id,
-                                 numbers::internal_face_boundary_id);
+                Assert(material_id < numbers::internal_face_boundary_id,
```
Comment (gassmoeller) [inline source/grid/grid_in.cc]: Above you convert AssertIndexRange into AssertThrow, here into Assert. What is different about this location?

Also do we have written guidelines somewhere on when to use `Assert` vs `AssertThrow`? I know the difference in their behavior, but I am not sure I fully grasp when to use one vs the other in deal.II.

**Comment by bangerth** [comment]
Good catch. I fixed the place you marked up.

I don't have a definitive guideline for when to use `Assert` vs `AssertThrow`. We use `Assert` in places where you would run through the same code in the same way whether you are in debug or release mode -- say, adding two vectors and asserting that they have the same size. We use `AssertThrow` to catch situations that have a run-time component. So you'd check that a file you're trying to read from is readable with `AssertThrow`. Here, I think it is not unreasonable for people to run small test cases on small meshes in debug mode, conclude that the code runs, switch to release mode, and then load the big mesh they really wanted to compute on. So the reading *of this specific file* would then be something that has not been tested with the `Assert` statements in the code, and I thought using `AssertThrow` is reasonable to catch those cases. I suspect that these statements are also not something that will make the code overall much slower because they are only executed in that one part of the code. I admit that there is an element of "judgment call" in all of this.
