### PR TITLE
Use MUMPS in SLEPcWrappers test

### LINKED ISSUE #5141: slepc/step-36_parallel_02 failing
Currently, I get

> 8360: DEAL::Jacobi
 8360: DEAL::KrylovSchur
 8360:
 8360: slepc/step-36_parallel_02.mpirun=3.debug: RUN failed. ------ Additional output on stdout/stderr:
 8360:
 8360: [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
 8360: [0]PETSC ERROR: No support for this operation for this object type
 8360: [0]PETSC ERROR: You chose to solve linear systems with a factorization, but in parallel runs you need to select an external package; see the users guide for      details
 8360: [0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
 8360: [0]PETSC ERROR: Petsc Release Version 3.6.3, Dec, 03, 2015
 8360: [0]PETSC ERROR: /mnt/data/darndt/Sources/dealii/build/tests/slepc/step-36_parallel_02.debug/step-36_parallel_02.debug on a arch-linux2-c-opt named simserv02 by   darndt Sun Sep 24 14:48:35 2017
 8360: [0]PETSC ERROR: Configure options --with-debugging=0 --download-hypre --with-64-bit-indices

This seems to be similar to #1117.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5141.
Even when compiling  `PETSc` with `MUMPS` we still need tell `PETSc` to actually use this package ( at least in my configuration using `petsc-3.6.3`). Hence, I am still puzzled that `slepc/step-36_parallel_02` possibly passes.
~~This PR explicitly enables `MUMPS` for `SLEPcWrappers::SolverKrylovSchur`.~~

### CODE REVIEW

File: source/lac/slepc_solver.cc [hunk 1]
```diff
@@ -320,6 +320,10 @@ namespace SLEPcWrappers
     const PetscErrorCode ierr = EPSSetType (eps,
                                             const_cast<char *>(EPSKRYLOVSCHUR));
     AssertThrow (ierr == 0, ExcSLEPcError(ierr));
+
+#ifdef PETSC_HAVE_MUMPS
+    PETScWrappers::set_option_value("-st_pc_factor_mat_solver_package", "mumps");
```
Comment (davydden) [inline source/lac/slepc_solver.cc]: Please move it to the test. Otherwise you are forcing this always regardless to what solvers are combined with spectral transformation (which u can)

File: include/deal.II/lac/slepc_solver.h [hunk 2]
```diff
@@ -384,6 +384,8 @@ namespace SLEPcWrappers
    * An implementation of the solver interface using the SLEPc Krylov-Schur
    * solver. Usage: All spectrum, all problem types, complex.
    *
+   * If available, MUMPS is used for factorization.
```
Comment (davydden) [inline include/deal.II/lac/slepc_solver.h]: ...and remove that

File: source/lac/slepc_solver.cc (hunk 1 above)
Comment (masterleinad) [reply source/lac/slepc_solver.cc]: Hmm... This just changes the default to use, isn't it? You can always override this property afterwards. In particular, this allows to run the test without further changes which seems to be advantageous. What are the disadvantages?

Comment (davydden) [reply source/lac/slepc_solver.cc]: No, some time ago I reworked slepc spectral transformation to accept our PETSc wrappers for solvers. With this change you override this

Comment (davydden) [reply source/lac/slepc_solver.cc]: It’s NOT default, it says use this no matter what

Comment (davydden) [reply source/lac/slepc_solver.cc]: https://www.dealii.org/8.5.0/doxygen/deal.II/classSLEPcWrappers_1_1TransformationBase.html#af238a03c00c7dbaeb60bdc6e6e710443

Comment (masterleinad) [reply source/lac/slepc_solver.cc]: So you are saying that `set_transformation` is not overriding the previous options?

Comment (davydden) [reply source/lac/slepc_solver.cc]: > So you are saying that set_transformation is not overriding the previous options?

you are not setting spectral transformation here, you are setting a solver to be used in spectral transformation. 

And yes, any command-like parameter will override whatever accomodations we are doing with object-oriented-proramming and making spectral transformation know about the solver via ` SLEPcWrappers::TransformationBase::::set_solver()` which internally calls `STSetKSP`.

Comment (davydden) [reply source/lac/slepc_solver.cc]: FYI [step-36_parallel.cc](https://github.com/dealii/dealii/blob/master/tests/slepc/step-36_parallel.cc#L287) is the only test which uses this feature. But the trick is -- you won't see the difference from outside if everything works as your eigenpairs should be the same.
