### PR TITLE
Provide a second error for Trilinos sparsity pattern problems.

### LINKED ISSUE #13428: Failure when building Trilinos matrices with more than 2B entries
@marcfehling ran into a problem where he has a matrix with 15,110,817 rows and columns, and 2,280,732,000 entries (just barely more than the 2,147,483,647 that form the upper end of what a signed int can represent). This then leads to a segfault as follows:
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1554af260000)
 4  /expanse/lustre/projects/ucd150/mfehling/bin/aocc/trilinos-13.0.1/lib/libepetra.so.13(Epetra_CrsGraph::OptimizeStorage()+0x4e7) [0x155543905307]
 5  /home/mfehling/project/bin/aocc/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre(dealii::TrilinosWrappers::SparsityPattern::compress()+0x110) [0x155550e8ec30]
 6  /home/mfehling/project/bin/aocc/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre(dealii::BlockSparsityPatternBase<dealii::TrilinosWrappers::SparsityPattern>::compress()+0x6d) [0x155550cfb05d]
 7  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(Problem::Stokes<3, Trilinos, 3>::setup_system()+0xe98) [0x43a9f8]
 8  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(Problem::Stokes<3, Trilinos, 3>::run()+0x45f) [0x4390cf]
 9  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(main+0x2a1) [0x33cbd1]
10  /lib64/libc.so.6(__libc_start_main+0xf3) [0x15553f7f5873]
11  /expanse/lustre/projects/ucd150/mfehling/build-parallel-matrixfree-hp/stokes(_start+0x2e) [0x33c86e]
```
He reports that this happens both with compiling in 32- and 64-bit mode.

We should take a look at whether we call one of Trilinos's 32-bit functions by accident where there is a 64-bit function we should be calling instead.

### PR DESCRIPTION
**Pull request by bangerth**
This is another patch to fix #13428, in addition to #13445. I think we want both.

In essence, at some point or other we are going to call `Epetra_CrsGraph::OptimizeStorage()`, which internally looks like this:
```
int Epetra_CrsGraph::OptimizeStorage() {
  [...]

  if(!Contiguous) { // Must pack indices if not already contiguous

    // Allocate one big integer array for all index values
    if (!(StaticProfile())) { // If static profile, All_Indices_ is already allocated, only need to pack data
      int errorcode = Data.All_Indices_.Size(CrsGraphData_->NumMyNonzeros_);
      if(errorcode != 0) throw ReportError("Error with All_Indices_ allocation.", -99);
    }
```
When we allocate too much memory, `CrsGraphData_->NumMyNonzeros_` has overflown and is a negative integer, and then the call to `Data.All_Indices_.Size()` (which is really a *re*size operation) returns an error code. Helpfully (not!), the function we're looking at here decides to not just return this fact as an error code as it's supposed to do, but instead throw an integer exception. That's just poor design :-(

In deal.II, we correctly check the integer error code, but we miss the exception, which then propagates upward to places where we lost track where things happened. This patch avoids that and translates the integer exception into something more readable. I've verified that with the test in #13428 (but without the assertions in #13445), we now catch the exception and provide a better error messages.

I believe that this should also catch the case @marcfehling is considering, and that uses different code paths than #13445. #13445 is able to give error messages earlier, and so I think it is still useful.

/rebuild

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by marcfehling — APPROVED** [review]
I'll try your branch out, and see if I can reproduce it in the original problem.

**Comment by marcfehling** [comment]
Your exception gets triggered in my code. Thank you :)
```
----------------------------------------------------
Exception on processing: 

--------------------------------------------------------
An error occurred in line <730> of file </raid/fehling/dealii/source/lac/trilinos_sparsity_pattern.cc> in function
    void dealii::TrilinosWrappers::SparsityPattern::compress()
The violated condition was: 
    false
Additional information: 
    The Epetra_CrsGraph::OptimizeStorage() function has thrown an error
    with code -99. You will have to look up the exact meaning of this
    error in the Trilinos source code, but oftentimes, this function
    throwing an error indicates that you are trying to allocate more than
    2,147,483,647 nonzero entries in the sparsity pattern on the local
    process; this will not work because Trilinos indexes entries with a
    simple 'signed int'.

Stacktrace:
-----------
#0  /raid/fehling/bin/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre: 
#1  /raid/fehling/bin/dealii-10.0.0-pre/lib/libdeal_II.so.10.0.0-pre: dealii::BlockSparsityPatternBase<dealii::TrilinosWrappers::SparsityPattern>::compress()
#2  ../stokes: Problem::Stokes<3, Trilinos, 3>::setup_system()
#3  ../stokes: Problem::Stokes<3, Trilinos, 3>::run()
#4  ../stokes: main
--------------------------------------------------------

```

**Comment by marcfehling** [comment]
... with two processes. I get a segfault with one process.

I guess it's something related. I'll let gdb provide some more information.

Good to be merged from my side!

**Comment by marcfehling** [comment]
Yes, it's exactly in `OptimizeStorage()`.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffc91f9015 in Epetra_CrsGraph::OptimizeStorage() ()
   from /raid/fehling/bin/trilinos-13.0.0/lib/libepetra.so.13
```

Nothing we can do here. I can try to switch to the latest release `13.2.0`, but I doubt it will be different. Let's see what https://github.com/trilinos/Trilinos/issues/10249 leads to :)

File: source/lac/trilinos_sparsity_pattern.cc [hunk 1]
```diff
@@ -710,7 +710,25 @@ namespace TrilinosWrappers
...
+          ExcMessage(
+            "The Epetra_CrsGraph::OptimizeStorage() function "
+            "has thrown an error with code " +
+            std::to_string(error_code) +
+            ". You will have to look up the exact meaning of this error "
+            "in the Trilinos source code, but oftentimes, this function "
+            "throwing an error indicates that you are trying to allocate "
+            "more than 2,147,483,647 nonzero entries in the sparsity "
+            "pattern on the local process; this will not work because "
+            "Trilinos indexes entries with a simple 'signed int'."));
```
Comment (kronbichler) [inline source/lac/trilinos_sparsity_pattern.cc:730]: Maybe we should be more specific here:
```suggestion
            "Epetra indexes entries with a simple 'signed int'."));
```
Or also `Trilinos' Epetra` would work for me. I think we might otherwise imply that all of Trilinos would have this behavior, which is not true as far as I know.

**Comment by bangerth** [comment]
Good point. So updated!

**Review by kronbichler — APPROVED** [review]
