### PR TITLE
CMake: Bugfix: run get_latest_tag only if git is recent enough

### LINKED ISSUE #4420: Issues with tag information and older git versions
When I run `cmake` with a relatively old git version (1.8.3.1, the version
shipping with Red Hat 7) I encounter the following error output:

```
-- Include /home/wellsd2/Documents/Code/CPP/dealii-dev/cmake/setup_finalize.cmake
--
-- Include /home/wellsd2/Documents/Code/CPP/dealii-dev/cmake/setup_write_config.cmake
-- Query git repository information.
error: unknown option `sort=-creatordate'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>]
                [<pattern>...]
   or: git tag -v <tagname>...

    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags

Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns

Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object
```

we should just disable tag detection if the current version of git does not support this option.

### PR DESCRIPTION
**Pull request by tamiko**
Fixes #4420

### CODE REVIEW

**Comment by davydden** [comment]
@drwells please check if this fixes your problem, which it should.

File: cmake/scripts/get_latest_tag.sh [hunk 1]
```diff
@@ -4,6 +4,11 @@
 # current HEAD
 #
 
+if ! git --version | grep -q "git version 2"; then
+  # This script requires version 2 or newer
+  exit 1
```
Comment (davydden) [inline cmake/scripts/get_latest_tag.sh]: i don't mind either way, but we may fallback to `git describe --tags --abbrev=0`

Comment (davydden) [inline cmake/scripts/get_latest_tag.sh]: on a second though, i guess it's fine to simply return `1` as you do here so that we do not set `tag` in CMake script.
